/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_impl_dae_fun_jac_x_xdot_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[61] = 
  {13, 13, 0, 0, 0, 0, 1, 2,
  3, 9, 15, 21, 27, 33, 39, 45,
  0, 1, 2, 3, 4, 5, 7, 8,
  9, 3, 4, 5, 6, 8, 9, 3,
  4, 5, 6, 7, 9, 3, 4, 5,
  6, 7, 8, 6, 7, 8, 9, 11,
  12, 6, 7, 8, 9, 10, 12, 6,
  7, 8, 9, 10, 11};
static const casadi_int casadi_s5[29] = 
  {13, 13, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 10, 11, 12};
static const casadi_int casadi_s6[3] = {13, 0, 1};

/* quadrotor_ode_impl_dae_fun_jac_x_xdot_z:(i0[13],i1[13],i2[6],i3[0],i4[],i5[0])->(o0[13],o1[13x13,45nz],o2[13x13,13nz],o3[13x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36;
  a00=arg[1]? arg[1][0] : 0;
  a01=arg[0]? arg[0][3] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[1]? arg[1][1] : 0;
  a01=arg[0]? arg[0][4] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[1]? arg[1][2] : 0;
  a01=arg[0]? arg[0][5] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][3] : 0;
  a01=1.;
  a02=2.;
  a03=arg[0]? arg[0][8] : 0;
  a04=casadi_sq(a03);
  a05=arg[0]? arg[0][9] : 0;
  a06=casadi_sq(a05);
  a07=(a04+a06);
  a07=(a02*a07);
  a07=(a01-a07);
  a08=arg[2]? arg[2][0] : 0;
  a07=(a07*a08);
  a09=arg[0]? arg[0][7] : 0;
  a10=(a09*a03);
  a11=arg[0]? arg[0][6] : 0;
  a12=(a05*a11);
  a13=(a10-a12);
  a13=(a02*a13);
  a14=arg[2]? arg[2][1] : 0;
  a13=(a13*a14);
  a07=(a07+a13);
  a13=(a09*a05);
  a15=(a03*a11);
  a16=(a13+a15);
  a16=(a02*a16);
  a17=arg[2]? arg[2][2] : 0;
  a16=(a16*a17);
  a07=(a07+a16);
  a00=(a00-a07);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][4] : 0;
  a10=(a10+a12);
  a10=(a02*a10);
  a10=(a10*a08);
  a12=casadi_sq(a09);
  a06=(a12+a06);
  a06=(a02*a06);
  a06=(a01-a06);
  a06=(a06*a14);
  a10=(a10+a06);
  a06=(a03*a05);
  a07=(a09*a11);
  a16=(a06-a07);
  a16=(a02*a16);
  a16=(a16*a17);
  a10=(a10+a16);
  a00=(a00-a10);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][5] : 0;
  a13=(a13-a15);
  a13=(a02*a13);
  a13=(a13*a08);
  a06=(a06+a07);
  a06=(a02*a06);
  a06=(a06*a14);
  a13=(a13+a06);
  a12=(a12+a04);
  a12=(a02*a12);
  a12=(a01-a12);
  a12=(a12*a17);
  a13=(a13+a12);
  a12=9.8066499999999994e+00;
  a13=(a13-a12);
  a00=(a00-a13);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[1]? arg[1][6] : 0;
  a13=5.0000000000000000e-01;
  a12=arg[0]? arg[0][10] : 0;
  a04=(a12*a09);
  a06=arg[0]? arg[0][11] : 0;
  a07=(a06*a03);
  a04=(a04+a07);
  a07=arg[0]? arg[0][12] : 0;
  a15=(a07*a05);
  a04=(a04+a15);
  a04=(a13*a04);
  a00=(a00+a04);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[1]? arg[1][7] : 0;
  a04=(a12*a11);
  a15=(a07*a03);
  a04=(a04+a15);
  a15=(a06*a05);
  a04=(a04-a15);
  a04=(a13*a04);
  a00=(a00-a04);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[1]? arg[1][8] : 0;
  a04=(a06*a11);
  a15=(a07*a09);
  a04=(a04-a15);
  a15=(a12*a05);
  a04=(a04+a15);
  a04=(a13*a04);
  a00=(a00-a04);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[1]? arg[1][9] : 0;
  a04=(a07*a11);
  a15=(a06*a09);
  a04=(a04+a15);
  a15=(a12*a03);
  a04=(a04-a15);
  a04=(a13*a04);
  a00=(a00-a04);
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[1]? arg[1][10] : 0;
  a04=6.6666666666666671e+01;
  a15=arg[2]? arg[2][3] : 0;
  a10=7.0000000000000001e-03;
  a16=(a10*a07);
  a18=(a06*a16);
  a19=1.4999999999999999e-02;
  a20=(a19*a06);
  a21=(a07*a20);
  a18=(a18-a21);
  a15=(a15+a18);
  a15=(a04*a15);
  a00=(a00-a15);
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[1]? arg[1][11] : 0;
  a15=arg[2]? arg[2][4] : 0;
  a18=(a19*a12);
  a21=(a07*a18);
  a22=(a12*a16);
  a21=(a21-a22);
  a15=(a15+a21);
  a15=(a04*a15);
  a00=(a00-a15);
  if (res[0]!=0) res[0][11]=a00;
  a00=arg[1]? arg[1][12] : 0;
  a15=1.4285714285714286e+02;
  a21=arg[2]? arg[2][5] : 0;
  a22=(a12*a20);
  a23=(a06*a18);
  a22=(a22-a23);
  a21=(a21+a22);
  a15=(a15*a21);
  a00=(a00-a15);
  if (res[0]!=0) res[0][12]=a00;
  a00=-1.;
  if (res[1]!=0) res[1][0]=a00;
  if (res[1]!=0) res[1][1]=a00;
  if (res[1]!=0) res[1][2]=a00;
  a00=(a02*a03);
  a15=(a17*a00);
  a21=(a02*a05);
  a22=(a14*a21);
  a23=(a15-a22);
  a23=(-a23);
  if (res[1]!=0) res[1][3]=a23;
  a23=(a08*a21);
  a24=(a02*a09);
  a25=(a17*a24);
  a26=(a23-a25);
  a26=(-a26);
  if (res[1]!=0) res[1][4]=a26;
  a26=(a14*a24);
  a27=(a08*a00);
  a28=(a26-a27);
  a28=(-a28);
  if (res[1]!=0) res[1][5]=a28;
  a28=(a13*a12);
  a29=(-a28);
  if (res[1]!=0) res[1][6]=a29;
  a30=(a13*a06);
  a31=(-a30);
  if (res[1]!=0) res[1][7]=a31;
  a32=(a13*a07);
  a33=(-a32);
  if (res[1]!=0) res[1][8]=a33;
  a00=(a14*a00);
  a21=(a17*a21);
  a34=(a00+a21);
  a34=(-a34);
  if (res[1]!=0) res[1][9]=a34;
  a34=(a09+a09);
  a34=(a02*a34);
  a35=(a14*a34);
  a27=(a27-a35);
  a35=(a02*a11);
  a36=(a17*a35);
  a27=(a27-a36);
  a27=(-a27);
  if (res[1]!=0) res[1][10]=a27;
  a27=(a14*a35);
  a23=(a23+a27);
  a34=(a17*a34);
  a23=(a23-a34);
  a23=(-a23);
  if (res[1]!=0) res[1][11]=a23;
  if (res[1]!=0) res[1][12]=a28;
  if (res[1]!=0) res[1][13]=a32;
  if (res[1]!=0) res[1][14]=a31;
  a31=(a03+a03);
  a31=(a02*a31);
  a23=(a08*a31);
  a26=(a26-a23);
  a26=(a26+a36);
  a26=(-a26);
  if (res[1]!=0) res[1][15]=a26;
  a24=(a08*a24);
  a21=(a24+a21);
  a21=(-a21);
  if (res[1]!=0) res[1][16]=a21;
  a35=(a08*a35);
  a22=(a22-a35);
  a17=(a17*a31);
  a22=(a22-a17);
  a22=(-a22);
  if (res[1]!=0) res[1][17]=a22;
  if (res[1]!=0) res[1][18]=a30;
  if (res[1]!=0) res[1][19]=a33;
  if (res[1]!=0) res[1][20]=a28;
  a28=(a05+a05);
  a02=(a02*a28);
  a08=(a08*a02);
  a08=(a08+a27);
  a25=(a25-a08);
  a25=(-a25);
  if (res[1]!=0) res[1][21]=a25;
  a14=(a14*a02);
  a35=(a35-a14);
  a35=(a35+a15);
  a35=(-a35);
  if (res[1]!=0) res[1][22]=a35;
  a24=(a24+a00);
  a24=(-a24);
  if (res[1]!=0) res[1][23]=a24;
  if (res[1]!=0) res[1][24]=a32;
  if (res[1]!=0) res[1][25]=a30;
  if (res[1]!=0) res[1][26]=a29;
  a09=(a13*a09);
  if (res[1]!=0) res[1][27]=a09;
  a11=(a13*a11);
  a11=(-a11);
  if (res[1]!=0) res[1][28]=a11;
  a05=(a13*a05);
  a29=(-a05);
  if (res[1]!=0) res[1][29]=a29;
  a13=(a13*a03);
  if (res[1]!=0) res[1][30]=a13;
  a19=(a19*a07);
  a07=(a19-a16);
  a07=(a04*a07);
  a07=(-a07);
  if (res[1]!=0) res[1][31]=a07;
  a07=0.;
  if (res[1]!=0) res[1][32]=a07;
  if (res[1]!=0) res[1][33]=a13;
  if (res[1]!=0) res[1][34]=a05;
  if (res[1]!=0) res[1][35]=a11;
  a03=(-a09);
  if (res[1]!=0) res[1][36]=a03;
  a16=(a16-a19);
  a16=(a04*a16);
  a16=(-a16);
  if (res[1]!=0) res[1][37]=a16;
  if (res[1]!=0) res[1][38]=a07;
  if (res[1]!=0) res[1][39]=a05;
  a13=(-a13);
  if (res[1]!=0) res[1][40]=a13;
  if (res[1]!=0) res[1][41]=a09;
  if (res[1]!=0) res[1][42]=a11;
  a06=(a10*a06);
  a06=(a06-a20);
  a06=(a04*a06);
  a06=(-a06);
  if (res[1]!=0) res[1][43]=a06;
  a10=(a10*a12);
  a18=(a18-a10);
  a04=(a04*a18);
  a04=(-a04);
  if (res[1]!=0) res[1][44]=a04;
  if (res[2]!=0) res[2][0]=a01;
  if (res[2]!=0) res[2][1]=a01;
  if (res[2]!=0) res[2][2]=a01;
  if (res[2]!=0) res[2][3]=a01;
  if (res[2]!=0) res[2][4]=a01;
  if (res[2]!=0) res[2][5]=a01;
  if (res[2]!=0) res[2][6]=a01;
  if (res[2]!=0) res[2][7]=a01;
  if (res[2]!=0) res[2][8]=a01;
  if (res[2]!=0) res[2][9]=a01;
  if (res[2]!=0) res[2][10]=a01;
  if (res[2]!=0) res[2][11]=a01;
  if (res[2]!=0) res[2][12]=a01;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_fun_jac_x_xdot_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_fun_jac_x_xdot_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_fun_jac_x_xdot_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_impl_dae_fun_jac_x_xdot_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_fun_jac_x_xdot_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_impl_dae_fun_jac_x_xdot_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_impl_dae_fun_jac_x_xdot_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_impl_dae_fun_jac_x_xdot_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_impl_dae_fun_jac_x_xdot_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_impl_dae_fun_jac_x_xdot_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_impl_dae_fun_jac_x_xdot_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_impl_dae_fun_jac_x_xdot_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_impl_dae_fun_jac_x_xdot_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_impl_dae_fun_jac_x_xdot_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_impl_dae_fun_jac_x_xdot_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_fun_jac_x_xdot_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_fun_jac_x_xdot_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
