/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_cost_y_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {27, 1, 1};

/* quadrotor_ode_cost_y_0_fun:(i0[13],i1[6],i2[0],i3[],i4[6])->(o0[27]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  a00=arg[0]? arg[0][0] : 0;
  a01=arg[4]? arg[4][0] : 0;
  a00=(a00-a01);
  a01=casadi_sq(a00);
  a02=arg[0]? arg[0][1] : 0;
  a03=arg[4]? arg[4][1] : 0;
  a02=(a02-a03);
  a03=casadi_sq(a02);
  a01=(a01+a03);
  a03=arg[0]? arg[0][2] : 0;
  a04=arg[4]? arg[4][2] : 0;
  a03=(a03-a04);
  a04=casadi_sq(a03);
  a01=(a01+a04);
  a01=sqrt(a01);
  if (res[0]!=0) res[0][0]=a01;
  a00=atan2(a00,a02);
  if (res[0]!=0) res[0][1]=a00;
  a03=(a03/a01);
  a03=asin(a03);
  if (res[0]!=0) res[0][2]=a03;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a03=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a03;
  a03=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a03;
  a03=arg[4]? arg[4][4] : 0;
  a01=cos(a03);
  a00=arg[4]? arg[4][3] : 0;
  a02=sin(a00);
  a02=(a01*a02);
  a04=2.;
  a05=arg[0]? arg[0][6] : 0;
  a06=arg[0]? arg[0][9] : 0;
  a07=(a05*a06);
  a08=arg[0]? arg[0][7] : 0;
  a09=arg[0]? arg[0][8] : 0;
  a10=(a08*a09);
  a07=(a07+a10);
  a07=(a04*a07);
  a11=1.;
  a12=casadi_sq(a09);
  a13=casadi_sq(a06);
  a14=(a12+a13);
  a14=(a04*a14);
  a14=(a11-a14);
  a07=atan2(a07,a14);
  a15=sin(a07);
  a16=(a05*a09);
  a17=(a06*a08);
  a16=(a16-a17);
  a16=(a04*a16);
  a16=asin(a16);
  a17=sin(a16);
  a18=(a15*a17);
  a19=(a05*a08);
  a20=(a09*a06);
  a19=(a19+a20);
  a19=(a04*a19);
  a21=casadi_sq(a08);
  a12=(a21+a12);
  a12=(a04*a12);
  a12=(a11-a12);
  a19=atan2(a19,a12);
  a22=cos(a19);
  a18=(a18*a22);
  a07=cos(a07);
  a19=sin(a19);
  a23=(a07*a19);
  a18=(a18-a23);
  a02=(a02*a18);
  a00=cos(a00);
  a00=(a01*a00);
  a18=cos(a16);
  a23=(a18*a22);
  a00=(a00*a23);
  a02=atan2(a02,a00);
  if (res[0]!=0) res[0][6]=a02;
  a03=sin(a03);
  a17=(a07*a17);
  a02=(a17*a22);
  a00=(a15*a19);
  a02=(a02+a00);
  a03=(a03*a02);
  a03=(-a03);
  a03=asin(a03);
  a03=(-a03);
  if (res[0]!=0) res[0][7]=a03;
  a03=arg[4]? arg[4][5] : 0;
  a02=sin(a03);
  a02=(a02*a01);
  a17=(a17*a19);
  a15=(a15*a22);
  a17=(a17-a15);
  a02=(a02*a17);
  a03=cos(a03);
  a03=(a03*a01);
  a07=(a07*a18);
  a03=(a03*a07);
  a02=atan2(a02,a03);
  if (res[0]!=0) res[0][8]=a02;
  a02=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][9]=a02;
  a03=arg[0]? arg[0][11] : 0;
  a07=(a22*a03);
  a16=tan(a16);
  a18=(a19*a16);
  a01=arg[0]? arg[0][12] : 0;
  a18=(a18*a01);
  a07=(a07+a18);
  if (res[0]!=0) res[0][10]=a07;
  a22=(a22*a16);
  a22=(a22*a01);
  a19=(a19*a03);
  a22=(a22-a19);
  if (res[0]!=0) res[0][11]=a22;
  a22=arg[1]? arg[1][0] : 0;
  a14=(a14*a22);
  a19=(a06*a05);
  a16=(a10-a19);
  a16=(a04*a16);
  a07=arg[1]? arg[1][1] : 0;
  a16=(a16*a07);
  a14=(a14+a16);
  a16=(a08*a06);
  a18=(a09*a05);
  a17=(a16+a18);
  a17=(a04*a17);
  a15=arg[1]? arg[1][2] : 0;
  a17=(a17*a15);
  a14=(a14+a17);
  if (res[0]!=0) res[0][12]=a14;
  a10=(a10+a19);
  a10=(a04*a10);
  a10=(a10*a22);
  a21=(a21+a13);
  a21=(a04*a21);
  a11=(a11-a21);
  a11=(a11*a07);
  a10=(a10+a11);
  a11=(a08*a05);
  a21=(a20-a11);
  a21=(a04*a21);
  a21=(a21*a15);
  a10=(a10+a21);
  if (res[0]!=0) res[0][13]=a10;
  a16=(a16-a18);
  a16=(a04*a16);
  a16=(a16*a22);
  a20=(a20+a11);
  a20=(a04*a20);
  a20=(a20*a07);
  a16=(a16+a20);
  a12=(a12*a15);
  a16=(a16+a12);
  a12=9.8066499999999994e+00;
  a16=(a16-a12);
  if (res[0]!=0) res[0][14]=a16;
  a16=(a04*a09);
  a12=(a07*a16);
  a20=(a04*a06);
  a11=(a15*a20);
  a18=(a12+a11);
  a10=5.0000000000000000e-01;
  a21=(a02*a05);
  a13=(a01*a09);
  a21=(a21+a13);
  a13=(a03*a06);
  a21=(a21-a13);
  a21=(a10*a21);
  a13=(a18*a21);
  a19=(a15*a16);
  a14=(a07*a20);
  a17=(a19-a14);
  a00=(a02*a08);
  a23=(a03*a09);
  a00=(a00+a23);
  a23=(a01*a06);
  a00=(a00+a23);
  a00=(a10*a00);
  a23=(a17*a00);
  a13=(a13-a23);
  a23=(a04*a08);
  a24=(a07*a23);
  a25=(a09+a09);
  a25=(a04*a25);
  a26=(a22*a25);
  a26=(a24-a26);
  a27=(a04*a05);
  a28=(a15*a27);
  a26=(a26+a28);
  a29=(a03*a05);
  a30=(a01*a08);
  a29=(a29-a30);
  a30=(a02*a06);
  a29=(a29+a30);
  a29=(a10*a29);
  a30=(a26*a29);
  a13=(a13+a30);
  a30=(a15*a23);
  a31=(a06+a06);
  a31=(a04*a31);
  a32=(a22*a31);
  a33=(a07*a27);
  a32=(a32+a33);
  a32=(a30-a32);
  a34=(a01*a05);
  a35=(a03*a08);
  a34=(a34+a35);
  a35=(a02*a09);
  a34=(a34-a35);
  a34=(a10*a34);
  a35=(a32*a34);
  a13=(a13+a35);
  if (res[0]!=0) res[0][15]=a13;
  a16=(a22*a16);
  a13=(a08+a08);
  a13=(a04*a13);
  a35=(a07*a13);
  a35=(a16-a35);
  a35=(a35-a28);
  a28=(a35*a21);
  a20=(a22*a20);
  a30=(a20-a30);
  a36=(a30*a00);
  a28=(a28-a36);
  a23=(a22*a23);
  a11=(a23+a11);
  a36=(a11*a29);
  a28=(a28+a36);
  a27=(a22*a27);
  a31=(a07*a31);
  a31=(a27-a31);
  a31=(a31+a19);
  a19=(a31*a34);
  a28=(a28+a19);
  if (res[0]!=0) res[0][16]=a28;
  a20=(a20+a33);
  a13=(a15*a13);
  a20=(a20-a13);
  a13=(a20*a21);
  a24=(a24-a16);
  a16=(a24*a00);
  a13=(a13-a16);
  a14=(a14-a27);
  a25=(a15*a25);
  a14=(a14-a25);
  a25=(a14*a29);
  a13=(a13+a25);
  a23=(a23+a12);
  a12=(a23*a34);
  a13=(a13+a12);
  if (res[0]!=0) res[0][17]=a13;
  a32=(a10*a32);
  a13=(a03*a32);
  a12=(a15*a34);
  a12=(a04*a12);
  a13=(a13+a12);
  a26=(a10*a26);
  a25=(a01*a26);
  a13=(a13-a25);
  a25=(a07*a29);
  a25=(a04*a25);
  a13=(a13+a25);
  a17=(a10*a17);
  a27=(a02*a17);
  a13=(a13-a27);
  a13=(a13*a21);
  a27=(a01*a32);
  a16=(a07*a34);
  a16=(a04*a16);
  a27=(a27-a16);
  a33=(a03*a26);
  a27=(a27+a33);
  a33=(a15*a29);
  a33=(a04*a33);
  a27=(a27+a33);
  a18=(a10*a18);
  a28=(a02*a18);
  a27=(a27+a28);
  a27=(a27*a00);
  a13=(a13-a27);
  a27=(a01*a18);
  a28=(a02*a32);
  a19=(a22*a29);
  a19=(a04*a19);
  a28=(a28+a19);
  a28=(a28+a19);
  a36=(a03*a17);
  a28=(a28+a36);
  a36=(a15*a00);
  a36=(a04*a36);
  a28=(a28+a36);
  a27=(a27-a28);
  a28=(a07*a21);
  a28=(a04*a28);
  a27=(a27+a28);
  a27=(a27*a29);
  a13=(a13+a27);
  a27=(a02*a26);
  a37=(a22*a34);
  a37=(a04*a37);
  a38=(a37+a37);
  a27=(a27-a38);
  a38=(a01*a17);
  a27=(a27-a38);
  a38=(a07*a00);
  a38=(a04*a38);
  a27=(a27+a38);
  a39=(a03*a18);
  a27=(a27-a39);
  a39=(a15*a21);
  a39=(a04*a39);
  a27=(a27+a39);
  a27=(a27*a34);
  a13=(a13+a27);
  a27=(a06*a26);
  a40=(a09*a32);
  a27=(a27-a40);
  a40=(a08*a17);
  a27=(a27-a40);
  a40=(a05*a18);
  a27=(a27+a40);
  a40=6.6666666666666671e+01;
  a41=arg[1]? arg[1][3] : 0;
  a42=7.0000000000000001e-03;
  a42=(a42*a01);
  a43=(a03*a42);
  a44=1.4999999999999999e-02;
  a45=(a44*a03);
  a46=(a01*a45);
  a43=(a43-a46);
  a43=(a41-a43);
  a43=(a40*a43);
  a27=(a27*a43);
  a13=(a13+a27);
  a27=(a08*a32);
  a46=(a05*a26);
  a27=(a27+a46);
  a46=(a09*a17);
  a27=(a27-a46);
  a46=(a06*a18);
  a27=(a27-a46);
  a46=arg[1]? arg[1][4] : 0;
  a44=(a44*a02);
  a47=(a01*a44);
  a42=(a02*a42);
  a47=(a47-a42);
  a47=(a46-a47);
  a40=(a40*a47);
  a27=(a27*a40);
  a13=(a13+a27);
  a32=(a05*a32);
  a26=(a08*a26);
  a32=(a32-a26);
  a17=(a06*a17);
  a32=(a32-a17);
  a18=(a09*a18);
  a32=(a32+a18);
  a18=1.4285714285714286e+02;
  a17=arg[1]? arg[1][5] : 0;
  a45=(a02*a45);
  a44=(a03*a44);
  a45=(a45-a44);
  a45=(a17-a45);
  a18=(a18*a45);
  a32=(a32*a18);
  a13=(a13+a32);
  if (res[0]!=0) res[0][18]=a13;
  a36=(a19+a36);
  a36=(a36-a28);
  a36=(a36-a28);
  a31=(a10*a31);
  a13=(a03*a31);
  a36=(a36+a13);
  a11=(a10*a11);
  a13=(a01*a11);
  a36=(a36-a13);
  a30=(a10*a30);
  a13=(a02*a30);
  a36=(a36-a13);
  a36=(a36*a21);
  a13=(a37-a39);
  a32=(a01*a31);
  a13=(a13+a32);
  a32=(a03*a11);
  a13=(a13+a32);
  a35=(a10*a35);
  a32=(a02*a35);
  a13=(a13+a32);
  a13=(a13*a00);
  a36=(a36-a13);
  a13=(a22*a21);
  a13=(a04*a13);
  a12=(a12+a13);
  a32=(a02*a31);
  a12=(a12-a32);
  a32=(a03*a30);
  a12=(a12-a32);
  a32=(a01*a35);
  a12=(a12+a32);
  a12=(a12*a29);
  a36=(a36+a12);
  a12=(a16+a16);
  a12=(a33-a12);
  a32=(a22*a00);
  a04=(a04*a32);
  a12=(a12-a04);
  a32=(a02*a11);
  a12=(a12+a32);
  a32=(a01*a30);
  a12=(a12-a32);
  a32=(a03*a35);
  a12=(a12-a32);
  a12=(a12*a34);
  a36=(a36+a12);
  a12=(a06*a11);
  a32=(a09*a31);
  a12=(a12-a32);
  a32=(a08*a30);
  a12=(a12-a32);
  a32=(a05*a35);
  a12=(a12+a32);
  a12=(a12*a43);
  a36=(a36+a12);
  a12=(a08*a31);
  a32=(a05*a11);
  a12=(a12+a32);
  a32=(a09*a30);
  a12=(a12-a32);
  a32=(a06*a35);
  a12=(a12-a32);
  a12=(a12*a40);
  a36=(a36+a12);
  a31=(a05*a31);
  a11=(a08*a11);
  a31=(a31-a11);
  a30=(a06*a30);
  a31=(a31-a30);
  a35=(a09*a35);
  a31=(a31+a35);
  a31=(a31*a18);
  a36=(a36+a31);
  if (res[0]!=0) res[0][19]=a36;
  a37=(a37-a38);
  a37=(a37-a39);
  a37=(a37-a39);
  a23=(a10*a23);
  a39=(a03*a23);
  a37=(a37+a39);
  a14=(a10*a14);
  a39=(a01*a14);
  a37=(a37-a39);
  a24=(a10*a24);
  a39=(a02*a24);
  a37=(a37-a39);
  a37=(a37*a21);
  a28=(a28-a19);
  a19=(a01*a23);
  a28=(a28+a19);
  a19=(a03*a14);
  a28=(a28+a19);
  a10=(a10*a20);
  a20=(a02*a10);
  a28=(a28+a20);
  a28=(a28*a00);
  a37=(a37-a28);
  a16=(a16-a33);
  a16=(a16-a33);
  a16=(a16+a04);
  a04=(a02*a23);
  a16=(a16-a04);
  a04=(a03*a24);
  a16=(a16-a04);
  a04=(a01*a10);
  a16=(a16+a04);
  a16=(a16*a29);
  a37=(a37+a16);
  a25=(a25+a13);
  a02=(a02*a14);
  a25=(a25+a02);
  a01=(a01*a24);
  a25=(a25-a01);
  a03=(a03*a10);
  a25=(a25-a03);
  a25=(a25*a34);
  a37=(a37+a25);
  a25=(a06*a14);
  a34=(a09*a23);
  a25=(a25-a34);
  a34=(a08*a24);
  a25=(a25-a34);
  a34=(a05*a10);
  a25=(a25+a34);
  a25=(a25*a43);
  a37=(a37+a25);
  a25=(a08*a23);
  a43=(a05*a14);
  a25=(a25+a43);
  a43=(a09*a24);
  a25=(a25-a43);
  a43=(a06*a10);
  a25=(a25-a43);
  a25=(a25*a40);
  a37=(a37+a25);
  a05=(a05*a23);
  a08=(a08*a14);
  a05=(a05-a08);
  a06=(a06*a24);
  a05=(a05-a06);
  a09=(a09*a10);
  a05=(a05+a09);
  a05=(a05*a18);
  a37=(a37+a05);
  if (res[0]!=0) res[0][20]=a37;
  if (res[0]!=0) res[0][21]=a22;
  if (res[0]!=0) res[0][22]=a07;
  if (res[0]!=0) res[0][23]=a15;
  if (res[0]!=0) res[0][24]=a41;
  if (res[0]!=0) res[0][25]=a46;
  if (res[0]!=0) res[0][26]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_cost_y_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
