/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_cost_y_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {27, 1, 1};

/* quadrotor_ode_cost_y_0_fun:(i0[13],i1[6],i2[0],i3[],i4[6])->(o0[27]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  a00=arg[0]? arg[0][0] : 0;
  a01=arg[4]? arg[4][0] : 0;
  a00=(a00-a01);
  a01=casadi_sq(a00);
  a02=arg[0]? arg[0][1] : 0;
  a03=arg[4]? arg[4][1] : 0;
  a02=(a02-a03);
  a03=casadi_sq(a02);
  a01=(a01+a03);
  a03=arg[0]? arg[0][2] : 0;
  a04=arg[4]? arg[4][2] : 0;
  a03=(a03-a04);
  a04=casadi_sq(a03);
  a01=(a01+a04);
  a01=sqrt(a01);
  if (res[0]!=0) res[0][0]=a01;
  a00=atan2(a00,a02);
  if (res[0]!=0) res[0][1]=a00;
  a03=(a03/a01);
  a03=asin(a03);
  if (res[0]!=0) res[0][2]=a03;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a03=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a03;
  a03=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a03;
  a03=arg[4]? arg[4][5] : 0;
  a01=sin(a03);
  a00=arg[4]? arg[4][4] : 0;
  a02=sin(a00);
  a04=(a01*a02);
  a05=arg[4]? arg[4][3] : 0;
  a06=cos(a05);
  a04=(a04*a06);
  a03=cos(a03);
  a05=sin(a05);
  a07=(a03*a05);
  a04=(a04-a07);
  a07=2.;
  a08=arg[0]? arg[0][6] : 0;
  a09=arg[0]? arg[0][8] : 0;
  a10=(a08*a09);
  a11=arg[0]? arg[0][9] : 0;
  a12=arg[0]? arg[0][7] : 0;
  a13=(a11*a12);
  a10=(a10-a13);
  a10=(a07*a10);
  a10=asin(a10);
  a13=cos(a10);
  a14=(a08*a12);
  a15=(a09*a11);
  a14=(a14+a15);
  a14=(a07*a14);
  a16=1.;
  a17=casadi_sq(a12);
  a18=casadi_sq(a09);
  a19=(a17+a18);
  a19=(a07*a19);
  a19=(a16-a19);
  a14=atan2(a14,a19);
  a20=sin(a14);
  a21=(a13*a20);
  a04=(a04*a21);
  a00=cos(a00);
  a21=(a00*a06);
  a14=cos(a14);
  a22=(a13*a14);
  a21=(a21*a22);
  a04=atan2(a04,a21);
  if (res[0]!=0) res[0][6]=a04;
  a02=(a03*a02);
  a04=(a02*a06);
  a21=(a01*a05);
  a04=(a04+a21);
  a21=sin(a10);
  a04=(a04*a21);
  a04=(-a04);
  a04=asin(a04);
  a04=(-a04);
  if (res[0]!=0) res[0][7]=a04;
  a02=(a02*a05);
  a01=(a01*a06);
  a02=(a02-a01);
  a01=(a08*a11);
  a06=(a12*a09);
  a01=(a01+a06);
  a01=(a07*a01);
  a05=casadi_sq(a11);
  a18=(a18+a05);
  a18=(a07*a18);
  a18=(a16-a18);
  a01=atan2(a01,a18);
  a04=sin(a01);
  a04=(a04*a13);
  a02=(a02*a04);
  a03=(a03*a00);
  a01=cos(a01);
  a01=(a01*a13);
  a03=(a03*a01);
  a02=atan2(a02,a03);
  if (res[0]!=0) res[0][8]=a02;
  a02=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][9]=a02;
  a03=arg[0]? arg[0][11] : 0;
  a01=(a14*a03);
  a10=tan(a10);
  a13=(a20*a10);
  a00=arg[0]? arg[0][12] : 0;
  a13=(a13*a00);
  a01=(a01+a13);
  if (res[0]!=0) res[0][10]=a01;
  a14=(a14*a10);
  a14=(a14*a00);
  a20=(a20*a03);
  a14=(a14-a20);
  if (res[0]!=0) res[0][11]=a14;
  a14=arg[1]? arg[1][0] : 0;
  a18=(a18*a14);
  a20=(a11*a08);
  a10=(a06-a20);
  a10=(a07*a10);
  a01=arg[1]? arg[1][1] : 0;
  a10=(a10*a01);
  a18=(a18+a10);
  a10=(a12*a11);
  a13=(a09*a08);
  a04=(a10+a13);
  a04=(a07*a04);
  a21=arg[1]? arg[1][2] : 0;
  a04=(a04*a21);
  a18=(a18+a04);
  if (res[0]!=0) res[0][12]=a18;
  a06=(a06+a20);
  a06=(a07*a06);
  a06=(a06*a14);
  a17=(a17+a05);
  a17=(a07*a17);
  a16=(a16-a17);
  a16=(a16*a01);
  a06=(a06+a16);
  a16=(a12*a08);
  a17=(a15-a16);
  a17=(a07*a17);
  a17=(a17*a21);
  a06=(a06+a17);
  if (res[0]!=0) res[0][13]=a06;
  a10=(a10-a13);
  a10=(a07*a10);
  a10=(a10*a14);
  a15=(a15+a16);
  a15=(a07*a15);
  a15=(a15*a01);
  a10=(a10+a15);
  a19=(a19*a21);
  a10=(a10+a19);
  a19=9.8066499999999994e+00;
  a10=(a10-a19);
  if (res[0]!=0) res[0][14]=a10;
  a10=(a07*a09);
  a19=(a01*a10);
  a15=(a07*a11);
  a16=(a21*a15);
  a13=(a19+a16);
  a06=5.0000000000000000e-01;
  a17=(a02*a08);
  a05=(a00*a09);
  a17=(a17+a05);
  a05=(a03*a11);
  a17=(a17-a05);
  a17=(a06*a17);
  a05=(a13*a17);
  a20=(a21*a10);
  a18=(a01*a15);
  a04=(a20-a18);
  a22=(a02*a12);
  a23=(a03*a09);
  a22=(a22+a23);
  a23=(a00*a11);
  a22=(a22+a23);
  a22=(a06*a22);
  a23=(a04*a22);
  a05=(a05-a23);
  a23=(a07*a12);
  a24=(a01*a23);
  a25=(a09+a09);
  a25=(a07*a25);
  a26=(a14*a25);
  a26=(a24-a26);
  a27=(a07*a08);
  a28=(a21*a27);
  a26=(a26+a28);
  a29=(a03*a08);
  a30=(a00*a12);
  a29=(a29-a30);
  a30=(a02*a11);
  a29=(a29+a30);
  a29=(a06*a29);
  a30=(a26*a29);
  a05=(a05+a30);
  a30=(a21*a23);
  a31=(a11+a11);
  a31=(a07*a31);
  a32=(a14*a31);
  a33=(a01*a27);
  a32=(a32+a33);
  a32=(a30-a32);
  a34=(a00*a08);
  a35=(a03*a12);
  a34=(a34+a35);
  a35=(a02*a09);
  a34=(a34-a35);
  a34=(a06*a34);
  a35=(a32*a34);
  a05=(a05+a35);
  if (res[0]!=0) res[0][15]=a05;
  a10=(a14*a10);
  a05=(a12+a12);
  a05=(a07*a05);
  a35=(a01*a05);
  a35=(a10-a35);
  a35=(a35-a28);
  a28=(a35*a17);
  a15=(a14*a15);
  a30=(a15-a30);
  a36=(a30*a22);
  a28=(a28-a36);
  a23=(a14*a23);
  a16=(a23+a16);
  a36=(a16*a29);
  a28=(a28+a36);
  a27=(a14*a27);
  a31=(a01*a31);
  a31=(a27-a31);
  a31=(a31+a20);
  a20=(a31*a34);
  a28=(a28+a20);
  if (res[0]!=0) res[0][16]=a28;
  a15=(a15+a33);
  a05=(a21*a05);
  a15=(a15-a05);
  a05=(a15*a17);
  a24=(a24-a10);
  a10=(a24*a22);
  a05=(a05-a10);
  a18=(a18-a27);
  a25=(a21*a25);
  a18=(a18-a25);
  a25=(a18*a29);
  a05=(a05+a25);
  a23=(a23+a19);
  a19=(a23*a34);
  a05=(a05+a19);
  if (res[0]!=0) res[0][17]=a05;
  a32=(a06*a32);
  a05=(a03*a32);
  a19=(a21*a34);
  a19=(a07*a19);
  a05=(a05+a19);
  a26=(a06*a26);
  a25=(a00*a26);
  a05=(a05-a25);
  a25=(a01*a29);
  a25=(a07*a25);
  a05=(a05+a25);
  a04=(a06*a04);
  a27=(a02*a04);
  a05=(a05-a27);
  a05=(a05*a17);
  a27=(a00*a32);
  a10=(a01*a34);
  a10=(a07*a10);
  a27=(a27-a10);
  a33=(a03*a26);
  a27=(a27+a33);
  a33=(a21*a29);
  a33=(a07*a33);
  a27=(a27+a33);
  a13=(a06*a13);
  a28=(a02*a13);
  a27=(a27+a28);
  a27=(a27*a22);
  a05=(a05-a27);
  a27=(a00*a13);
  a28=(a02*a32);
  a20=(a14*a29);
  a20=(a07*a20);
  a28=(a28+a20);
  a28=(a28+a20);
  a36=(a03*a04);
  a28=(a28+a36);
  a36=(a21*a22);
  a36=(a07*a36);
  a28=(a28+a36);
  a27=(a27-a28);
  a28=(a01*a17);
  a28=(a07*a28);
  a27=(a27+a28);
  a27=(a27*a29);
  a05=(a05+a27);
  a27=(a02*a26);
  a37=(a14*a34);
  a37=(a07*a37);
  a38=(a37+a37);
  a27=(a27-a38);
  a38=(a00*a04);
  a27=(a27-a38);
  a38=(a01*a22);
  a38=(a07*a38);
  a27=(a27+a38);
  a39=(a03*a13);
  a27=(a27-a39);
  a39=(a21*a17);
  a39=(a07*a39);
  a27=(a27+a39);
  a27=(a27*a34);
  a05=(a05+a27);
  a27=(a11*a26);
  a40=(a09*a32);
  a27=(a27-a40);
  a40=(a12*a04);
  a27=(a27-a40);
  a40=(a08*a13);
  a27=(a27+a40);
  a40=6.6666666666666671e+01;
  a41=arg[1]? arg[1][3] : 0;
  a42=7.0000000000000001e-03;
  a42=(a42*a00);
  a43=(a03*a42);
  a44=1.4999999999999999e-02;
  a45=(a44*a03);
  a46=(a00*a45);
  a43=(a43-a46);
  a43=(a41-a43);
  a43=(a40*a43);
  a27=(a27*a43);
  a05=(a05+a27);
  a27=(a12*a32);
  a46=(a08*a26);
  a27=(a27+a46);
  a46=(a09*a04);
  a27=(a27-a46);
  a46=(a11*a13);
  a27=(a27-a46);
  a46=arg[1]? arg[1][4] : 0;
  a44=(a44*a02);
  a47=(a00*a44);
  a42=(a02*a42);
  a47=(a47-a42);
  a47=(a46-a47);
  a40=(a40*a47);
  a27=(a27*a40);
  a05=(a05+a27);
  a32=(a08*a32);
  a26=(a12*a26);
  a32=(a32-a26);
  a04=(a11*a04);
  a32=(a32-a04);
  a13=(a09*a13);
  a32=(a32+a13);
  a13=1.4285714285714286e+02;
  a04=arg[1]? arg[1][5] : 0;
  a45=(a02*a45);
  a44=(a03*a44);
  a45=(a45-a44);
  a45=(a04-a45);
  a13=(a13*a45);
  a32=(a32*a13);
  a05=(a05+a32);
  if (res[0]!=0) res[0][18]=a05;
  a36=(a20+a36);
  a36=(a36-a28);
  a36=(a36-a28);
  a31=(a06*a31);
  a05=(a03*a31);
  a36=(a36+a05);
  a16=(a06*a16);
  a05=(a00*a16);
  a36=(a36-a05);
  a30=(a06*a30);
  a05=(a02*a30);
  a36=(a36-a05);
  a36=(a36*a17);
  a05=(a37-a39);
  a32=(a00*a31);
  a05=(a05+a32);
  a32=(a03*a16);
  a05=(a05+a32);
  a35=(a06*a35);
  a32=(a02*a35);
  a05=(a05+a32);
  a05=(a05*a22);
  a36=(a36-a05);
  a05=(a14*a17);
  a05=(a07*a05);
  a19=(a19+a05);
  a32=(a02*a31);
  a19=(a19-a32);
  a32=(a03*a30);
  a19=(a19-a32);
  a32=(a00*a35);
  a19=(a19+a32);
  a19=(a19*a29);
  a36=(a36+a19);
  a19=(a10+a10);
  a19=(a33-a19);
  a32=(a14*a22);
  a07=(a07*a32);
  a19=(a19-a07);
  a32=(a02*a16);
  a19=(a19+a32);
  a32=(a00*a30);
  a19=(a19-a32);
  a32=(a03*a35);
  a19=(a19-a32);
  a19=(a19*a34);
  a36=(a36+a19);
  a19=(a11*a16);
  a32=(a09*a31);
  a19=(a19-a32);
  a32=(a12*a30);
  a19=(a19-a32);
  a32=(a08*a35);
  a19=(a19+a32);
  a19=(a19*a43);
  a36=(a36+a19);
  a19=(a12*a31);
  a32=(a08*a16);
  a19=(a19+a32);
  a32=(a09*a30);
  a19=(a19-a32);
  a32=(a11*a35);
  a19=(a19-a32);
  a19=(a19*a40);
  a36=(a36+a19);
  a31=(a08*a31);
  a16=(a12*a16);
  a31=(a31-a16);
  a30=(a11*a30);
  a31=(a31-a30);
  a35=(a09*a35);
  a31=(a31+a35);
  a31=(a31*a13);
  a36=(a36+a31);
  if (res[0]!=0) res[0][19]=a36;
  a37=(a37-a38);
  a37=(a37-a39);
  a37=(a37-a39);
  a23=(a06*a23);
  a39=(a03*a23);
  a37=(a37+a39);
  a18=(a06*a18);
  a39=(a00*a18);
  a37=(a37-a39);
  a24=(a06*a24);
  a39=(a02*a24);
  a37=(a37-a39);
  a37=(a37*a17);
  a28=(a28-a20);
  a20=(a00*a23);
  a28=(a28+a20);
  a20=(a03*a18);
  a28=(a28+a20);
  a06=(a06*a15);
  a15=(a02*a06);
  a28=(a28+a15);
  a28=(a28*a22);
  a37=(a37-a28);
  a10=(a10-a33);
  a10=(a10-a33);
  a10=(a10+a07);
  a07=(a02*a23);
  a10=(a10-a07);
  a07=(a03*a24);
  a10=(a10-a07);
  a07=(a00*a06);
  a10=(a10+a07);
  a10=(a10*a29);
  a37=(a37+a10);
  a25=(a25+a05);
  a02=(a02*a18);
  a25=(a25+a02);
  a00=(a00*a24);
  a25=(a25-a00);
  a03=(a03*a06);
  a25=(a25-a03);
  a25=(a25*a34);
  a37=(a37+a25);
  a25=(a11*a18);
  a34=(a09*a23);
  a25=(a25-a34);
  a34=(a12*a24);
  a25=(a25-a34);
  a34=(a08*a06);
  a25=(a25+a34);
  a25=(a25*a43);
  a37=(a37+a25);
  a25=(a12*a23);
  a43=(a08*a18);
  a25=(a25+a43);
  a43=(a09*a24);
  a25=(a25-a43);
  a43=(a11*a06);
  a25=(a25-a43);
  a25=(a25*a40);
  a37=(a37+a25);
  a08=(a08*a23);
  a12=(a12*a18);
  a08=(a08-a12);
  a11=(a11*a24);
  a08=(a08-a11);
  a09=(a09*a06);
  a08=(a08+a09);
  a08=(a08*a13);
  a37=(a37+a08);
  if (res[0]!=0) res[0][20]=a37;
  if (res[0]!=0) res[0][21]=a14;
  if (res[0]!=0) res[0][22]=a01;
  if (res[0]!=0) res[0][23]=a21;
  if (res[0]!=0) res[0][24]=a41;
  if (res[0]!=0) res[0][25]=a46;
  if (res[0]!=0) res[0][26]=a04;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_cost_y_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
