/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {27, 1, 1};

/* quadrotor_ode_cost_y_fun:(i0[13],i1[6],i2[0],i3[],i4[0])->(o0[27]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a70, a71;
  casadi_real a72, a73, a74, a75, a76, a77, a78;
  a00=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a00;
  a00=2.;
  a01=arg[0]? arg[0][6] : 0;
  a02=arg[0]? arg[0][7] : 0;
  a03=(a01*a02);
  a04=arg[0]? arg[0][8] : 0;
  a05=arg[0]? arg[0][9] : 0;
  a06=(a04*a05);
  a03=(a03+a06);
  a03=(a00*a03);
  a07=1.;
  a08=casadi_sq(a02);
  a09=casadi_sq(a04);
  a10=(a08+a09);
  a10=(a00*a10);
  a10=(a07-a10);
  a03=atan2(a03,a10);
  if (res[0]!=0) res[0][6]=a03;
  a03=(a01*a04);
  a11=(a05*a02);
  a03=(a03-a11);
  a03=(a00*a03);
  a03=asin(a03);
  if (res[0]!=0) res[0][7]=a03;
  a03=(a01*a05);
  a11=(a02*a04);
  a03=(a03+a11);
  a03=(a00*a03);
  a12=casadi_sq(a05);
  a09=(a09+a12);
  a09=(a00*a09);
  a09=(a07-a09);
  a03=atan2(a03,a09);
  if (res[0]!=0) res[0][8]=a03;
  a03=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][9]=a03;
  a13=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][10]=a13;
  a14=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][11]=a14;
  a15=arg[1]? arg[1][0] : 0;
  a16=(a09*a15);
  a17=(a05*a01);
  a18=(a11-a17);
  a18=(a00*a18);
  a19=arg[1]? arg[1][1] : 0;
  a20=(a18*a19);
  a16=(a16+a20);
  a20=(a02*a05);
  a21=(a04*a01);
  a22=(a20+a21);
  a22=(a00*a22);
  a23=arg[1]? arg[1][2] : 0;
  a24=(a22*a23);
  a16=(a16+a24);
  if (res[0]!=0) res[0][12]=a16;
  a11=(a11+a17);
  a11=(a00*a11);
  a17=(a11*a15);
  a08=(a08+a12);
  a08=(a00*a08);
  a07=(a07-a08);
  a08=(a07*a19);
  a17=(a17+a08);
  a08=(a02*a01);
  a12=(a06-a08);
  a12=(a00*a12);
  a24=(a12*a23);
  a17=(a17+a24);
  if (res[0]!=0) res[0][13]=a17;
  a20=(a20-a21);
  a20=(a00*a20);
  a21=(a20*a15);
  a06=(a06+a08);
  a06=(a00*a06);
  a08=(a06*a19);
  a21=(a21+a08);
  a08=(a10*a23);
  a21=(a21+a08);
  a08=9.8066499999999994e+00;
  a08=(a21-a08);
  if (res[0]!=0) res[0][14]=a08;
  a08=(a00*a04);
  a24=(a19*a08);
  a25=(a00*a05);
  a26=(a23*a25);
  a27=(a24+a26);
  a28=5.0000000000000000e-01;
  a29=(a03*a01);
  a30=(a14*a04);
  a29=(a29+a30);
  a30=(a13*a05);
  a29=(a29-a30);
  a29=(a28*a29);
  a30=(a27*a29);
  a31=(a23*a08);
  a32=(a19*a25);
  a33=(a31-a32);
  a34=(a03*a02);
  a35=(a13*a04);
  a34=(a34+a35);
  a35=(a14*a05);
  a34=(a34+a35);
  a34=(a28*a34);
  a35=(a33*a34);
  a30=(a30-a35);
  a35=(a00*a02);
  a36=(a19*a35);
  a37=(a04+a04);
  a38=(a00*a37);
  a39=(a15*a38);
  a39=(a36-a39);
  a40=(a00*a01);
  a41=(a23*a40);
  a39=(a39+a41);
  a42=(a13*a01);
  a43=(a14*a02);
  a42=(a42-a43);
  a43=(a03*a05);
  a42=(a42+a43);
  a42=(a28*a42);
  a43=(a39*a42);
  a30=(a30+a43);
  a43=(a23*a35);
  a44=(a05+a05);
  a45=(a00*a44);
  a46=(a15*a45);
  a47=(a19*a40);
  a46=(a46+a47);
  a46=(a43-a46);
  a48=(a14*a01);
  a49=(a13*a02);
  a48=(a48+a49);
  a49=(a03*a04);
  a48=(a48-a49);
  a48=(a28*a48);
  a49=(a46*a48);
  a30=(a30+a49);
  a30=(a30+a16);
  if (res[0]!=0) res[0][15]=a30;
  a30=(a15*a08);
  a16=(a02+a02);
  a49=(a00*a16);
  a50=(a19*a49);
  a50=(a30-a50);
  a50=(a50-a41);
  a41=(a50*a29);
  a51=(a15*a25);
  a43=(a51-a43);
  a52=(a43*a34);
  a41=(a41-a52);
  a52=(a15*a35);
  a26=(a52+a26);
  a53=(a26*a42);
  a41=(a41+a53);
  a53=(a15*a40);
  a54=(a19*a45);
  a54=(a53-a54);
  a54=(a54+a31);
  a31=(a54*a48);
  a41=(a41+a31);
  a41=(a41+a17);
  if (res[0]!=0) res[0][16]=a41;
  a51=(a51+a47);
  a47=(a23*a49);
  a51=(a51-a47);
  a47=(a51*a29);
  a36=(a36-a30);
  a30=(a36*a34);
  a47=(a47-a30);
  a32=(a32-a53);
  a53=(a23*a38);
  a32=(a32-a53);
  a53=(a32*a42);
  a47=(a47+a53);
  a52=(a52+a24);
  a24=(a52*a48);
  a47=(a47+a24);
  a47=(a47+a21);
  if (res[0]!=0) res[0][17]=a47;
  a47=(a00*a23);
  a21=(a05*a47);
  a24=(a00*a19);
  a53=(a04*a24);
  a30=(a21+a53);
  a46=(a28*a46);
  a41=(a13*a46);
  a30=(a30+a41);
  a41=(a23*a48);
  a41=(a00*a41);
  a30=(a30+a41);
  a39=(a28*a39);
  a17=(a14*a39);
  a30=(a30-a17);
  a17=(a19*a42);
  a17=(a00*a17);
  a30=(a30+a17);
  a33=(a28*a33);
  a31=(a03*a33);
  a30=(a30-a31);
  a30=(a30*a29);
  a31=(a04*a47);
  a55=(a05*a24);
  a56=(a31-a55);
  a57=(a14*a46);
  a56=(a56+a57);
  a57=(a19*a48);
  a57=(a00*a57);
  a56=(a56-a57);
  a58=(a13*a39);
  a56=(a56+a58);
  a58=(a23*a42);
  a58=(a00*a58);
  a56=(a56+a58);
  a27=(a28*a27);
  a59=(a03*a27);
  a56=(a56+a59);
  a56=(a56*a34);
  a30=(a30-a56);
  a56=(a01*a47);
  a59=(a02*a24);
  a60=(a56+a59);
  a61=(a00*a15);
  a62=(a37*a61);
  a60=(a60-a62);
  a62=(a03*a46);
  a60=(a60-a62);
  a62=(a15*a42);
  a62=(a00*a62);
  a60=(a60-a62);
  a60=(a60-a62);
  a63=(a13*a33);
  a60=(a60-a63);
  a63=(a23*a34);
  a63=(a00*a63);
  a60=(a60-a63);
  a64=(a14*a27);
  a60=(a60+a64);
  a64=(a19*a29);
  a64=(a00*a64);
  a60=(a60+a64);
  a60=(a60*a42);
  a30=(a30+a60);
  a60=(a02*a47);
  a65=(a01*a24);
  a66=(a60-a65);
  a67=(a44*a61);
  a66=(a66-a67);
  a67=(a15*a48);
  a67=(a00*a67);
  a66=(a66-a67);
  a66=(a66-a67);
  a68=(a03*a39);
  a66=(a66+a68);
  a68=(a14*a33);
  a66=(a66-a68);
  a68=(a19*a34);
  a68=(a00*a68);
  a66=(a66+a68);
  a69=(a13*a27);
  a66=(a66-a69);
  a69=(a23*a29);
  a69=(a00*a69);
  a66=(a66+a69);
  a66=(a66*a48);
  a30=(a30+a66);
  a66=(a05*a39);
  a70=(a04*a46);
  a66=(a66-a70);
  a70=(a02*a33);
  a66=(a66-a70);
  a70=(a01*a27);
  a66=(a66+a70);
  a70=6.6666666666666671e+01;
  a71=arg[1]? arg[1][3] : 0;
  a72=7.0000000000000001e-03;
  a72=(a72*a14);
  a73=(a13*a72);
  a74=1.4999999999999999e-02;
  a75=(a74*a13);
  a76=(a14*a75);
  a73=(a73-a76);
  a73=(a71+a73);
  a73=(a70*a73);
  a66=(a66*a73);
  a30=(a30+a66);
  a66=(a02*a46);
  a76=(a01*a39);
  a66=(a66+a76);
  a76=(a04*a33);
  a66=(a66-a76);
  a76=(a05*a27);
  a66=(a66-a76);
  a76=arg[1]? arg[1][4] : 0;
  a74=(a74*a03);
  a77=(a14*a74);
  a72=(a03*a72);
  a77=(a77-a72);
  a77=(a76+a77);
  a70=(a70*a77);
  a66=(a66*a70);
  a30=(a30+a66);
  a46=(a01*a46);
  a39=(a02*a39);
  a46=(a46-a39);
  a33=(a05*a33);
  a46=(a46-a33);
  a27=(a04*a27);
  a46=(a46+a27);
  a27=1.4285714285714286e+02;
  a33=arg[1]? arg[1][5] : 0;
  a75=(a03*a75);
  a74=(a13*a74);
  a75=(a75-a74);
  a75=(a33+a75);
  a27=(a27*a75);
  a46=(a46*a27);
  a30=(a30+a46);
  a38=(a42*a38);
  a45=(a48*a45);
  a46=(a38+a45);
  a09=(a09-a46);
  a09=(a09*a15);
  a46=(a29*a08);
  a75=(a34*a25);
  a74=(a46+a75);
  a39=(a42*a35);
  a74=(a74+a39);
  a66=(a48*a40);
  a74=(a74-a66);
  a74=(a74+a18);
  a74=(a74*a19);
  a09=(a09+a74);
  a74=(a29*a25);
  a18=(a34*a08);
  a77=(a74-a18);
  a72=(a42*a40);
  a77=(a77+a72);
  a78=(a48*a35);
  a77=(a77+a78);
  a77=(a77+a22);
  a77=(a77*a23);
  a09=(a09+a77);
  a30=(a30+a09);
  if (res[0]!=0) res[0][18]=a30;
  a30=(a04*a61);
  a09=(a16*a24);
  a56=(a56+a09);
  a56=(a30-a56);
  a56=(a56+a62);
  a56=(a56+a63);
  a56=(a56-a64);
  a56=(a56-a64);
  a54=(a28*a54);
  a63=(a13*a54);
  a56=(a56+a63);
  a26=(a28*a26);
  a63=(a14*a26);
  a56=(a56-a63);
  a43=(a28*a43);
  a63=(a03*a43);
  a56=(a56-a63);
  a56=(a56*a29);
  a63=(a05*a61);
  a60=(a63-a60);
  a60=(a60+a67);
  a60=(a60-a69);
  a09=(a14*a54);
  a60=(a60+a09);
  a09=(a13*a26);
  a60=(a60+a09);
  a50=(a28*a50);
  a09=(a03*a50);
  a60=(a60+a09);
  a60=(a60*a34);
  a56=(a56-a60);
  a60=(a02*a61);
  a21=(a21+a60);
  a21=(a21+a41);
  a41=(a15*a29);
  a41=(a00*a41);
  a21=(a21+a41);
  a09=(a03*a54);
  a21=(a21-a09);
  a09=(a13*a43);
  a21=(a21-a09);
  a09=(a14*a50);
  a21=(a21+a09);
  a21=(a21*a42);
  a56=(a56+a21);
  a44=(a44*a24);
  a31=(a31-a44);
  a61=(a01*a61);
  a31=(a31+a61);
  a31=(a31-a57);
  a31=(a31-a57);
  a31=(a31+a58);
  a44=(a15*a34);
  a00=(a00*a44);
  a31=(a31-a00);
  a44=(a03*a26);
  a31=(a31+a44);
  a44=(a14*a43);
  a31=(a31-a44);
  a44=(a13*a50);
  a31=(a31-a44);
  a31=(a31*a48);
  a56=(a56+a31);
  a31=(a05*a26);
  a44=(a04*a54);
  a31=(a31-a44);
  a44=(a02*a43);
  a31=(a31-a44);
  a44=(a01*a50);
  a31=(a31+a44);
  a31=(a31*a73);
  a56=(a56+a31);
  a31=(a02*a54);
  a44=(a01*a26);
  a31=(a31+a44);
  a44=(a04*a43);
  a31=(a31-a44);
  a44=(a05*a50);
  a31=(a31-a44);
  a31=(a31*a70);
  a56=(a56+a31);
  a54=(a01*a54);
  a26=(a02*a26);
  a54=(a54-a26);
  a43=(a05*a43);
  a54=(a54-a43);
  a50=(a04*a50);
  a54=(a54+a50);
  a54=(a54*a27);
  a56=(a56+a54);
  a46=(a46-a75);
  a46=(a46+a39);
  a46=(a46+a66);
  a46=(a46+a11);
  a46=(a46*a15);
  a49=(a29*a49);
  a45=(a49+a45);
  a07=(a07-a45);
  a07=(a07*a19);
  a46=(a46+a07);
  a35=(a34*a35);
  a40=(a29*a40);
  a07=(a35-a40);
  a25=(a42*a25);
  a07=(a07+a25);
  a08=(a48*a08);
  a07=(a07+a08);
  a07=(a07+a12);
  a07=(a07*a23);
  a46=(a46+a07);
  a56=(a56+a46);
  if (res[0]!=0) res[0][19]=a56;
  a16=(a16*a47);
  a65=(a65-a16);
  a65=(a65+a63);
  a65=(a65+a67);
  a65=(a65-a68);
  a65=(a65-a69);
  a65=(a65-a69);
  a52=(a28*a52);
  a69=(a13*a52);
  a65=(a65+a69);
  a32=(a28*a32);
  a69=(a14*a32);
  a65=(a65-a69);
  a36=(a28*a36);
  a69=(a03*a36);
  a65=(a65-a69);
  a65=(a65*a29);
  a59=(a59-a30);
  a59=(a59-a62);
  a59=(a59+a64);
  a64=(a14*a52);
  a59=(a59+a64);
  a64=(a13*a32);
  a59=(a59+a64);
  a28=(a28*a51);
  a51=(a03*a28);
  a59=(a59+a51);
  a59=(a59*a34);
  a65=(a65-a59);
  a37=(a37*a47);
  a55=(a55-a37);
  a55=(a55-a61);
  a55=(a55+a57);
  a55=(a55-a58);
  a55=(a55-a58);
  a55=(a55+a00);
  a00=(a03*a52);
  a55=(a55-a00);
  a00=(a13*a36);
  a55=(a55-a00);
  a00=(a14*a28);
  a55=(a55+a00);
  a55=(a55*a42);
  a65=(a65+a55);
  a53=(a53+a60);
  a53=(a53+a17);
  a53=(a53+a41);
  a03=(a03*a32);
  a53=(a53+a03);
  a14=(a14*a36);
  a53=(a53-a14);
  a13=(a13*a28);
  a53=(a53-a13);
  a53=(a53*a48);
  a65=(a65+a53);
  a53=(a05*a32);
  a48=(a04*a52);
  a53=(a53-a48);
  a48=(a02*a36);
  a53=(a53-a48);
  a48=(a01*a28);
  a53=(a53+a48);
  a53=(a53*a73);
  a65=(a65+a53);
  a53=(a02*a52);
  a73=(a01*a32);
  a53=(a53+a73);
  a73=(a04*a36);
  a53=(a53-a73);
  a73=(a05*a28);
  a53=(a53-a73);
  a53=(a53*a70);
  a65=(a65+a53);
  a01=(a01*a52);
  a02=(a02*a32);
  a01=(a01-a02);
  a05=(a05*a36);
  a01=(a01-a05);
  a04=(a04*a28);
  a01=(a01+a04);
  a01=(a01*a27);
  a65=(a65+a01);
  a74=(a74+a18);
  a74=(a74-a72);
  a74=(a74+a78);
  a74=(a74+a20);
  a74=(a74*a15);
  a40=(a40-a35);
  a40=(a40+a25);
  a40=(a40+a08);
  a40=(a40+a06);
  a40=(a40*a19);
  a74=(a74+a40);
  a49=(a49+a38);
  a10=(a10-a49);
  a10=(a10*a23);
  a74=(a74+a10);
  a65=(a65+a74);
  if (res[0]!=0) res[0][20]=a65;
  if (res[0]!=0) res[0][21]=a15;
  if (res[0]!=0) res[0][22]=a19;
  if (res[0]!=0) res[0][23]=a23;
  if (res[0]!=0) res[0][24]=a71;
  if (res[0]!=0) res[0][25]=a76;
  if (res[0]!=0) res[0][26]=a33;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_cost_y_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
