/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {9, 1, 1};
static const casadi_int casadi_s5[3] = {31, 1, 1};

/* quadrotor_ode_cost_y_fun:(i0[13],i1[6],i2[0],i3[],i4[9])->(o0[31]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54;
  a00=arg[0]? arg[0][0] : 0;
  a01=arg[4]? arg[4][0] : 0;
  a00=(a00-a01);
  a01=casadi_sq(a00);
  a02=arg[0]? arg[0][1] : 0;
  a03=arg[4]? arg[4][1] : 0;
  a02=(a02-a03);
  a03=casadi_sq(a02);
  a01=(a01+a03);
  a03=arg[0]? arg[0][2] : 0;
  a04=arg[4]? arg[4][2] : 0;
  a03=(a03-a04);
  a04=casadi_sq(a03);
  a01=(a01+a04);
  a01=sqrt(a01);
  if (res[0]!=0) res[0][0]=a01;
  a02=atan2(a02,a00);
  if (res[0]!=0) res[0][1]=a02;
  a03=(a03/a01);
  a03=asin(a03);
  if (res[0]!=0) res[0][2]=a03;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a03=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a03;
  a03=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a03;
  a03=0.;
  a01=arg[4]? arg[4][8] : 0;
  a02=cos(a01);
  a00=arg[4]? arg[4][7] : 0;
  a04=cos(a00);
  a05=(a02*a04);
  a06=2.;
  a07=arg[0]? arg[0][6] : 0;
  a08=arg[0]? arg[0][9] : 0;
  a09=(a07*a08);
  a10=arg[0]? arg[0][7] : 0;
  a11=arg[0]? arg[0][8] : 0;
  a12=(a10*a11);
  a09=(a09+a12);
  a09=(a06*a09);
  a13=1.;
  a14=casadi_sq(a11);
  a15=casadi_sq(a08);
  a16=(a14+a15);
  a16=(a06*a16);
  a16=(a13-a16);
  a09=atan2(a09,a16);
  a17=cos(a09);
  a18=(a07*a11);
  a19=(a08*a10);
  a18=(a18-a19);
  a18=(a06*a18);
  a18=asin(a18);
  a19=cos(a18);
  a20=(a17*a19);
  a21=arg[4]? arg[4][5] : 0;
  a22=cos(a21);
  a23=arg[4]? arg[4][4] : 0;
  a24=cos(a23);
  a25=(a22*a24);
  a26=(a20*a25);
  a09=sin(a09);
  a27=(a09*a19);
  a21=sin(a21);
  a28=(a21*a24);
  a29=(a27*a28);
  a26=(a26+a29);
  a29=sin(a18);
  a23=sin(a23);
  a30=(a29*a23);
  a26=(a26+a30);
  a30=(a05*a26);
  a01=sin(a01);
  a31=(a01*a04);
  a32=(a17*a29);
  a33=(a07*a10);
  a34=(a11*a08);
  a33=(a33+a34);
  a33=(a06*a33);
  a35=casadi_sq(a10);
  a14=(a35+a14);
  a14=(a06*a14);
  a14=(a13-a14);
  a33=atan2(a33,a14);
  a36=sin(a33);
  a37=(a32*a36);
  a33=cos(a33);
  a38=(a09*a33);
  a37=(a37-a38);
  a38=(a37*a25);
  a39=(a09*a29);
  a40=(a39*a36);
  a41=(a17*a33);
  a40=(a40+a41);
  a41=(a40*a28);
  a38=(a38+a41);
  a41=(a19*a36);
  a42=(a41*a23);
  a38=(a38-a42);
  a42=(a31*a38);
  a30=(a30+a42);
  a00=sin(a00);
  a32=(a32*a33);
  a09=(a09*a36);
  a32=(a32+a09);
  a25=(a32*a25);
  a39=(a39*a33);
  a17=(a17*a36);
  a39=(a39-a17);
  a28=(a39*a28);
  a25=(a25+a28);
  a19=(a19*a33);
  a28=(a19*a23);
  a25=(a25-a28);
  a28=(a00*a25);
  a30=(a30-a28);
  a28=(a02*a00);
  a17=arg[4]? arg[4][6] : 0;
  a09=sin(a17);
  a42=(a28*a09);
  a17=cos(a17);
  a43=(a01*a17);
  a42=(a42-a43);
  a43=(a22*a23);
  a44=arg[4]? arg[4][3] : 0;
  a45=sin(a44);
  a46=(a43*a45);
  a44=cos(a44);
  a47=(a21*a44);
  a46=(a46-a47);
  a47=(a20*a46);
  a23=(a21*a23);
  a48=(a23*a45);
  a49=(a22*a44);
  a48=(a48+a49);
  a49=(a27*a48);
  a47=(a47+a49);
  a49=(a24*a45);
  a50=(a29*a49);
  a47=(a47-a50);
  a50=(a42*a47);
  a51=(a01*a00);
  a52=(a51*a09);
  a53=(a02*a17);
  a52=(a52+a53);
  a53=(a37*a46);
  a54=(a40*a48);
  a53=(a53+a54);
  a54=(a41*a49);
  a53=(a53+a54);
  a54=(a52*a53);
  a50=(a50+a54);
  a54=(a04*a09);
  a46=(a32*a46);
  a48=(a39*a48);
  a46=(a46+a48);
  a49=(a19*a49);
  a46=(a46+a49);
  a49=(a54*a46);
  a50=(a50+a49);
  a49=(a30+a50);
  a28=(a28*a17);
  a01=(a01*a09);
  a28=(a28+a01);
  a43=(a43*a44);
  a21=(a21*a45);
  a43=(a43+a21);
  a20=(a20*a43);
  a23=(a23*a44);
  a22=(a22*a45);
  a23=(a23-a22);
  a27=(a27*a23);
  a20=(a20+a27);
  a24=(a24*a44);
  a29=(a29*a24);
  a20=(a20-a29);
  a29=(a28*a20);
  a51=(a51*a17);
  a02=(a02*a09);
  a51=(a51-a02);
  a37=(a37*a43);
  a40=(a40*a23);
  a37=(a37+a40);
  a41=(a41*a24);
  a37=(a37+a41);
  a41=(a51*a37);
  a29=(a29+a41);
  a04=(a04*a17);
  a32=(a32*a43);
  a39=(a39*a23);
  a32=(a32+a39);
  a19=(a19*a24);
  a32=(a32+a19);
  a19=(a04*a32);
  a29=(a29+a19);
  a49=(a49+a29);
  a03=(a03<a49);
  a19=2.5000000000000000e-01;
  a49=(a49+a13);
  a49=sqrt(a49);
  a49=(a06*a49);
  a24=(a19*a49);
  a24=(a03?a24:0);
  a39=(!a03);
  a23=(a50<a30);
  a43=(a29<a30);
  a23=(a23&&a43);
  a43=(a28*a47);
  a17=(a51*a53);
  a43=(a43+a17);
  a17=(a04*a46);
  a43=(a43+a17);
  a17=(a42*a20);
  a41=(a52*a37);
  a17=(a17+a41);
  a41=(a54*a32);
  a17=(a17+a41);
  a41=(a43-a17);
  a40=(a13+a30);
  a40=(a40-a50);
  a40=(a40-a29);
  a40=sqrt(a40);
  a40=(a06*a40);
  a02=(a41/a40);
  a02=(a23?a02:0);
  a09=(!a23);
  a44=(a29<a50);
  a20=(a05*a20);
  a37=(a31*a37);
  a20=(a20+a37);
  a32=(a00*a32);
  a20=(a20-a32);
  a28=(a28*a26);
  a51=(a51*a38);
  a28=(a28+a51);
  a04=(a04*a25);
  a28=(a28+a04);
  a04=(a20-a28);
  a51=(a13+a50);
  a51=(a51-a30);
  a51=(a51-a29);
  a51=sqrt(a51);
  a51=(a06*a51);
  a32=(a04/a51);
  a32=(a44?a32:0);
  a37=(!a44);
  a42=(a42*a26);
  a52=(a52*a38);
  a42=(a42+a52);
  a54=(a54*a25);
  a42=(a42+a54);
  a05=(a05*a47);
  a31=(a31*a53);
  a05=(a05+a31);
  a00=(a00*a46);
  a05=(a05-a00);
  a00=(a42-a05);
  a29=(a13+a29);
  a29=(a29-a30);
  a29=(a29-a50);
  a29=sqrt(a29);
  a29=(a06*a29);
  a50=(a00/a29);
  a50=(a37?a50:0);
  a32=(a32+a50);
  a32=(a09?a32:0);
  a02=(a02+a32);
  a02=(a39?a02:0);
  a24=(a24+a02);
  a02=casadi_sq(a24);
  a41=(a41/a49);
  a41=(a03?a41:0);
  a32=(a19*a40);
  a32=(a23?a32:0);
  a05=(a05+a42);
  a42=(a05/a51);
  a42=(a44?a42:0);
  a20=(a20+a28);
  a28=(a20/a29);
  a28=(a37?a28:0);
  a42=(a42+a28);
  a42=(a09?a42:0);
  a32=(a32+a42);
  a32=(a39?a32:0);
  a41=(a41+a32);
  a32=casadi_sq(a41);
  a02=(a02+a32);
  a04=(a04/a49);
  a04=(a03?a04:0);
  a05=(a05/a40);
  a05=(a23?a05:0);
  a32=(a19*a51);
  a32=(a44?a32:0);
  a17=(a17+a43);
  a43=(a17/a29);
  a43=(a37?a43:0);
  a32=(a32+a43);
  a32=(a09?a32:0);
  a05=(a05+a32);
  a05=(a39?a05:0);
  a04=(a04+a05);
  a05=casadi_sq(a04);
  a02=(a02+a05);
  a00=(a00/a49);
  a03=(a03?a00:0);
  a20=(a20/a40);
  a23=(a23?a20:0);
  a17=(a17/a51);
  a44=(a44?a17:0);
  a19=(a19*a29);
  a37=(a37?a19:0);
  a44=(a44+a37);
  a09=(a09?a44:0);
  a23=(a23+a09);
  a39=(a39?a23:0);
  a03=(a03+a39);
  a39=casadi_sq(a03);
  a02=(a02+a39);
  a02=sqrt(a02);
  a24=(a24/a02);
  a39=casadi_sign(a24);
  a24=(a24*a39);
  a24=(-a24);
  if (res[0]!=0) res[0][6]=a24;
  a41=(a41/a02);
  a41=(a41*a39);
  a41=(-a41);
  if (res[0]!=0) res[0][7]=a41;
  a04=(a04/a02);
  a04=(a04*a39);
  a04=(-a04);
  if (res[0]!=0) res[0][8]=a04;
  a03=(a03/a02);
  a03=(a03*a39);
  a03=(-a03);
  if (res[0]!=0) res[0][9]=a03;
  a03=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][10]=a03;
  a39=arg[0]? arg[0][11] : 0;
  a02=(a33*a39);
  a18=tan(a18);
  a04=(a36*a18);
  a41=arg[0]? arg[0][12] : 0;
  a04=(a04*a41);
  a02=(a02+a04);
  if (res[0]!=0) res[0][11]=a02;
  a33=(a33*a18);
  a33=(a33*a41);
  a36=(a36*a39);
  a33=(a33-a36);
  if (res[0]!=0) res[0][12]=a33;
  a33=arg[1]? arg[1][0] : 0;
  a16=(a16*a33);
  a36=(a08*a07);
  a18=(a12-a36);
  a18=(a06*a18);
  a02=arg[1]? arg[1][1] : 0;
  a18=(a18*a02);
  a16=(a16+a18);
  a18=(a10*a08);
  a04=(a11*a07);
  a24=(a18+a04);
  a24=(a06*a24);
  a23=arg[1]? arg[1][2] : 0;
  a24=(a24*a23);
  a16=(a16+a24);
  if (res[0]!=0) res[0][13]=a16;
  a12=(a12+a36);
  a12=(a06*a12);
  a12=(a12*a33);
  a35=(a35+a15);
  a35=(a06*a35);
  a13=(a13-a35);
  a13=(a13*a02);
  a12=(a12+a13);
  a13=(a10*a07);
  a35=(a34-a13);
  a35=(a06*a35);
  a35=(a35*a23);
  a12=(a12+a35);
  if (res[0]!=0) res[0][14]=a12;
  a18=(a18-a04);
  a18=(a06*a18);
  a18=(a18*a33);
  a34=(a34+a13);
  a34=(a06*a34);
  a34=(a34*a02);
  a18=(a18+a34);
  a14=(a14*a23);
  a18=(a18+a14);
  a14=9.8066499999999994e+00;
  a18=(a18-a14);
  if (res[0]!=0) res[0][15]=a18;
  a18=6.6666666666666671e+01;
  a14=arg[1]? arg[1][3] : 0;
  a34=7.0000000000000001e-03;
  a34=(a34*a41);
  a13=(a39*a34);
  a04=1.4999999999999999e-02;
  a12=(a04*a39);
  a35=(a41*a12);
  a13=(a13-a35);
  a13=(a14-a13);
  a13=(a18*a13);
  if (res[0]!=0) res[0][16]=a13;
  a35=arg[1]? arg[1][4] : 0;
  a04=(a04*a03);
  a15=(a41*a04);
  a34=(a03*a34);
  a15=(a15-a34);
  a15=(a35-a15);
  a18=(a18*a15);
  if (res[0]!=0) res[0][17]=a18;
  a15=1.4285714285714286e+02;
  a34=arg[1]? arg[1][5] : 0;
  a12=(a03*a12);
  a04=(a39*a04);
  a12=(a12-a04);
  a12=(a34-a12);
  a15=(a15*a12);
  if (res[0]!=0) res[0][18]=a15;
  a12=(a06*a11);
  a04=(a02*a12);
  a36=(a06*a08);
  a16=(a23*a36);
  a24=(a04+a16);
  a09=5.0000000000000000e-01;
  a44=(a03*a07);
  a37=(a41*a11);
  a44=(a44+a37);
  a37=(a39*a08);
  a44=(a44-a37);
  a44=(a09*a44);
  a37=(a24*a44);
  a19=(a23*a12);
  a29=(a02*a36);
  a17=(a19-a29);
  a51=(a03*a10);
  a20=(a39*a11);
  a51=(a51+a20);
  a20=(a41*a08);
  a51=(a51+a20);
  a51=(a09*a51);
  a20=(a17*a51);
  a37=(a37-a20);
  a20=(a06*a10);
  a40=(a02*a20);
  a00=(a11+a11);
  a00=(a06*a00);
  a49=(a33*a00);
  a49=(a40-a49);
  a05=(a06*a07);
  a32=(a23*a05);
  a49=(a49+a32);
  a43=(a39*a07);
  a42=(a41*a10);
  a43=(a43-a42);
  a42=(a03*a08);
  a43=(a43+a42);
  a43=(a09*a43);
  a42=(a49*a43);
  a37=(a37+a42);
  a42=(a23*a20);
  a28=(a08+a08);
  a28=(a06*a28);
  a50=(a33*a28);
  a30=(a02*a05);
  a50=(a50+a30);
  a50=(a42-a50);
  a46=(a41*a07);
  a31=(a39*a10);
  a46=(a46+a31);
  a31=(a03*a11);
  a46=(a46-a31);
  a46=(a09*a46);
  a31=(a50*a46);
  a37=(a37+a31);
  if (res[0]!=0) res[0][19]=a37;
  a12=(a33*a12);
  a37=(a10+a10);
  a37=(a06*a37);
  a31=(a02*a37);
  a31=(a12-a31);
  a31=(a31-a32);
  a32=(a31*a44);
  a36=(a33*a36);
  a42=(a36-a42);
  a53=(a42*a51);
  a32=(a32-a53);
  a20=(a33*a20);
  a16=(a20+a16);
  a53=(a16*a43);
  a32=(a32+a53);
  a05=(a33*a05);
  a28=(a02*a28);
  a28=(a05-a28);
  a28=(a28+a19);
  a19=(a28*a46);
  a32=(a32+a19);
  if (res[0]!=0) res[0][20]=a32;
  a36=(a36+a30);
  a37=(a23*a37);
  a36=(a36-a37);
  a37=(a36*a44);
  a40=(a40-a12);
  a12=(a40*a51);
  a37=(a37-a12);
  a29=(a29-a05);
  a00=(a23*a00);
  a29=(a29-a00);
  a00=(a29*a43);
  a37=(a37+a00);
  a20=(a20+a04);
  a04=(a20*a46);
  a37=(a37+a04);
  if (res[0]!=0) res[0][21]=a37;
  a50=(a09*a50);
  a37=(a39*a50);
  a04=(a23*a46);
  a04=(a06*a04);
  a37=(a37+a04);
  a49=(a09*a49);
  a00=(a41*a49);
  a37=(a37-a00);
  a00=(a02*a43);
  a00=(a06*a00);
  a37=(a37+a00);
  a17=(a09*a17);
  a05=(a03*a17);
  a37=(a37-a05);
  a37=(a37*a44);
  a05=(a41*a50);
  a12=(a02*a46);
  a12=(a06*a12);
  a05=(a05-a12);
  a30=(a39*a49);
  a05=(a05+a30);
  a30=(a23*a43);
  a30=(a06*a30);
  a05=(a05+a30);
  a24=(a09*a24);
  a32=(a03*a24);
  a05=(a05+a32);
  a05=(a05*a51);
  a37=(a37-a05);
  a05=(a41*a24);
  a32=(a03*a50);
  a19=(a33*a43);
  a19=(a06*a19);
  a32=(a32+a19);
  a32=(a32+a19);
  a53=(a39*a17);
  a32=(a32+a53);
  a53=(a23*a51);
  a53=(a06*a53);
  a32=(a32+a53);
  a05=(a05-a32);
  a32=(a02*a44);
  a32=(a06*a32);
  a05=(a05+a32);
  a05=(a05*a43);
  a37=(a37+a05);
  a05=(a03*a49);
  a47=(a33*a46);
  a47=(a06*a47);
  a54=(a47+a47);
  a05=(a05-a54);
  a54=(a41*a17);
  a05=(a05-a54);
  a54=(a02*a51);
  a54=(a06*a54);
  a05=(a05+a54);
  a25=(a39*a24);
  a05=(a05-a25);
  a25=(a23*a44);
  a25=(a06*a25);
  a05=(a05+a25);
  a05=(a05*a46);
  a37=(a37+a05);
  a05=(a08*a49);
  a52=(a11*a50);
  a05=(a05-a52);
  a52=(a10*a17);
  a05=(a05-a52);
  a52=(a07*a24);
  a05=(a05+a52);
  a05=(a05*a13);
  a37=(a37+a05);
  a05=(a10*a50);
  a52=(a07*a49);
  a05=(a05+a52);
  a52=(a11*a17);
  a05=(a05-a52);
  a52=(a08*a24);
  a05=(a05-a52);
  a05=(a05*a18);
  a37=(a37+a05);
  a50=(a07*a50);
  a49=(a10*a49);
  a50=(a50-a49);
  a17=(a08*a17);
  a50=(a50-a17);
  a24=(a11*a24);
  a50=(a50+a24);
  a50=(a50*a15);
  a37=(a37+a50);
  if (res[0]!=0) res[0][22]=a37;
  a53=(a19+a53);
  a53=(a53-a32);
  a53=(a53-a32);
  a28=(a09*a28);
  a37=(a39*a28);
  a53=(a53+a37);
  a16=(a09*a16);
  a37=(a41*a16);
  a53=(a53-a37);
  a42=(a09*a42);
  a37=(a03*a42);
  a53=(a53-a37);
  a53=(a53*a44);
  a37=(a47-a25);
  a50=(a41*a28);
  a37=(a37+a50);
  a50=(a39*a16);
  a37=(a37+a50);
  a31=(a09*a31);
  a50=(a03*a31);
  a37=(a37+a50);
  a37=(a37*a51);
  a53=(a53-a37);
  a37=(a33*a44);
  a37=(a06*a37);
  a04=(a04+a37);
  a50=(a03*a28);
  a04=(a04-a50);
  a50=(a39*a42);
  a04=(a04-a50);
  a50=(a41*a31);
  a04=(a04+a50);
  a04=(a04*a43);
  a53=(a53+a04);
  a04=(a12+a12);
  a04=(a30-a04);
  a50=(a33*a51);
  a06=(a06*a50);
  a04=(a04-a06);
  a50=(a03*a16);
  a04=(a04+a50);
  a50=(a41*a42);
  a04=(a04-a50);
  a50=(a39*a31);
  a04=(a04-a50);
  a04=(a04*a46);
  a53=(a53+a04);
  a04=(a08*a16);
  a50=(a11*a28);
  a04=(a04-a50);
  a50=(a10*a42);
  a04=(a04-a50);
  a50=(a07*a31);
  a04=(a04+a50);
  a04=(a04*a13);
  a53=(a53+a04);
  a04=(a10*a28);
  a50=(a07*a16);
  a04=(a04+a50);
  a50=(a11*a42);
  a04=(a04-a50);
  a50=(a08*a31);
  a04=(a04-a50);
  a04=(a04*a18);
  a53=(a53+a04);
  a28=(a07*a28);
  a16=(a10*a16);
  a28=(a28-a16);
  a42=(a08*a42);
  a28=(a28-a42);
  a31=(a11*a31);
  a28=(a28+a31);
  a28=(a28*a15);
  a53=(a53+a28);
  if (res[0]!=0) res[0][23]=a53;
  a47=(a47-a54);
  a47=(a47-a25);
  a47=(a47-a25);
  a20=(a09*a20);
  a25=(a39*a20);
  a47=(a47+a25);
  a29=(a09*a29);
  a25=(a41*a29);
  a47=(a47-a25);
  a40=(a09*a40);
  a25=(a03*a40);
  a47=(a47-a25);
  a47=(a47*a44);
  a32=(a32-a19);
  a19=(a41*a20);
  a32=(a32+a19);
  a19=(a39*a29);
  a32=(a32+a19);
  a09=(a09*a36);
  a36=(a03*a09);
  a32=(a32+a36);
  a32=(a32*a51);
  a47=(a47-a32);
  a12=(a12-a30);
  a12=(a12-a30);
  a12=(a12+a06);
  a06=(a03*a20);
  a12=(a12-a06);
  a06=(a39*a40);
  a12=(a12-a06);
  a06=(a41*a09);
  a12=(a12+a06);
  a12=(a12*a43);
  a47=(a47+a12);
  a00=(a00+a37);
  a03=(a03*a29);
  a00=(a00+a03);
  a41=(a41*a40);
  a00=(a00-a41);
  a39=(a39*a09);
  a00=(a00-a39);
  a00=(a00*a46);
  a47=(a47+a00);
  a00=(a08*a29);
  a46=(a11*a20);
  a00=(a00-a46);
  a46=(a10*a40);
  a00=(a00-a46);
  a46=(a07*a09);
  a00=(a00+a46);
  a00=(a00*a13);
  a47=(a47+a00);
  a00=(a10*a20);
  a13=(a07*a29);
  a00=(a00+a13);
  a13=(a11*a40);
  a00=(a00-a13);
  a13=(a08*a09);
  a00=(a00-a13);
  a00=(a00*a18);
  a47=(a47+a00);
  a07=(a07*a20);
  a10=(a10*a29);
  a07=(a07-a10);
  a08=(a08*a40);
  a07=(a07-a08);
  a11=(a11*a09);
  a07=(a07+a11);
  a07=(a07*a15);
  a47=(a47+a07);
  if (res[0]!=0) res[0][24]=a47;
  if (res[0]!=0) res[0][25]=a33;
  if (res[0]!=0) res[0][26]=a02;
  if (res[0]!=0) res[0][27]=a23;
  if (res[0]!=0) res[0][28]=a14;
  if (res[0]!=0) res[0][29]=a35;
  if (res[0]!=0) res[0][30]=a34;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_cost_y_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
