/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {9, 1, 1};
static const casadi_int casadi_s5[3] = {30, 1, 1};

/* quadrotor_ode_cost_y_fun:(i0[13],i1[6],i2[0],i3[],i4[9])->(o0[30]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46;
  a00=arg[0]? arg[0][0] : 0;
  a01=arg[4]? arg[4][0] : 0;
  a00=(a00-a01);
  a01=casadi_sq(a00);
  a02=arg[0]? arg[0][1] : 0;
  a03=arg[4]? arg[4][1] : 0;
  a02=(a02-a03);
  a03=casadi_sq(a02);
  a01=(a01+a03);
  a03=arg[0]? arg[0][2] : 0;
  a04=arg[4]? arg[4][2] : 0;
  a03=(a03-a04);
  a04=casadi_sq(a03);
  a01=(a01+a04);
  a01=sqrt(a01);
  if (res[0]!=0) res[0][0]=a01;
  a02=atan2(a02,a00);
  if (res[0]!=0) res[0][1]=a02;
  a03=(a03/a01);
  a03=asin(a03);
  if (res[0]!=0) res[0][2]=a03;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a03=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a03;
  a03=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a03;
  a03=arg[4]? arg[4][5] : 0;
  a01=sin(a03);
  a02=arg[4]? arg[4][4] : 0;
  a00=cos(a02);
  a04=(a01*a00);
  a05=casadi_fabs(a04);
  a06=9.9999999999999995e-07;
  a05=(a05<a06);
  a05=(!a05);
  a07=2.;
  a08=arg[0]? arg[0][6] : 0;
  a09=casadi_sq(a08);
  a10=arg[0]? arg[0][7] : 0;
  a11=casadi_sq(a10);
  a09=(a09+a11);
  a12=arg[0]? arg[0][8] : 0;
  a13=casadi_sq(a12);
  a09=(a09+a13);
  a14=arg[0]? arg[0][9] : 0;
  a15=casadi_sq(a14);
  a09=(a09+a15);
  a09=sqrt(a09);
  a16=(a08/a09);
  a17=(a12/a09);
  a18=(a16*a17);
  a19=(a14/a09);
  a09=(a10/a09);
  a20=(a19*a09);
  a18=(a18-a20);
  a18=(a07*a18);
  a18=asin(a18);
  a20=sin(a18);
  a21=(-a20);
  a21=casadi_fabs(a21);
  a21=(a21<a06);
  a21=(!a21);
  a04=(a20*a04);
  a04=(-a04);
  a04=(a21?a04:0);
  a05=(a05?a04:0);
  a02=sin(a02);
  a04=(a01*a02);
  a22=arg[4]? arg[4][3] : 0;
  a23=sin(a22);
  a24=(a04*a23);
  a03=cos(a03);
  a22=cos(a22);
  a25=(a03*a22);
  a24=(a24+a25);
  a25=casadi_fabs(a24);
  a25=(a25<a06);
  a25=(!a25);
  a26=cos(a18);
  a27=(a16*a09);
  a28=(a17*a19);
  a27=(a27+a28);
  a27=(a07*a27);
  a28=1.;
  a29=casadi_sq(a09);
  a30=casadi_sq(a17);
  a29=(a29+a30);
  a29=(a07*a29);
  a29=(a28-a29);
  a27=atan2(a27,a29);
  a29=sin(a27);
  a31=(a26*a29);
  a32=casadi_fabs(a31);
  a32=(a32<a06);
  a32=(!a32);
  a24=(a31*a24);
  a24=(a32?a24:0);
  a25=(a25?a24:0);
  a05=(a05+a25);
  a04=(a04*a22);
  a25=(a03*a23);
  a04=(a04-a25);
  a25=casadi_fabs(a04);
  a25=(a25<a06);
  a25=(!a25);
  a27=cos(a27);
  a24=(a26*a27);
  a33=casadi_fabs(a24);
  a33=(a33<a06);
  a33=(!a33);
  a04=(a24*a04);
  a04=(a33?a04:0);
  a25=(a25?a04:0);
  a05=(a05+a25);
  a25=(-a02);
  a25=casadi_fabs(a25);
  a25=(a25<a06);
  a25=(!a25);
  a04=(a20*a02);
  a04=(a21?a04:0);
  a25=(a25?a04:0);
  a04=(a00*a23);
  a34=casadi_fabs(a04);
  a34=(a34<a06);
  a34=(!a34);
  a04=(a31*a04);
  a04=(a32?a04:0);
  a34=(a34?a04:0);
  a25=(a25+a34);
  a34=(a00*a22);
  a04=casadi_fabs(a34);
  a04=(a04<a06);
  a04=(!a04);
  a34=(a24*a34);
  a34=(a33?a34:0);
  a04=(a04?a34:0);
  a25=(a25+a04);
  a05=atan2(a05,a25);
  a25=casadi_fabs(a05);
  a25=(a25<a06);
  a25=(!a25);
  a25=(a25?a05:0);
  a05=arg[4]? arg[4][6] : 0;
  a25=(a25-a05);
  a05=-3.1415926535897931e+00;
  a04=(a25==a05);
  a34=(a04?a05:0);
  a04=(!a04);
  a35=6.2831853071795862e+00;
  a36=3.1415926535897931e+00;
  a37=(a25+a36);
  a37=(a37/a35);
  a37=floor(a37);
  a37=(a35*a37);
  a25=(a25-a37);
  a04=(a04?a25:0);
  a34=(a34+a04);
  a04=casadi_fabs(a34);
  a25=(a04<=a36);
  a37=(a25?a34:0);
  a25=(!a25);
  a38=0.;
  a34=(a38<=a34);
  a04=(a35-a04);
  a39=(-a04);
  a39=(a34?a39:0);
  a34=(!a34);
  a34=(a34?a04:0);
  a39=(a39+a34);
  a25=(a25?a39:0);
  a37=(a37+a25);
  if (res[0]!=0) res[0][6]=a37;
  a00=(a03*a00);
  a37=casadi_fabs(a00);
  a37=(a37<a06);
  a37=(!a37);
  a25=(a20*a00);
  a25=(-a25);
  a21=(a21?a25:0);
  a21=(a37?a21:0);
  a03=(a03*a02);
  a02=(a03*a23);
  a25=(a01*a22);
  a02=(a02-a25);
  a25=casadi_fabs(a02);
  a25=(a25<a06);
  a25=(!a25);
  a31=(a31*a02);
  a32=(a32?a31:0);
  a32=(a25?a32:0);
  a21=(a21+a32);
  a03=(a03*a22);
  a01=(a01*a23);
  a03=(a03+a01);
  a01=casadi_fabs(a03);
  a01=(a01<a06);
  a01=(!a01);
  a24=(a24*a03);
  a33=(a33?a24:0);
  a33=(a01?a33:0);
  a21=(a21+a33);
  a21=asin(a21);
  a21=(-a21);
  a33=casadi_fabs(a21);
  a33=(a33<a06);
  a33=(!a33);
  a33=(a33?a21:0);
  a21=arg[4]? arg[4][7] : 0;
  a33=(a33-a21);
  a21=(a33==a05);
  a24=(a21?a05:0);
  a21=(!a21);
  a23=(a33+a36);
  a23=(a23/a35);
  a23=floor(a23);
  a23=(a35*a23);
  a33=(a33-a23);
  a21=(a21?a33:0);
  a24=(a24+a21);
  a21=casadi_fabs(a24);
  a33=(a21<=a36);
  a23=(a33?a24:0);
  a33=(!a33);
  a24=(a38<=a24);
  a21=(a35-a21);
  a22=(-a21);
  a22=(a24?a22:0);
  a24=(!a24);
  a24=(a24?a21:0);
  a22=(a22+a24);
  a33=(a33?a22:0);
  a23=(a23+a33);
  if (res[0]!=0) res[0][7]=a23;
  a16=(a16*a19);
  a09=(a09*a17);
  a16=(a16+a09);
  a16=(a07*a16);
  a19=casadi_sq(a19);
  a30=(a30+a19);
  a30=(a07*a30);
  a30=(a28-a30);
  a16=atan2(a16,a30);
  a30=sin(a16);
  a19=(a30*a26);
  a09=casadi_fabs(a19);
  a09=(a09<a06);
  a09=(!a09);
  a19=(a19*a00);
  a09=(a09?a19:0);
  a09=(a37?a09:0);
  a19=(a30*a20);
  a17=(a19*a29);
  a16=cos(a16);
  a23=(a16*a27);
  a17=(a17+a23);
  a23=casadi_fabs(a17);
  a23=(a23<a06);
  a23=(!a23);
  a17=(a17*a02);
  a23=(a23?a17:0);
  a23=(a25?a23:0);
  a09=(a09+a23);
  a19=(a19*a27);
  a23=(a16*a29);
  a19=(a19-a23);
  a23=casadi_fabs(a19);
  a23=(a23<a06);
  a23=(!a23);
  a19=(a19*a03);
  a23=(a23?a19:0);
  a23=(a01?a23:0);
  a09=(a09+a23);
  a26=(a16*a26);
  a23=casadi_fabs(a26);
  a23=(a23<a06);
  a23=(!a23);
  a26=(a26*a00);
  a23=(a23?a26:0);
  a37=(a37?a23:0);
  a16=(a16*a20);
  a20=(a16*a29);
  a23=(a30*a27);
  a20=(a20-a23);
  a23=casadi_fabs(a20);
  a23=(a23<a06);
  a23=(!a23);
  a20=(a20*a02);
  a23=(a23?a20:0);
  a25=(a25?a23:0);
  a37=(a37+a25);
  a16=(a16*a27);
  a30=(a30*a29);
  a16=(a16+a30);
  a30=casadi_fabs(a16);
  a30=(a30<a06);
  a30=(!a30);
  a16=(a16*a03);
  a30=(a30?a16:0);
  a01=(a01?a30:0);
  a37=(a37+a01);
  a09=atan2(a09,a37);
  a37=casadi_fabs(a09);
  a37=(a37<a06);
  a37=(!a37);
  a37=(a37?a09:0);
  a09=arg[4]? arg[4][8] : 0;
  a37=(a37-a09);
  a09=(a37==a05);
  a05=(a09?a05:0);
  a09=(!a09);
  a06=(a37+a36);
  a06=(a06/a35);
  a06=floor(a06);
  a06=(a35*a06);
  a37=(a37-a06);
  a09=(a09?a37:0);
  a05=(a05+a09);
  a09=casadi_fabs(a05);
  a36=(a09<=a36);
  a37=(a36?a05:0);
  a36=(!a36);
  a38=(a38<=a05);
  a35=(a35-a09);
  a09=(-a35);
  a09=(a38?a09:0);
  a38=(!a38);
  a38=(a38?a35:0);
  a09=(a09+a38);
  a36=(a36?a09:0);
  a37=(a37+a36);
  if (res[0]!=0) res[0][8]=a37;
  a37=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][9]=a37;
  a36=arg[0]? arg[0][11] : 0;
  a09=(a27*a36);
  a18=tan(a18);
  a38=(a29*a18);
  a35=arg[0]? arg[0][12] : 0;
  a38=(a38*a35);
  a09=(a09+a38);
  if (res[0]!=0) res[0][10]=a09;
  a27=(a27*a18);
  a27=(a27*a35);
  a29=(a29*a36);
  a27=(a27-a29);
  if (res[0]!=0) res[0][11]=a27;
  a27=(a13+a15);
  a27=(a07*a27);
  a27=(a28-a27);
  a29=arg[1]? arg[1][0] : 0;
  a27=(a27*a29);
  a18=(a10*a12);
  a09=(a14*a08);
  a38=(a18-a09);
  a38=(a07*a38);
  a05=arg[1]? arg[1][1] : 0;
  a38=(a38*a05);
  a27=(a27+a38);
  a38=(a10*a14);
  a06=(a12*a08);
  a01=(a38+a06);
  a01=(a07*a01);
  a30=arg[1]? arg[1][2] : 0;
  a01=(a01*a30);
  a27=(a27+a01);
  if (res[0]!=0) res[0][12]=a27;
  a18=(a18+a09);
  a18=(a07*a18);
  a18=(a18*a29);
  a15=(a11+a15);
  a15=(a07*a15);
  a15=(a28-a15);
  a15=(a15*a05);
  a18=(a18+a15);
  a15=(a12*a14);
  a09=(a10*a08);
  a27=(a15-a09);
  a27=(a07*a27);
  a27=(a27*a30);
  a18=(a18+a27);
  if (res[0]!=0) res[0][13]=a18;
  a38=(a38-a06);
  a38=(a07*a38);
  a38=(a38*a29);
  a15=(a15+a09);
  a15=(a07*a15);
  a15=(a15*a05);
  a38=(a38+a15);
  a11=(a11+a13);
  a11=(a07*a11);
  a28=(a28-a11);
  a28=(a28*a30);
  a38=(a38+a28);
  a28=9.8066499999999994e+00;
  a38=(a38-a28);
  if (res[0]!=0) res[0][14]=a38;
  a38=6.6666666666666671e+01;
  a28=arg[1]? arg[1][3] : 0;
  a11=7.0000000000000001e-03;
  a11=(a11*a35);
  a13=(a36*a11);
  a15=1.4999999999999999e-02;
  a09=(a15*a36);
  a06=(a35*a09);
  a13=(a13-a06);
  a13=(a28-a13);
  a13=(a38*a13);
  if (res[0]!=0) res[0][15]=a13;
  a06=arg[1]? arg[1][4] : 0;
  a15=(a15*a37);
  a18=(a35*a15);
  a11=(a37*a11);
  a18=(a18-a11);
  a18=(a06-a18);
  a38=(a38*a18);
  if (res[0]!=0) res[0][16]=a38;
  a18=1.4285714285714286e+02;
  a11=arg[1]? arg[1][5] : 0;
  a09=(a37*a09);
  a15=(a36*a15);
  a09=(a09-a15);
  a09=(a11-a09);
  a18=(a18*a09);
  if (res[0]!=0) res[0][17]=a18;
  a09=(a07*a12);
  a15=(a05*a09);
  a27=(a07*a14);
  a01=(a30*a27);
  a16=(a15+a01);
  a03=5.0000000000000000e-01;
  a25=(a37*a08);
  a23=(a35*a12);
  a25=(a25+a23);
  a23=(a36*a14);
  a25=(a25-a23);
  a25=(a03*a25);
  a23=(a16*a25);
  a20=(a30*a09);
  a02=(a05*a27);
  a26=(a20-a02);
  a00=(a37*a10);
  a19=(a36*a12);
  a00=(a00+a19);
  a19=(a35*a14);
  a00=(a00+a19);
  a00=(a03*a00);
  a19=(a26*a00);
  a23=(a23-a19);
  a19=(a07*a10);
  a17=(a05*a19);
  a33=(a12+a12);
  a33=(a07*a33);
  a22=(a29*a33);
  a22=(a17-a22);
  a24=(a07*a08);
  a21=(a30*a24);
  a22=(a22+a21);
  a32=(a36*a08);
  a31=(a35*a10);
  a32=(a32-a31);
  a31=(a37*a14);
  a32=(a32+a31);
  a32=(a03*a32);
  a31=(a22*a32);
  a23=(a23+a31);
  a31=(a30*a19);
  a39=(a14+a14);
  a39=(a07*a39);
  a34=(a29*a39);
  a04=(a05*a24);
  a34=(a34+a04);
  a34=(a31-a34);
  a40=(a35*a08);
  a41=(a36*a10);
  a40=(a40+a41);
  a41=(a37*a12);
  a40=(a40-a41);
  a40=(a03*a40);
  a41=(a34*a40);
  a23=(a23+a41);
  if (res[0]!=0) res[0][18]=a23;
  a09=(a29*a09);
  a23=(a10+a10);
  a23=(a07*a23);
  a41=(a05*a23);
  a41=(a09-a41);
  a41=(a41-a21);
  a21=(a41*a25);
  a27=(a29*a27);
  a31=(a27-a31);
  a42=(a31*a00);
  a21=(a21-a42);
  a19=(a29*a19);
  a01=(a19+a01);
  a42=(a01*a32);
  a21=(a21+a42);
  a24=(a29*a24);
  a39=(a05*a39);
  a39=(a24-a39);
  a39=(a39+a20);
  a20=(a39*a40);
  a21=(a21+a20);
  if (res[0]!=0) res[0][19]=a21;
  a27=(a27+a04);
  a23=(a30*a23);
  a27=(a27-a23);
  a23=(a27*a25);
  a17=(a17-a09);
  a09=(a17*a00);
  a23=(a23-a09);
  a02=(a02-a24);
  a33=(a30*a33);
  a02=(a02-a33);
  a33=(a02*a32);
  a23=(a23+a33);
  a19=(a19+a15);
  a15=(a19*a40);
  a23=(a23+a15);
  if (res[0]!=0) res[0][20]=a23;
  a34=(a03*a34);
  a23=(a36*a34);
  a15=(a30*a40);
  a15=(a07*a15);
  a23=(a23+a15);
  a22=(a03*a22);
  a33=(a35*a22);
  a23=(a23-a33);
  a33=(a05*a32);
  a33=(a07*a33);
  a23=(a23+a33);
  a26=(a03*a26);
  a24=(a37*a26);
  a23=(a23-a24);
  a23=(a23*a25);
  a24=(a35*a34);
  a09=(a05*a40);
  a09=(a07*a09);
  a24=(a24-a09);
  a04=(a36*a22);
  a24=(a24+a04);
  a04=(a30*a32);
  a04=(a07*a04);
  a24=(a24+a04);
  a16=(a03*a16);
  a21=(a37*a16);
  a24=(a24+a21);
  a24=(a24*a00);
  a23=(a23-a24);
  a24=(a35*a16);
  a21=(a37*a34);
  a20=(a29*a32);
  a20=(a07*a20);
  a21=(a21+a20);
  a21=(a21+a20);
  a42=(a36*a26);
  a21=(a21+a42);
  a42=(a30*a00);
  a42=(a07*a42);
  a21=(a21+a42);
  a24=(a24-a21);
  a21=(a05*a25);
  a21=(a07*a21);
  a24=(a24+a21);
  a24=(a24*a32);
  a23=(a23+a24);
  a24=(a37*a22);
  a43=(a29*a40);
  a43=(a07*a43);
  a44=(a43+a43);
  a24=(a24-a44);
  a44=(a35*a26);
  a24=(a24-a44);
  a44=(a05*a00);
  a44=(a07*a44);
  a24=(a24+a44);
  a45=(a36*a16);
  a24=(a24-a45);
  a45=(a30*a25);
  a45=(a07*a45);
  a24=(a24+a45);
  a24=(a24*a40);
  a23=(a23+a24);
  a24=(a14*a22);
  a46=(a12*a34);
  a24=(a24-a46);
  a46=(a10*a26);
  a24=(a24-a46);
  a46=(a08*a16);
  a24=(a24+a46);
  a24=(a24*a13);
  a23=(a23+a24);
  a24=(a10*a34);
  a46=(a08*a22);
  a24=(a24+a46);
  a46=(a12*a26);
  a24=(a24-a46);
  a46=(a14*a16);
  a24=(a24-a46);
  a24=(a24*a38);
  a23=(a23+a24);
  a34=(a08*a34);
  a22=(a10*a22);
  a34=(a34-a22);
  a26=(a14*a26);
  a34=(a34-a26);
  a16=(a12*a16);
  a34=(a34+a16);
  a34=(a34*a18);
  a23=(a23+a34);
  if (res[0]!=0) res[0][21]=a23;
  a42=(a20+a42);
  a42=(a42-a21);
  a42=(a42-a21);
  a39=(a03*a39);
  a23=(a36*a39);
  a42=(a42+a23);
  a01=(a03*a01);
  a23=(a35*a01);
  a42=(a42-a23);
  a31=(a03*a31);
  a23=(a37*a31);
  a42=(a42-a23);
  a42=(a42*a25);
  a23=(a43-a45);
  a34=(a35*a39);
  a23=(a23+a34);
  a34=(a36*a01);
  a23=(a23+a34);
  a41=(a03*a41);
  a34=(a37*a41);
  a23=(a23+a34);
  a23=(a23*a00);
  a42=(a42-a23);
  a23=(a29*a25);
  a23=(a07*a23);
  a15=(a15+a23);
  a34=(a37*a39);
  a15=(a15-a34);
  a34=(a36*a31);
  a15=(a15-a34);
  a34=(a35*a41);
  a15=(a15+a34);
  a15=(a15*a32);
  a42=(a42+a15);
  a15=(a09+a09);
  a15=(a04-a15);
  a34=(a29*a00);
  a07=(a07*a34);
  a15=(a15-a07);
  a34=(a37*a01);
  a15=(a15+a34);
  a34=(a35*a31);
  a15=(a15-a34);
  a34=(a36*a41);
  a15=(a15-a34);
  a15=(a15*a40);
  a42=(a42+a15);
  a15=(a14*a01);
  a34=(a12*a39);
  a15=(a15-a34);
  a34=(a10*a31);
  a15=(a15-a34);
  a34=(a08*a41);
  a15=(a15+a34);
  a15=(a15*a13);
  a42=(a42+a15);
  a15=(a10*a39);
  a34=(a08*a01);
  a15=(a15+a34);
  a34=(a12*a31);
  a15=(a15-a34);
  a34=(a14*a41);
  a15=(a15-a34);
  a15=(a15*a38);
  a42=(a42+a15);
  a39=(a08*a39);
  a01=(a10*a01);
  a39=(a39-a01);
  a31=(a14*a31);
  a39=(a39-a31);
  a41=(a12*a41);
  a39=(a39+a41);
  a39=(a39*a18);
  a42=(a42+a39);
  if (res[0]!=0) res[0][22]=a42;
  a43=(a43-a44);
  a43=(a43-a45);
  a43=(a43-a45);
  a19=(a03*a19);
  a45=(a36*a19);
  a43=(a43+a45);
  a02=(a03*a02);
  a45=(a35*a02);
  a43=(a43-a45);
  a17=(a03*a17);
  a45=(a37*a17);
  a43=(a43-a45);
  a43=(a43*a25);
  a21=(a21-a20);
  a20=(a35*a19);
  a21=(a21+a20);
  a20=(a36*a02);
  a21=(a21+a20);
  a03=(a03*a27);
  a27=(a37*a03);
  a21=(a21+a27);
  a21=(a21*a00);
  a43=(a43-a21);
  a09=(a09-a04);
  a09=(a09-a04);
  a09=(a09+a07);
  a07=(a37*a19);
  a09=(a09-a07);
  a07=(a36*a17);
  a09=(a09-a07);
  a07=(a35*a03);
  a09=(a09+a07);
  a09=(a09*a32);
  a43=(a43+a09);
  a33=(a33+a23);
  a37=(a37*a02);
  a33=(a33+a37);
  a35=(a35*a17);
  a33=(a33-a35);
  a36=(a36*a03);
  a33=(a33-a36);
  a33=(a33*a40);
  a43=(a43+a33);
  a33=(a14*a02);
  a40=(a12*a19);
  a33=(a33-a40);
  a40=(a10*a17);
  a33=(a33-a40);
  a40=(a08*a03);
  a33=(a33+a40);
  a33=(a33*a13);
  a43=(a43+a33);
  a33=(a10*a19);
  a13=(a08*a02);
  a33=(a33+a13);
  a13=(a12*a17);
  a33=(a33-a13);
  a13=(a14*a03);
  a33=(a33-a13);
  a33=(a33*a38);
  a43=(a43+a33);
  a08=(a08*a19);
  a10=(a10*a02);
  a08=(a08-a10);
  a14=(a14*a17);
  a08=(a08-a14);
  a12=(a12*a03);
  a08=(a08+a12);
  a08=(a08*a18);
  a43=(a43+a08);
  if (res[0]!=0) res[0][23]=a43;
  if (res[0]!=0) res[0][24]=a29;
  if (res[0]!=0) res[0][25]=a05;
  if (res[0]!=0) res[0][26]=a30;
  if (res[0]!=0) res[0][27]=a28;
  if (res[0]!=0) res[0][28]=a06;
  if (res[0]!=0) res[0][29]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_cost_y_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
