/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_cost_y_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {9, 1, 1};
static const casadi_int casadi_s4[3] = {24, 1, 1};

/* quadrotor_ode_cost_y_e_fun:(i0[13],i1[0],i2[0],i3[],i4[9])->(o0[24]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  a00=arg[0]? arg[0][0] : 0;
  a01=arg[4]? arg[4][0] : 0;
  a00=(a00-a01);
  a01=casadi_sq(a00);
  a02=arg[0]? arg[0][1] : 0;
  a03=arg[4]? arg[4][1] : 0;
  a02=(a02-a03);
  a03=casadi_sq(a02);
  a01=(a01+a03);
  a03=arg[0]? arg[0][2] : 0;
  a04=arg[4]? arg[4][2] : 0;
  a03=(a03-a04);
  a04=casadi_sq(a03);
  a01=(a01+a04);
  a01=sqrt(a01);
  if (res[0]!=0) res[0][0]=a01;
  a02=atan2(a02,a00);
  if (res[0]!=0) res[0][1]=a02;
  a03=(a03/a01);
  a03=asin(a03);
  if (res[0]!=0) res[0][2]=a03;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a03=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a03;
  a03=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a03;
  a03=arg[4]? arg[4][6] : 0;
  a01=2.;
  a02=arg[0]? arg[0][6] : 0;
  a00=arg[0]? arg[0][9] : 0;
  a04=(a02*a00);
  a05=arg[0]? arg[0][7] : 0;
  a06=arg[0]? arg[0][8] : 0;
  a07=(a05*a06);
  a04=(a04+a07);
  a04=(a01*a04);
  a07=1.;
  a08=casadi_sq(a06);
  a09=casadi_sq(a00);
  a09=(a08+a09);
  a09=(a01*a09);
  a09=(a07-a09);
  a04=atan2(a04,a09);
  a09=cos(a04);
  a10=(a02*a06);
  a11=(a00*a05);
  a10=(a10-a11);
  a10=(a01*a10);
  a10=asin(a10);
  a11=sin(a10);
  a12=(a09*a11);
  a13=(a02*a05);
  a14=(a06*a00);
  a13=(a13+a14);
  a13=(a01*a13);
  a15=casadi_sq(a05);
  a15=(a15+a08);
  a15=(a01*a15);
  a07=(a07-a15);
  a13=atan2(a13,a07);
  a15=cos(a13);
  a08=(a12*a15);
  a04=sin(a04);
  a13=sin(a13);
  a16=(a04*a13);
  a08=(a08+a16);
  a16=arg[4]? arg[4][5] : 0;
  a17=cos(a16);
  a18=arg[4]? arg[4][4] : 0;
  a19=sin(a18);
  a20=(a17*a19);
  a21=arg[4]? arg[4][3] : 0;
  a22=sin(a21);
  a23=(a20*a22);
  a16=sin(a16);
  a21=cos(a21);
  a24=(a16*a21);
  a23=(a23-a24);
  a23=(a08*a23);
  a24=(a04*a11);
  a25=(a24*a15);
  a26=(a09*a13);
  a25=(a25-a26);
  a26=(a16*a19);
  a27=(a26*a22);
  a28=(a17*a21);
  a27=(a27+a28);
  a27=(a25*a27);
  a23=(a23+a27);
  a27=cos(a10);
  a28=(a27*a15);
  a18=cos(a18);
  a29=(a18*a22);
  a29=(a28*a29);
  a23=(a23+a29);
  a20=(a20*a21);
  a29=(a16*a22);
  a20=(a20+a29);
  a20=(a08*a20);
  a26=(a26*a21);
  a22=(a17*a22);
  a26=(a26-a22);
  a26=(a25*a26);
  a20=(a20+a26);
  a21=(a18*a21);
  a21=(a28*a21);
  a20=(a20+a21);
  a23=atan2(a23,a20);
  a03=(a03-a23);
  a23=casadi_fabs(a03);
  a20=3.1415926535897931e+00;
  a21=(a23<=a20);
  a26=(a21?a03:0);
  a21=(!a21);
  a22=0.;
  a03=(a22<=a03);
  a29=6.2831853071795862e+00;
  a23=(a29-a23);
  a30=(-a23);
  a30=(a03?a30:0);
  a03=(!a03);
  a03=(a03?a23:0);
  a30=(a30+a03);
  a21=(a21?a30:0);
  a26=(a26+a21);
  if (res[0]!=0) res[0][6]=a26;
  a26=arg[4]? arg[4][7] : 0;
  a17=(a17*a18);
  a08=(a08*a17);
  a16=(a16*a18);
  a25=(a25*a16);
  a08=(a08+a25);
  a28=(a28*a19);
  a08=(a08-a28);
  a08=asin(a08);
  a26=(a26+a08);
  a08=casadi_fabs(a26);
  a28=(a08<=a20);
  a25=(a28?a26:0);
  a28=(!a28);
  a26=(a22<=a26);
  a08=(a29-a08);
  a18=(-a08);
  a18=(a26?a18:0);
  a26=(!a26);
  a26=(a26?a08:0);
  a18=(a18+a26);
  a28=(a28?a18:0);
  a25=(a25+a28);
  if (res[0]!=0) res[0][7]=a25;
  a25=arg[4]? arg[4][8] : 0;
  a12=(a12*a13);
  a28=(a04*a15);
  a12=(a12-a28);
  a12=(a12*a17);
  a24=(a24*a13);
  a28=(a09*a15);
  a24=(a24+a28);
  a24=(a24*a16);
  a12=(a12+a24);
  a24=(a27*a13);
  a24=(a24*a19);
  a12=(a12-a24);
  a09=(a09*a27);
  a09=(a09*a17);
  a04=(a04*a27);
  a04=(a04*a16);
  a09=(a09+a04);
  a11=(a11*a19);
  a09=(a09+a11);
  a12=atan2(a12,a09);
  a25=(a25-a12);
  a12=casadi_fabs(a25);
  a20=(a12<=a20);
  a09=(a20?a25:0);
  a20=(!a20);
  a22=(a22<=a25);
  a29=(a29-a12);
  a12=(-a29);
  a12=(a22?a12:0);
  a22=(!a22);
  a22=(a22?a29:0);
  a12=(a12+a22);
  a20=(a20?a12:0);
  a09=(a09+a20);
  if (res[0]!=0) res[0][8]=a09;
  a09=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][9]=a09;
  a20=arg[0]? arg[0][11] : 0;
  a12=(a15*a20);
  a10=tan(a10);
  a22=(a13*a10);
  a29=arg[0]? arg[0][12] : 0;
  a22=(a22*a29);
  a12=(a12+a22);
  if (res[0]!=0) res[0][10]=a12;
  a15=(a15*a10);
  a15=(a15*a29);
  a13=(a13*a20);
  a15=(a15-a13);
  if (res[0]!=0) res[0][11]=a15;
  a15=9.8066499999999994e+00;
  a13=(a05*a00);
  a10=(a06*a02);
  a13=(a13+a10);
  a13=(a01*a13);
  a13=(a15*a13);
  if (res[0]!=0) res[0][12]=a13;
  a13=(a05*a02);
  a14=(a14-a13);
  a14=(a01*a14);
  a14=(a15*a14);
  if (res[0]!=0) res[0][13]=a14;
  a07=(a15*a07);
  a07=(a07-a15);
  if (res[0]!=0) res[0][14]=a07;
  a07=6.6666666666666671e+01;
  a14=7.0000000000000001e-03;
  a14=(a14*a29);
  a13=(a20*a14);
  a10=1.4999999999999999e-02;
  a12=(a10*a20);
  a22=(a29*a12);
  a13=(a13-a22);
  a13=(a07*a13);
  a22=(-a13);
  if (res[0]!=0) res[0][15]=a22;
  a10=(a10*a09);
  a22=(a29*a10);
  a14=(a09*a14);
  a22=(a22-a14);
  a07=(a07*a22);
  a22=(-a07);
  if (res[0]!=0) res[0][16]=a22;
  a22=1.4285714285714286e+02;
  a12=(a09*a12);
  a10=(a20*a10);
  a12=(a12-a10);
  a22=(a22*a12);
  a12=(-a22);
  if (res[0]!=0) res[0][17]=a12;
  a12=(a01*a00);
  a12=(a15*a12);
  a10=5.0000000000000000e-01;
  a14=(a09*a02);
  a25=(a29*a06);
  a14=(a14+a25);
  a25=(a20*a00);
  a14=(a14-a25);
  a14=(a10*a14);
  a25=(a12*a14);
  a11=(a01*a06);
  a11=(a15*a11);
  a19=(a09*a05);
  a04=(a20*a06);
  a19=(a19+a04);
  a04=(a29*a00);
  a19=(a19+a04);
  a19=(a10*a19);
  a04=(a11*a19);
  a25=(a25-a04);
  a04=(a01*a02);
  a04=(a15*a04);
  a16=(a20*a02);
  a27=(a29*a05);
  a16=(a16-a27);
  a27=(a09*a00);
  a16=(a16+a27);
  a16=(a10*a16);
  a27=(a04*a16);
  a25=(a25+a27);
  a27=(a01*a05);
  a27=(a15*a27);
  a17=(a29*a02);
  a24=(a20*a05);
  a17=(a17+a24);
  a24=(a09*a06);
  a17=(a17-a24);
  a17=(a10*a17);
  a24=(a27*a17);
  a25=(a25+a24);
  if (res[0]!=0) res[0][18]=a25;
  a25=(a27*a19);
  a24=(a04*a14);
  a25=(a25-a24);
  a24=(a12*a16);
  a25=(a25+a24);
  a24=(a11*a17);
  a25=(a25+a24);
  if (res[0]!=0) res[0][19]=a25;
  a25=(a05+a05);
  a25=(a01*a25);
  a25=(a15*a25);
  a24=(a25*a14);
  a28=(a06+a06);
  a28=(a01*a28);
  a28=(a15*a28);
  a18=(a28*a16);
  a24=(a24+a18);
  a24=(-a24);
  if (res[0]!=0) res[0][20]=a24;
  a27=(a10*a27);
  a24=(a20*a27);
  a18=(a15*a17);
  a18=(a01*a18);
  a26=(a24+a18);
  a04=(a10*a04);
  a08=(a29*a04);
  a26=(a26-a08);
  a11=(a10*a11);
  a21=(a09*a11);
  a26=(a26-a21);
  a26=(a26*a14);
  a30=(a29*a27);
  a03=(a20*a04);
  a23=(a30+a03);
  a31=(a15*a16);
  a31=(a01*a31);
  a23=(a23+a31);
  a12=(a10*a12);
  a32=(a09*a12);
  a23=(a23+a32);
  a23=(a23*a19);
  a26=(a26-a23);
  a23=(a29*a12);
  a33=(a09*a27);
  a34=(a20*a11);
  a35=(a33+a34);
  a36=(a15*a19);
  a36=(a01*a36);
  a35=(a35+a36);
  a35=(a23-a35);
  a35=(a35*a16);
  a26=(a26+a35);
  a35=(a09*a04);
  a37=(a29*a11);
  a38=(a35-a37);
  a39=(a20*a12);
  a38=(a38-a39);
  a15=(a15*a14);
  a01=(a01*a15);
  a38=(a38+a01);
  a38=(a38*a17);
  a26=(a26+a38);
  a38=(a00*a04);
  a15=(a06*a27);
  a40=(a38-a15);
  a41=(a05*a11);
  a40=(a40-a41);
  a42=(a02*a12);
  a40=(a40+a42);
  a40=(a40*a13);
  a26=(a26-a40);
  a40=(a05*a27);
  a43=(a02*a04);
  a44=(a40+a43);
  a45=(a06*a11);
  a44=(a44-a45);
  a46=(a00*a12);
  a44=(a44-a46);
  a44=(a44*a07);
  a26=(a26-a44);
  a44=(a02*a27);
  a47=(a05*a04);
  a44=(a44-a47);
  a47=(a00*a11);
  a44=(a44-a47);
  a47=(a06*a12);
  a44=(a44+a47);
  a44=(a44*a22);
  a26=(a26-a44);
  if (res[0]!=0) res[0][21]=a26;
  a36=(a36+a34);
  a36=(a36-a23);
  a36=(a36+a33);
  a36=(a36*a14);
  a37=(a37-a01);
  a37=(a37+a39);
  a37=(a37-a35);
  a37=(a37*a19);
  a36=(a36-a37);
  a18=(a18-a21);
  a18=(a18+a24);
  a18=(a18-a08);
  a18=(a18*a16);
  a36=(a36+a18);
  a32=(a31+a32);
  a32=(a32+a30);
  a32=(a32+a03);
  a32=(a32*a17);
  a36=(a36+a32);
  a46=(a46-a45);
  a46=(a46+a40);
  a46=(a46-a43);
  a46=(a46*a13);
  a36=(a36-a46);
  a41=(a41+a42);
  a41=(a41+a15);
  a41=(a41+a38);
  a41=(a41*a07);
  a36=(a36-a41);
  a11=(a02*a11);
  a12=(a05*a12);
  a11=(a11-a12);
  a27=(a00*a27);
  a11=(a11+a27);
  a04=(a06*a04);
  a11=(a11-a04);
  a11=(a11*a22);
  a36=(a36-a11);
  if (res[0]!=0) res[0][22]=a36;
  a28=(a10*a28);
  a36=(a29*a28);
  a01=(a01+a01);
  a36=(a36-a01);
  a36=(a36*a14);
  a14=(a20*a28);
  a10=(a10*a25);
  a25=(a09*a10);
  a14=(a14+a25);
  a14=(a14*a19);
  a36=(a36+a14);
  a31=(a31+a31);
  a29=(a29*a10);
  a31=(a31+a29);
  a31=(a31*a16);
  a36=(a36-a31);
  a20=(a20*a10);
  a09=(a09*a28);
  a20=(a20-a09);
  a20=(a20*a17);
  a36=(a36+a20);
  a20=(a00*a28);
  a17=(a02*a10);
  a20=(a20+a17);
  a20=(a20*a13);
  a36=(a36+a20);
  a00=(a00*a10);
  a02=(a02*a28);
  a00=(a00-a02);
  a00=(a00*a07);
  a36=(a36-a00);
  a05=(a05*a28);
  a06=(a06*a10);
  a05=(a05-a06);
  a05=(a05*a22);
  a36=(a36-a05);
  if (res[0]!=0) res[0][23]=a36;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_e_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_cost_y_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
