/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_cost_y_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {6, 1, 1};
static const casadi_int casadi_s4[3] = {21, 1, 1};

/* quadrotor_ode_cost_y_e_fun:(i0[13],i1[0],i2[0],i3[],i4[6])->(o0[21]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49;
  a00=arg[0]? arg[0][0] : 0;
  a01=arg[4]? arg[4][0] : 0;
  a00=(a00-a01);
  a01=casadi_sq(a00);
  a02=arg[0]? arg[0][1] : 0;
  a03=arg[4]? arg[4][1] : 0;
  a02=(a02-a03);
  a03=casadi_sq(a02);
  a01=(a01+a03);
  a03=arg[0]? arg[0][2] : 0;
  a04=arg[4]? arg[4][2] : 0;
  a03=(a03-a04);
  a04=casadi_sq(a03);
  a01=(a01+a04);
  a01=sqrt(a01);
  if (res[0]!=0) res[0][0]=a01;
  a00=atan2(a00,a02);
  if (res[0]!=0) res[0][1]=a00;
  a03=(a03/a01);
  a03=asin(a03);
  if (res[0]!=0) res[0][2]=a03;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a03=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a03;
  a03=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a03;
  a03=2.;
  a01=arg[0]? arg[0][6] : 0;
  a00=arg[0]? arg[0][9] : 0;
  a02=(a01*a00);
  a04=arg[0]? arg[0][7] : 0;
  a05=arg[0]? arg[0][8] : 0;
  a06=(a04*a05);
  a02=(a02+a06);
  a02=(a03*a02);
  a06=1.;
  a07=casadi_sq(a05);
  a08=casadi_sq(a00);
  a08=(a07+a08);
  a08=(a03*a08);
  a08=(a06-a08);
  a02=atan2(a02,a08);
  a08=sin(a02);
  a09=(a01*a05);
  a10=(a00*a04);
  a09=(a09-a10);
  a09=(a03*a09);
  a09=asin(a09);
  a10=sin(a09);
  a11=(a08*a10);
  a12=(a01*a04);
  a13=(a05*a00);
  a12=(a12+a13);
  a12=(a03*a12);
  a14=casadi_sq(a04);
  a14=(a14+a07);
  a14=(a03*a14);
  a06=(a06-a14);
  a12=atan2(a12,a06);
  a14=cos(a12);
  a11=(a11*a14);
  a02=cos(a02);
  a12=sin(a12);
  a07=(a02*a12);
  a11=(a11-a07);
  a07=arg[4]? arg[4][4] : 0;
  a15=cos(a07);
  a16=arg[4]? arg[4][3] : 0;
  a17=sin(a16);
  a17=(a15*a17);
  a11=(a11*a17);
  a17=cos(a09);
  a18=(a17*a14);
  a16=cos(a16);
  a16=(a15*a16);
  a18=(a18*a16);
  a11=atan2(a11,a18);
  if (res[0]!=0) res[0][6]=a11;
  a10=(a02*a10);
  a11=(a10*a14);
  a18=(a08*a12);
  a11=(a11+a18);
  a07=sin(a07);
  a11=(a11*a07);
  a11=(-a11);
  a11=asin(a11);
  a11=(-a11);
  if (res[0]!=0) res[0][7]=a11;
  a10=(a10*a12);
  a08=(a08*a14);
  a10=(a10-a08);
  a08=arg[4]? arg[4][5] : 0;
  a11=sin(a08);
  a11=(a11*a15);
  a10=(a10*a11);
  a02=(a02*a17);
  a08=cos(a08);
  a08=(a08*a15);
  a02=(a02*a08);
  a10=atan2(a10,a02);
  if (res[0]!=0) res[0][8]=a10;
  a10=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][9]=a10;
  a02=arg[0]? arg[0][11] : 0;
  a08=(a14*a02);
  a09=tan(a09);
  a15=(a12*a09);
  a17=arg[0]? arg[0][12] : 0;
  a15=(a15*a17);
  a08=(a08+a15);
  if (res[0]!=0) res[0][10]=a08;
  a14=(a14*a09);
  a14=(a14*a17);
  a12=(a12*a02);
  a14=(a14-a12);
  if (res[0]!=0) res[0][11]=a14;
  a14=9.8066499999999994e+00;
  a12=(a04*a00);
  a09=(a05*a01);
  a12=(a12+a09);
  a12=(a03*a12);
  a12=(a14*a12);
  if (res[0]!=0) res[0][12]=a12;
  a12=(a04*a01);
  a13=(a13-a12);
  a13=(a03*a13);
  a13=(a14*a13);
  if (res[0]!=0) res[0][13]=a13;
  a06=(a14*a06);
  a06=(a06-a14);
  if (res[0]!=0) res[0][14]=a06;
  a06=(a03*a00);
  a06=(a14*a06);
  a13=5.0000000000000000e-01;
  a12=(a10*a01);
  a09=(a17*a05);
  a12=(a12+a09);
  a09=(a02*a00);
  a12=(a12-a09);
  a12=(a13*a12);
  a09=(a06*a12);
  a08=(a03*a05);
  a08=(a14*a08);
  a15=(a10*a04);
  a11=(a02*a05);
  a15=(a15+a11);
  a11=(a17*a00);
  a15=(a15+a11);
  a15=(a13*a15);
  a11=(a08*a15);
  a09=(a09-a11);
  a11=(a03*a01);
  a11=(a14*a11);
  a07=(a02*a01);
  a18=(a17*a04);
  a07=(a07-a18);
  a18=(a10*a00);
  a07=(a07+a18);
  a07=(a13*a07);
  a18=(a11*a07);
  a09=(a09+a18);
  a18=(a03*a04);
  a18=(a14*a18);
  a16=(a17*a01);
  a19=(a02*a04);
  a16=(a16+a19);
  a19=(a10*a05);
  a16=(a16-a19);
  a16=(a13*a16);
  a19=(a18*a16);
  a09=(a09+a19);
  if (res[0]!=0) res[0][15]=a09;
  a09=(a18*a15);
  a19=(a11*a12);
  a09=(a09-a19);
  a19=(a06*a07);
  a09=(a09+a19);
  a19=(a08*a16);
  a09=(a09+a19);
  if (res[0]!=0) res[0][16]=a09;
  a09=(a04+a04);
  a09=(a03*a09);
  a09=(a14*a09);
  a19=(a09*a12);
  a20=(a05+a05);
  a20=(a03*a20);
  a20=(a14*a20);
  a21=(a20*a07);
  a19=(a19+a21);
  a19=(-a19);
  if (res[0]!=0) res[0][17]=a19;
  a18=(a13*a18);
  a19=(a02*a18);
  a21=(a14*a16);
  a21=(a03*a21);
  a22=(a19+a21);
  a11=(a13*a11);
  a23=(a17*a11);
  a22=(a22-a23);
  a08=(a13*a08);
  a24=(a10*a08);
  a22=(a22-a24);
  a22=(a22*a12);
  a25=(a17*a18);
  a26=(a02*a11);
  a27=(a25+a26);
  a28=(a14*a07);
  a28=(a03*a28);
  a27=(a27+a28);
  a06=(a13*a06);
  a29=(a10*a06);
  a27=(a27+a29);
  a27=(a27*a15);
  a22=(a22-a27);
  a27=(a17*a06);
  a30=(a10*a18);
  a31=(a02*a08);
  a32=(a30+a31);
  a33=(a14*a15);
  a33=(a03*a33);
  a32=(a32+a33);
  a32=(a27-a32);
  a32=(a32*a07);
  a22=(a22+a32);
  a32=(a10*a11);
  a34=(a17*a08);
  a35=(a32-a34);
  a36=(a02*a06);
  a35=(a35-a36);
  a14=(a14*a12);
  a03=(a03*a14);
  a35=(a35+a03);
  a35=(a35*a16);
  a22=(a22+a35);
  a35=(a00*a11);
  a14=(a05*a18);
  a37=(a35-a14);
  a38=(a04*a08);
  a37=(a37-a38);
  a39=(a01*a06);
  a37=(a37+a39);
  a40=6.6666666666666671e+01;
  a41=7.0000000000000001e-03;
  a41=(a41*a17);
  a42=(a02*a41);
  a43=1.4999999999999999e-02;
  a44=(a43*a02);
  a45=(a17*a44);
  a42=(a42-a45);
  a42=(a40*a42);
  a37=(a37*a42);
  a22=(a22-a37);
  a37=(a04*a18);
  a45=(a01*a11);
  a46=(a37+a45);
  a47=(a05*a08);
  a46=(a46-a47);
  a48=(a00*a06);
  a46=(a46-a48);
  a43=(a43*a10);
  a49=(a17*a43);
  a41=(a10*a41);
  a49=(a49-a41);
  a40=(a40*a49);
  a46=(a46*a40);
  a22=(a22-a46);
  a46=(a01*a18);
  a49=(a04*a11);
  a46=(a46-a49);
  a49=(a00*a08);
  a46=(a46-a49);
  a49=(a05*a06);
  a46=(a46+a49);
  a49=1.4285714285714286e+02;
  a44=(a10*a44);
  a43=(a02*a43);
  a44=(a44-a43);
  a49=(a49*a44);
  a46=(a46*a49);
  a22=(a22-a46);
  if (res[0]!=0) res[0][18]=a22;
  a33=(a33+a31);
  a33=(a33-a27);
  a33=(a33+a30);
  a33=(a33*a12);
  a34=(a34-a03);
  a34=(a34+a36);
  a34=(a34-a32);
  a34=(a34*a15);
  a33=(a33-a34);
  a21=(a21-a24);
  a21=(a21+a19);
  a21=(a21-a23);
  a21=(a21*a07);
  a33=(a33+a21);
  a29=(a28+a29);
  a29=(a29+a25);
  a29=(a29+a26);
  a29=(a29*a16);
  a33=(a33+a29);
  a48=(a48-a47);
  a48=(a48+a37);
  a48=(a48-a45);
  a48=(a48*a42);
  a33=(a33-a48);
  a38=(a38+a39);
  a38=(a38+a14);
  a38=(a38+a35);
  a38=(a38*a40);
  a33=(a33-a38);
  a08=(a01*a08);
  a06=(a04*a06);
  a08=(a08-a06);
  a18=(a00*a18);
  a08=(a08+a18);
  a11=(a05*a11);
  a08=(a08-a11);
  a08=(a08*a49);
  a33=(a33-a08);
  if (res[0]!=0) res[0][19]=a33;
  a20=(a13*a20);
  a33=(a17*a20);
  a03=(a03+a03);
  a33=(a33-a03);
  a33=(a33*a12);
  a12=(a02*a20);
  a13=(a13*a09);
  a09=(a10*a13);
  a12=(a12+a09);
  a12=(a12*a15);
  a33=(a33+a12);
  a28=(a28+a28);
  a17=(a17*a13);
  a28=(a28+a17);
  a28=(a28*a07);
  a33=(a33-a28);
  a02=(a02*a13);
  a10=(a10*a20);
  a02=(a02-a10);
  a02=(a02*a16);
  a33=(a33+a02);
  a02=(a00*a20);
  a16=(a01*a13);
  a02=(a02+a16);
  a02=(a02*a42);
  a33=(a33+a02);
  a00=(a00*a13);
  a01=(a01*a20);
  a00=(a00-a01);
  a00=(a00*a40);
  a33=(a33-a00);
  a04=(a04*a20);
  a05=(a05*a13);
  a04=(a04-a05);
  a04=(a04*a49);
  a33=(a33-a04);
  if (res[0]!=0) res[0][20]=a33;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_e_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_cost_y_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
