/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_cost_y_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {9, 1, 1};
static const casadi_int casadi_s4[3] = {25, 1, 1};

/* quadrotor_ode_cost_y_e_fun:(i0[13],i1[0],i2[0],i3[],i4[9])->(o0[25]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50;
  a00=arg[0]? arg[0][0] : 0;
  a01=arg[4]? arg[4][0] : 0;
  a00=(a00-a01);
  a01=casadi_sq(a00);
  a02=arg[0]? arg[0][1] : 0;
  a03=arg[4]? arg[4][1] : 0;
  a02=(a02-a03);
  a03=casadi_sq(a02);
  a01=(a01+a03);
  a03=arg[0]? arg[0][2] : 0;
  a04=arg[4]? arg[4][2] : 0;
  a03=(a03-a04);
  a04=casadi_sq(a03);
  a01=(a01+a04);
  a01=sqrt(a01);
  if (res[0]!=0) res[0][0]=a01;
  a02=atan2(a02,a00);
  if (res[0]!=0) res[0][1]=a02;
  a03=(a03/a01);
  a03=asin(a03);
  if (res[0]!=0) res[0][2]=a03;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a03=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a03;
  a03=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a03;
  a03=0.;
  a01=2.;
  a02=arg[0]? arg[0][6] : 0;
  a00=arg[0]? arg[0][9] : 0;
  a04=(a02*a00);
  a05=arg[0]? arg[0][7] : 0;
  a06=arg[0]? arg[0][8] : 0;
  a07=(a05*a06);
  a04=(a04+a07);
  a04=(a01*a04);
  a07=1.;
  a08=casadi_sq(a06);
  a09=casadi_sq(a00);
  a09=(a08+a09);
  a09=(a01*a09);
  a09=(a07-a09);
  a04=atan2(a04,a09);
  a09=cos(a04);
  a10=(a02*a06);
  a11=(a00*a05);
  a10=(a10-a11);
  a10=(a01*a10);
  a10=asin(a10);
  a11=cos(a10);
  a12=(a09*a11);
  a13=arg[4]? arg[4][5] : 0;
  a14=cos(a13);
  a15=arg[4]? arg[4][4] : 0;
  a16=cos(a15);
  a17=(a14*a16);
  a18=(a12*a17);
  a04=sin(a04);
  a19=(a04*a11);
  a13=sin(a13);
  a20=(a13*a16);
  a21=(a19*a20);
  a18=(a18+a21);
  a21=sin(a10);
  a15=sin(a15);
  a22=(a21*a15);
  a18=(a18+a22);
  a22=arg[4]? arg[4][8] : 0;
  a23=cos(a22);
  a24=arg[4]? arg[4][7] : 0;
  a25=cos(a24);
  a26=(a23*a25);
  a27=(a18*a26);
  a28=(a09*a21);
  a29=(a02*a05);
  a30=(a06*a00);
  a29=(a29+a30);
  a29=(a01*a29);
  a31=casadi_sq(a05);
  a31=(a31+a08);
  a31=(a01*a31);
  a31=(a07-a31);
  a29=atan2(a29,a31);
  a08=sin(a29);
  a32=(a28*a08);
  a29=cos(a29);
  a33=(a04*a29);
  a32=(a32-a33);
  a33=(a32*a17);
  a34=(a04*a21);
  a35=(a34*a08);
  a36=(a09*a29);
  a35=(a35+a36);
  a36=(a35*a20);
  a33=(a33+a36);
  a36=(a11*a08);
  a37=(a36*a15);
  a33=(a33-a37);
  a22=sin(a22);
  a37=(a22*a25);
  a38=(a33*a37);
  a27=(a27+a38);
  a28=(a28*a29);
  a04=(a04*a08);
  a28=(a28+a04);
  a17=(a28*a17);
  a34=(a34*a29);
  a09=(a09*a08);
  a34=(a34-a09);
  a20=(a34*a20);
  a17=(a17+a20);
  a11=(a11*a29);
  a20=(a11*a15);
  a17=(a17-a20);
  a24=sin(a24);
  a20=(a17*a24);
  a27=(a27-a20);
  a20=(a14*a15);
  a09=arg[4]? arg[4][3] : 0;
  a04=sin(a09);
  a38=(a20*a04);
  a09=cos(a09);
  a39=(a13*a09);
  a38=(a38-a39);
  a39=(a12*a38);
  a15=(a13*a15);
  a40=(a15*a04);
  a41=(a14*a09);
  a40=(a40+a41);
  a41=(a19*a40);
  a39=(a39+a41);
  a41=(a16*a04);
  a42=(a21*a41);
  a39=(a39-a42);
  a42=(a23*a24);
  a43=arg[4]? arg[4][6] : 0;
  a44=sin(a43);
  a45=(a42*a44);
  a43=cos(a43);
  a46=(a22*a43);
  a45=(a45-a46);
  a46=(a39*a45);
  a47=(a32*a38);
  a48=(a35*a40);
  a47=(a47+a48);
  a48=(a36*a41);
  a47=(a47+a48);
  a48=(a22*a24);
  a49=(a48*a44);
  a50=(a23*a43);
  a49=(a49+a50);
  a50=(a47*a49);
  a46=(a46+a50);
  a38=(a28*a38);
  a40=(a34*a40);
  a38=(a38+a40);
  a41=(a11*a41);
  a38=(a38+a41);
  a41=(a25*a44);
  a40=(a38*a41);
  a46=(a46+a40);
  a40=(a27+a46);
  a20=(a20*a09);
  a13=(a13*a04);
  a20=(a20+a13);
  a12=(a12*a20);
  a15=(a15*a09);
  a14=(a14*a04);
  a15=(a15-a14);
  a19=(a19*a15);
  a12=(a12+a19);
  a16=(a16*a09);
  a21=(a21*a16);
  a12=(a12-a21);
  a42=(a42*a43);
  a22=(a22*a44);
  a42=(a42+a22);
  a22=(a12*a42);
  a32=(a32*a20);
  a35=(a35*a15);
  a32=(a32+a35);
  a36=(a36*a16);
  a32=(a32+a36);
  a48=(a48*a43);
  a23=(a23*a44);
  a48=(a48-a23);
  a23=(a32*a48);
  a22=(a22+a23);
  a28=(a28*a20);
  a34=(a34*a15);
  a28=(a28+a34);
  a11=(a11*a16);
  a28=(a28+a11);
  a25=(a25*a43);
  a43=(a28*a25);
  a22=(a22+a43);
  a40=(a40+a22);
  a03=(a03<a40);
  a43=2.5000000000000000e-01;
  a40=(a40+a07);
  a40=sqrt(a40);
  a40=(a01*a40);
  a11=(a43*a40);
  a11=(a03?a11:0);
  a16=(!a03);
  a34=(a46<a27);
  a15=(a22<a27);
  a34=(a34&&a15);
  a15=(a12*a45);
  a20=(a32*a49);
  a15=(a15+a20);
  a20=(a28*a41);
  a15=(a15+a20);
  a20=(a39*a42);
  a23=(a47*a48);
  a20=(a20+a23);
  a23=(a38*a25);
  a20=(a20+a23);
  a23=(a15-a20);
  a44=(a07+a27);
  a44=(a44-a46);
  a44=(a44-a22);
  a44=sqrt(a44);
  a44=(a01*a44);
  a36=(a23/a44);
  a36=(a34?a36:0);
  a35=(!a34);
  a21=(a22<a46);
  a42=(a18*a42);
  a48=(a33*a48);
  a42=(a42+a48);
  a25=(a17*a25);
  a42=(a42+a25);
  a12=(a12*a26);
  a32=(a32*a37);
  a12=(a12+a32);
  a28=(a28*a24);
  a12=(a12-a28);
  a28=(a42-a12);
  a32=(a07+a46);
  a32=(a32-a27);
  a32=(a32-a22);
  a32=sqrt(a32);
  a32=(a01*a32);
  a25=(a28/a32);
  a25=(a21?a25:0);
  a48=(!a21);
  a39=(a39*a26);
  a47=(a47*a37);
  a39=(a39+a47);
  a38=(a38*a24);
  a39=(a39-a38);
  a18=(a18*a45);
  a33=(a33*a49);
  a18=(a18+a33);
  a17=(a17*a41);
  a18=(a18+a17);
  a17=(a39-a18);
  a07=(a07+a22);
  a07=(a07-a27);
  a07=(a07-a46);
  a07=sqrt(a07);
  a07=(a01*a07);
  a46=(a17/a07);
  a46=(a48?a46:0);
  a25=(a25+a46);
  a25=(a35?a25:0);
  a36=(a36+a25);
  a36=(a16?a36:0);
  a11=(a11+a36);
  a36=casadi_sq(a11);
  a23=(a23/a40);
  a23=(a03?a23:0);
  a25=(a43*a44);
  a25=(a34?a25:0);
  a18=(a18+a39);
  a39=(a18/a32);
  a39=(a21?a39:0);
  a42=(a42+a12);
  a12=(a42/a07);
  a12=(a48?a12:0);
  a39=(a39+a12);
  a39=(a35?a39:0);
  a25=(a25+a39);
  a25=(a16?a25:0);
  a23=(a23+a25);
  a25=casadi_sq(a23);
  a36=(a36+a25);
  a28=(a28/a40);
  a28=(a03?a28:0);
  a18=(a18/a44);
  a18=(a34?a18:0);
  a25=(a43*a32);
  a25=(a21?a25:0);
  a20=(a20+a15);
  a15=(a20/a07);
  a15=(a48?a15:0);
  a25=(a25+a15);
  a25=(a35?a25:0);
  a18=(a18+a25);
  a18=(a16?a18:0);
  a28=(a28+a18);
  a18=casadi_sq(a28);
  a36=(a36+a18);
  a17=(a17/a40);
  a03=(a03?a17:0);
  a42=(a42/a44);
  a34=(a34?a42:0);
  a20=(a20/a32);
  a21=(a21?a20:0);
  a43=(a43*a07);
  a48=(a48?a43:0);
  a21=(a21+a48);
  a35=(a35?a21:0);
  a34=(a34+a35);
  a16=(a16?a34:0);
  a03=(a03+a16);
  a16=casadi_sq(a03);
  a36=(a36+a16);
  a36=sqrt(a36);
  a11=(a11/a36);
  if (res[0]!=0) res[0][6]=a11;
  a23=(a23/a36);
  if (res[0]!=0) res[0][7]=a23;
  a28=(a28/a36);
  if (res[0]!=0) res[0][8]=a28;
  a03=(a03/a36);
  if (res[0]!=0) res[0][9]=a03;
  a03=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][10]=a03;
  a36=arg[0]? arg[0][11] : 0;
  a28=(a29*a36);
  a10=tan(a10);
  a23=(a08*a10);
  a11=arg[0]? arg[0][12] : 0;
  a23=(a23*a11);
  a28=(a28+a23);
  if (res[0]!=0) res[0][11]=a28;
  a29=(a29*a10);
  a29=(a29*a11);
  a08=(a08*a36);
  a29=(a29-a08);
  if (res[0]!=0) res[0][12]=a29;
  a29=7.8125000000000000e-01;
  a08=9.8066499999999994e+00;
  a10=(a05*a00);
  a28=(a06*a02);
  a10=(a10+a28);
  a10=(a01*a10);
  a10=(a08*a10);
  a10=(a29*a10);
  if (res[0]!=0) res[0][13]=a10;
  a10=(a05*a02);
  a30=(a30-a10);
  a30=(a01*a30);
  a30=(a08*a30);
  a30=(a29*a30);
  if (res[0]!=0) res[0][14]=a30;
  a31=(a08*a31);
  a31=(a29*a31);
  a31=(a31-a08);
  if (res[0]!=0) res[0][15]=a31;
  a31=4.3478260869565219e+01;
  a30=2.1999999999999999e-02;
  a30=(a30*a11);
  a10=(a36*a30);
  a28=2.3000000000000000e-02;
  a23=(a28*a36);
  a16=(a11*a23);
  a10=(a10-a16);
  a10=(a31*a10);
  a16=(-a10);
  if (res[0]!=0) res[0][16]=a16;
  a28=(a28*a03);
  a16=(a11*a28);
  a30=(a03*a30);
  a16=(a16-a30);
  a31=(a31*a16);
  a16=(-a31);
  if (res[0]!=0) res[0][17]=a16;
  a16=4.5454545454545460e+01;
  a23=(a03*a23);
  a28=(a36*a28);
  a23=(a23-a28);
  a16=(a16*a23);
  a23=(-a16);
  if (res[0]!=0) res[0][18]=a23;
  a23=(a01*a00);
  a23=(a08*a23);
  a23=(a29*a23);
  a28=5.0000000000000000e-01;
  a30=(a03*a02);
  a34=(a11*a06);
  a30=(a30+a34);
  a34=(a36*a00);
  a30=(a30-a34);
  a30=(a28*a30);
  a34=(a23*a30);
  a35=(a01*a06);
  a35=(a08*a35);
  a35=(a29*a35);
  a21=(a03*a05);
  a48=(a36*a06);
  a21=(a21+a48);
  a48=(a11*a00);
  a21=(a21+a48);
  a21=(a28*a21);
  a48=(a35*a21);
  a34=(a34-a48);
  a48=(a01*a02);
  a48=(a08*a48);
  a48=(a29*a48);
  a43=(a36*a02);
  a07=(a11*a05);
  a43=(a43-a07);
  a07=(a03*a00);
  a43=(a43+a07);
  a43=(a28*a43);
  a07=(a48*a43);
  a34=(a34+a07);
  a07=(a01*a05);
  a07=(a08*a07);
  a07=(a29*a07);
  a20=(a11*a02);
  a32=(a36*a05);
  a20=(a20+a32);
  a32=(a03*a06);
  a20=(a20-a32);
  a20=(a28*a20);
  a32=(a07*a20);
  a34=(a34+a32);
  if (res[0]!=0) res[0][19]=a34;
  a34=(a07*a21);
  a32=(a48*a30);
  a34=(a34-a32);
  a32=(a23*a43);
  a34=(a34+a32);
  a32=(a35*a20);
  a34=(a34+a32);
  if (res[0]!=0) res[0][20]=a34;
  a34=(a05+a05);
  a34=(a01*a34);
  a34=(a08*a34);
  a34=(a29*a34);
  a32=(a34*a30);
  a42=(a06+a06);
  a42=(a01*a42);
  a42=(a08*a42);
  a42=(a29*a42);
  a44=(a42*a43);
  a32=(a32+a44);
  a32=(-a32);
  if (res[0]!=0) res[0][21]=a32;
  a07=(a28*a07);
  a32=(a36*a07);
  a44=(a29*a20);
  a44=(a08*a44);
  a44=(a01*a44);
  a17=(a32+a44);
  a48=(a28*a48);
  a40=(a11*a48);
  a17=(a17-a40);
  a35=(a28*a35);
  a18=(a03*a35);
  a17=(a17-a18);
  a17=(a17*a30);
  a25=(a11*a07);
  a15=(a36*a48);
  a39=(a25+a15);
  a12=(a29*a43);
  a12=(a08*a12);
  a12=(a01*a12);
  a39=(a39+a12);
  a23=(a28*a23);
  a46=(a03*a23);
  a39=(a39+a46);
  a39=(a39*a21);
  a17=(a17-a39);
  a39=(a11*a23);
  a27=(a03*a07);
  a22=(a36*a35);
  a41=(a27+a22);
  a33=(a29*a21);
  a33=(a08*a33);
  a33=(a01*a33);
  a41=(a41+a33);
  a41=(a39-a41);
  a41=(a41*a43);
  a17=(a17+a41);
  a41=(a03*a48);
  a49=(a11*a35);
  a45=(a41-a49);
  a38=(a36*a23);
  a45=(a45-a38);
  a29=(a29*a30);
  a08=(a08*a29);
  a01=(a01*a08);
  a45=(a45+a01);
  a45=(a45*a20);
  a17=(a17+a45);
  a45=(a00*a48);
  a08=(a06*a07);
  a29=(a45-a08);
  a24=(a05*a35);
  a29=(a29-a24);
  a47=(a02*a23);
  a29=(a29+a47);
  a29=(a29*a10);
  a17=(a17-a29);
  a29=(a05*a07);
  a37=(a02*a48);
  a26=(a29+a37);
  a09=(a06*a35);
  a26=(a26-a09);
  a19=(a00*a23);
  a26=(a26-a19);
  a26=(a26*a31);
  a17=(a17-a26);
  a26=(a02*a07);
  a14=(a05*a48);
  a26=(a26-a14);
  a14=(a00*a35);
  a26=(a26-a14);
  a14=(a06*a23);
  a26=(a26+a14);
  a26=(a26*a16);
  a17=(a17-a26);
  if (res[0]!=0) res[0][22]=a17;
  a33=(a33+a22);
  a33=(a33-a39);
  a33=(a33+a27);
  a33=(a33*a30);
  a49=(a49-a01);
  a49=(a49+a38);
  a49=(a49-a41);
  a49=(a49*a21);
  a33=(a33-a49);
  a44=(a44-a18);
  a44=(a44+a32);
  a44=(a44-a40);
  a44=(a44*a43);
  a33=(a33+a44);
  a46=(a12+a46);
  a46=(a46+a25);
  a46=(a46+a15);
  a46=(a46*a20);
  a33=(a33+a46);
  a19=(a19-a09);
  a19=(a19+a29);
  a19=(a19-a37);
  a19=(a19*a10);
  a33=(a33-a19);
  a24=(a24+a47);
  a24=(a24+a08);
  a24=(a24+a45);
  a24=(a24*a31);
  a33=(a33-a24);
  a35=(a02*a35);
  a23=(a05*a23);
  a35=(a35-a23);
  a07=(a00*a07);
  a35=(a35+a07);
  a48=(a06*a48);
  a35=(a35-a48);
  a35=(a35*a16);
  a33=(a33-a35);
  if (res[0]!=0) res[0][23]=a33;
  a42=(a28*a42);
  a33=(a36*a42);
  a28=(a28*a34);
  a34=(a03*a28);
  a33=(a33+a34);
  a33=(a33*a21);
  a21=(a11*a42);
  a01=(a01+a01);
  a21=(a21-a01);
  a21=(a21*a30);
  a33=(a33+a21);
  a12=(a12+a12);
  a11=(a11*a28);
  a12=(a12+a11);
  a12=(a12*a43);
  a33=(a33-a12);
  a36=(a36*a28);
  a03=(a03*a42);
  a36=(a36-a03);
  a36=(a36*a20);
  a33=(a33+a36);
  a36=(a00*a42);
  a20=(a02*a28);
  a36=(a36+a20);
  a36=(a36*a10);
  a33=(a33+a36);
  a00=(a00*a28);
  a02=(a02*a42);
  a00=(a00-a02);
  a00=(a00*a31);
  a33=(a33-a00);
  a05=(a05*a42);
  a06=(a06*a28);
  a05=(a05-a06);
  a05=(a05*a16);
  a33=(a33-a05);
  if (res[0]!=0) res[0][24]=a33;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_e_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_cost_y_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
