/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {9, 1, 1};
static const casadi_int casadi_s5[3] = {30, 1, 1};

/* quadrotor_ode_cost_y_fun:(i0[13],i1[6],i2[0],i3[],i4[9])->(o0[30]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46;
  a00=arg[0]? arg[0][0] : 0;
  a01=arg[4]? arg[4][0] : 0;
  a00=(a00-a01);
  a01=casadi_sq(a00);
  a02=arg[0]? arg[0][1] : 0;
  a03=arg[4]? arg[4][1] : 0;
  a02=(a02-a03);
  a03=casadi_sq(a02);
  a01=(a01+a03);
  a03=arg[0]? arg[0][2] : 0;
  a04=arg[4]? arg[4][2] : 0;
  a03=(a03-a04);
  a04=casadi_sq(a03);
  a01=(a01+a04);
  a01=sqrt(a01);
  if (res[0]!=0) res[0][0]=a01;
  a02=atan2(a02,a00);
  if (res[0]!=0) res[0][1]=a02;
  a03=(a03/a01);
  a03=asin(a03);
  if (res[0]!=0) res[0][2]=a03;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a03=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a03;
  a03=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a03;
  a03=arg[4]? arg[4][6] : 0;
  a01=2.;
  a02=arg[0]? arg[0][6] : 0;
  a00=arg[0]? arg[0][9] : 0;
  a04=(a02*a00);
  a05=arg[0]? arg[0][7] : 0;
  a06=arg[0]? arg[0][8] : 0;
  a07=(a05*a06);
  a04=(a04+a07);
  a04=(a01*a04);
  a08=1.;
  a09=casadi_sq(a06);
  a10=casadi_sq(a00);
  a11=(a09+a10);
  a11=(a01*a11);
  a11=(a08-a11);
  a04=atan2(a04,a11);
  a12=cos(a04);
  a13=(a02*a06);
  a14=(a00*a05);
  a13=(a13-a14);
  a13=(a01*a13);
  a13=asin(a13);
  a14=sin(a13);
  a15=(a12*a14);
  a16=(a02*a05);
  a17=(a06*a00);
  a16=(a16+a17);
  a16=(a01*a16);
  a18=casadi_sq(a05);
  a09=(a18+a09);
  a09=(a01*a09);
  a09=(a08-a09);
  a16=atan2(a16,a09);
  a19=cos(a16);
  a20=(a15*a19);
  a04=sin(a04);
  a16=sin(a16);
  a21=(a04*a16);
  a20=(a20+a21);
  a21=arg[4]? arg[4][5] : 0;
  a22=cos(a21);
  a23=arg[4]? arg[4][4] : 0;
  a24=sin(a23);
  a25=(a22*a24);
  a26=arg[4]? arg[4][3] : 0;
  a27=sin(a26);
  a28=(a25*a27);
  a21=sin(a21);
  a26=cos(a26);
  a29=(a21*a26);
  a28=(a28-a29);
  a28=(a20*a28);
  a29=(a04*a14);
  a30=(a29*a19);
  a31=(a12*a16);
  a30=(a30-a31);
  a31=(a21*a24);
  a32=(a31*a27);
  a33=(a22*a26);
  a32=(a32+a33);
  a32=(a30*a32);
  a28=(a28+a32);
  a32=cos(a13);
  a33=(a32*a19);
  a23=cos(a23);
  a34=(a23*a27);
  a34=(a33*a34);
  a28=(a28+a34);
  a25=(a25*a26);
  a34=(a21*a27);
  a25=(a25+a34);
  a25=(a20*a25);
  a31=(a31*a26);
  a27=(a22*a27);
  a31=(a31-a27);
  a31=(a30*a31);
  a25=(a25+a31);
  a26=(a23*a26);
  a26=(a33*a26);
  a25=(a25+a26);
  a28=atan2(a28,a25);
  a03=(a03-a28);
  a28=casadi_fabs(a03);
  a25=3.1415926535897931e+00;
  a26=(a28<=a25);
  a31=(a26?a03:0);
  a26=(!a26);
  a27=0.;
  a03=(a27<=a03);
  a34=6.2831853071795862e+00;
  a28=(a34-a28);
  a35=(-a28);
  a35=(a03?a35:0);
  a03=(!a03);
  a03=(a03?a28:0);
  a35=(a35+a03);
  a26=(a26?a35:0);
  a31=(a31+a26);
  if (res[0]!=0) res[0][6]=a31;
  a31=arg[4]? arg[4][7] : 0;
  a22=(a22*a23);
  a20=(a20*a22);
  a21=(a21*a23);
  a30=(a30*a21);
  a20=(a20+a30);
  a33=(a33*a24);
  a20=(a20-a33);
  a20=asin(a20);
  a31=(a31+a20);
  a20=casadi_fabs(a31);
  a33=(a20<=a25);
  a30=(a33?a31:0);
  a33=(!a33);
  a31=(a27<=a31);
  a20=(a34-a20);
  a23=(-a20);
  a23=(a31?a23:0);
  a31=(!a31);
  a31=(a31?a20:0);
  a23=(a23+a31);
  a33=(a33?a23:0);
  a30=(a30+a33);
  if (res[0]!=0) res[0][7]=a30;
  a30=arg[4]? arg[4][8] : 0;
  a15=(a15*a16);
  a33=(a04*a19);
  a15=(a15-a33);
  a15=(a15*a22);
  a29=(a29*a16);
  a33=(a12*a19);
  a29=(a29+a33);
  a29=(a29*a21);
  a15=(a15+a29);
  a29=(a32*a16);
  a29=(a29*a24);
  a15=(a15-a29);
  a12=(a12*a32);
  a12=(a12*a22);
  a04=(a04*a32);
  a04=(a04*a21);
  a12=(a12+a04);
  a14=(a14*a24);
  a12=(a12+a14);
  a15=atan2(a15,a12);
  a30=(a30-a15);
  a15=casadi_fabs(a30);
  a25=(a15<=a25);
  a12=(a25?a30:0);
  a25=(!a25);
  a27=(a27<=a30);
  a34=(a34-a15);
  a15=(-a34);
  a15=(a27?a15:0);
  a27=(!a27);
  a27=(a27?a34:0);
  a15=(a15+a27);
  a25=(a25?a15:0);
  a12=(a12+a25);
  if (res[0]!=0) res[0][8]=a12;
  a12=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][9]=a12;
  a25=arg[0]? arg[0][11] : 0;
  a15=(a19*a25);
  a13=tan(a13);
  a27=(a16*a13);
  a34=arg[0]? arg[0][12] : 0;
  a27=(a27*a34);
  a15=(a15+a27);
  if (res[0]!=0) res[0][10]=a15;
  a19=(a19*a13);
  a19=(a19*a34);
  a16=(a16*a25);
  a19=(a19-a16);
  if (res[0]!=0) res[0][11]=a19;
  a19=arg[1]? arg[1][0] : 0;
  a11=(a11*a19);
  a16=(a00*a02);
  a13=(a07-a16);
  a13=(a01*a13);
  a15=arg[1]? arg[1][1] : 0;
  a13=(a13*a15);
  a11=(a11+a13);
  a13=(a05*a00);
  a27=(a06*a02);
  a30=(a13+a27);
  a30=(a01*a30);
  a14=arg[1]? arg[1][2] : 0;
  a30=(a30*a14);
  a11=(a11+a30);
  if (res[0]!=0) res[0][12]=a11;
  a07=(a07+a16);
  a07=(a01*a07);
  a07=(a07*a19);
  a18=(a18+a10);
  a18=(a01*a18);
  a08=(a08-a18);
  a08=(a08*a15);
  a07=(a07+a08);
  a08=(a05*a02);
  a18=(a17-a08);
  a18=(a01*a18);
  a18=(a18*a14);
  a07=(a07+a18);
  if (res[0]!=0) res[0][13]=a07;
  a13=(a13-a27);
  a13=(a01*a13);
  a13=(a13*a19);
  a17=(a17+a08);
  a17=(a01*a17);
  a17=(a17*a15);
  a13=(a13+a17);
  a09=(a09*a14);
  a13=(a13+a09);
  a09=9.8066499999999994e+00;
  a13=(a13-a09);
  if (res[0]!=0) res[0][14]=a13;
  a13=6.6666666666666671e+01;
  a09=arg[1]? arg[1][3] : 0;
  a17=7.0000000000000001e-03;
  a17=(a17*a34);
  a08=(a25*a17);
  a27=1.4999999999999999e-02;
  a07=(a27*a25);
  a18=(a34*a07);
  a08=(a08-a18);
  a08=(a09-a08);
  a08=(a13*a08);
  if (res[0]!=0) res[0][15]=a08;
  a18=arg[1]? arg[1][4] : 0;
  a27=(a27*a12);
  a10=(a34*a27);
  a17=(a12*a17);
  a10=(a10-a17);
  a10=(a18-a10);
  a13=(a13*a10);
  if (res[0]!=0) res[0][16]=a13;
  a10=1.4285714285714286e+02;
  a17=arg[1]? arg[1][5] : 0;
  a07=(a12*a07);
  a27=(a25*a27);
  a07=(a07-a27);
  a07=(a17-a07);
  a10=(a10*a07);
  if (res[0]!=0) res[0][17]=a10;
  a07=(a01*a06);
  a27=(a15*a07);
  a16=(a01*a00);
  a11=(a14*a16);
  a30=(a27+a11);
  a24=5.0000000000000000e-01;
  a04=(a12*a02);
  a21=(a34*a06);
  a04=(a04+a21);
  a21=(a25*a00);
  a04=(a04-a21);
  a04=(a24*a04);
  a21=(a30*a04);
  a32=(a14*a07);
  a22=(a15*a16);
  a29=(a32-a22);
  a33=(a12*a05);
  a23=(a25*a06);
  a33=(a33+a23);
  a23=(a34*a00);
  a33=(a33+a23);
  a33=(a24*a33);
  a23=(a29*a33);
  a21=(a21-a23);
  a23=(a01*a05);
  a31=(a15*a23);
  a20=(a06+a06);
  a20=(a01*a20);
  a26=(a19*a20);
  a26=(a31-a26);
  a35=(a01*a02);
  a03=(a14*a35);
  a26=(a26+a03);
  a28=(a25*a02);
  a36=(a34*a05);
  a28=(a28-a36);
  a36=(a12*a00);
  a28=(a28+a36);
  a28=(a24*a28);
  a36=(a26*a28);
  a21=(a21+a36);
  a36=(a14*a23);
  a37=(a00+a00);
  a37=(a01*a37);
  a38=(a19*a37);
  a39=(a15*a35);
  a38=(a38+a39);
  a38=(a36-a38);
  a40=(a34*a02);
  a41=(a25*a05);
  a40=(a40+a41);
  a41=(a12*a06);
  a40=(a40-a41);
  a40=(a24*a40);
  a41=(a38*a40);
  a21=(a21+a41);
  if (res[0]!=0) res[0][18]=a21;
  a07=(a19*a07);
  a21=(a05+a05);
  a21=(a01*a21);
  a41=(a15*a21);
  a41=(a07-a41);
  a41=(a41-a03);
  a03=(a41*a04);
  a16=(a19*a16);
  a36=(a16-a36);
  a42=(a36*a33);
  a03=(a03-a42);
  a23=(a19*a23);
  a11=(a23+a11);
  a42=(a11*a28);
  a03=(a03+a42);
  a35=(a19*a35);
  a37=(a15*a37);
  a37=(a35-a37);
  a37=(a37+a32);
  a32=(a37*a40);
  a03=(a03+a32);
  if (res[0]!=0) res[0][19]=a03;
  a16=(a16+a39);
  a21=(a14*a21);
  a16=(a16-a21);
  a21=(a16*a04);
  a31=(a31-a07);
  a07=(a31*a33);
  a21=(a21-a07);
  a22=(a22-a35);
  a20=(a14*a20);
  a22=(a22-a20);
  a20=(a22*a28);
  a21=(a21+a20);
  a23=(a23+a27);
  a27=(a23*a40);
  a21=(a21+a27);
  if (res[0]!=0) res[0][20]=a21;
  a38=(a24*a38);
  a21=(a25*a38);
  a27=(a14*a40);
  a27=(a01*a27);
  a21=(a21+a27);
  a26=(a24*a26);
  a20=(a34*a26);
  a21=(a21-a20);
  a20=(a15*a28);
  a20=(a01*a20);
  a21=(a21+a20);
  a29=(a24*a29);
  a35=(a12*a29);
  a21=(a21-a35);
  a21=(a21*a04);
  a35=(a34*a38);
  a07=(a15*a40);
  a07=(a01*a07);
  a35=(a35-a07);
  a39=(a25*a26);
  a35=(a35+a39);
  a39=(a14*a28);
  a39=(a01*a39);
  a35=(a35+a39);
  a30=(a24*a30);
  a03=(a12*a30);
  a35=(a35+a03);
  a35=(a35*a33);
  a21=(a21-a35);
  a35=(a34*a30);
  a03=(a12*a38);
  a32=(a19*a28);
  a32=(a01*a32);
  a03=(a03+a32);
  a03=(a03+a32);
  a42=(a25*a29);
  a03=(a03+a42);
  a42=(a14*a33);
  a42=(a01*a42);
  a03=(a03+a42);
  a35=(a35-a03);
  a03=(a15*a04);
  a03=(a01*a03);
  a35=(a35+a03);
  a35=(a35*a28);
  a21=(a21+a35);
  a35=(a12*a26);
  a43=(a19*a40);
  a43=(a01*a43);
  a44=(a43+a43);
  a35=(a35-a44);
  a44=(a34*a29);
  a35=(a35-a44);
  a44=(a15*a33);
  a44=(a01*a44);
  a35=(a35+a44);
  a45=(a25*a30);
  a35=(a35-a45);
  a45=(a14*a04);
  a45=(a01*a45);
  a35=(a35+a45);
  a35=(a35*a40);
  a21=(a21+a35);
  a35=(a00*a26);
  a46=(a06*a38);
  a35=(a35-a46);
  a46=(a05*a29);
  a35=(a35-a46);
  a46=(a02*a30);
  a35=(a35+a46);
  a35=(a35*a08);
  a21=(a21+a35);
  a35=(a05*a38);
  a46=(a02*a26);
  a35=(a35+a46);
  a46=(a06*a29);
  a35=(a35-a46);
  a46=(a00*a30);
  a35=(a35-a46);
  a35=(a35*a13);
  a21=(a21+a35);
  a38=(a02*a38);
  a26=(a05*a26);
  a38=(a38-a26);
  a29=(a00*a29);
  a38=(a38-a29);
  a30=(a06*a30);
  a38=(a38+a30);
  a38=(a38*a10);
  a21=(a21+a38);
  if (res[0]!=0) res[0][21]=a21;
  a42=(a32+a42);
  a42=(a42-a03);
  a42=(a42-a03);
  a37=(a24*a37);
  a21=(a25*a37);
  a42=(a42+a21);
  a11=(a24*a11);
  a21=(a34*a11);
  a42=(a42-a21);
  a36=(a24*a36);
  a21=(a12*a36);
  a42=(a42-a21);
  a42=(a42*a04);
  a21=(a43-a45);
  a38=(a34*a37);
  a21=(a21+a38);
  a38=(a25*a11);
  a21=(a21+a38);
  a41=(a24*a41);
  a38=(a12*a41);
  a21=(a21+a38);
  a21=(a21*a33);
  a42=(a42-a21);
  a21=(a19*a04);
  a21=(a01*a21);
  a27=(a27+a21);
  a38=(a12*a37);
  a27=(a27-a38);
  a38=(a25*a36);
  a27=(a27-a38);
  a38=(a34*a41);
  a27=(a27+a38);
  a27=(a27*a28);
  a42=(a42+a27);
  a27=(a07+a07);
  a27=(a39-a27);
  a38=(a19*a33);
  a01=(a01*a38);
  a27=(a27-a01);
  a38=(a12*a11);
  a27=(a27+a38);
  a38=(a34*a36);
  a27=(a27-a38);
  a38=(a25*a41);
  a27=(a27-a38);
  a27=(a27*a40);
  a42=(a42+a27);
  a27=(a00*a11);
  a38=(a06*a37);
  a27=(a27-a38);
  a38=(a05*a36);
  a27=(a27-a38);
  a38=(a02*a41);
  a27=(a27+a38);
  a27=(a27*a08);
  a42=(a42+a27);
  a27=(a05*a37);
  a38=(a02*a11);
  a27=(a27+a38);
  a38=(a06*a36);
  a27=(a27-a38);
  a38=(a00*a41);
  a27=(a27-a38);
  a27=(a27*a13);
  a42=(a42+a27);
  a37=(a02*a37);
  a11=(a05*a11);
  a37=(a37-a11);
  a36=(a00*a36);
  a37=(a37-a36);
  a41=(a06*a41);
  a37=(a37+a41);
  a37=(a37*a10);
  a42=(a42+a37);
  if (res[0]!=0) res[0][22]=a42;
  a43=(a43-a44);
  a43=(a43-a45);
  a43=(a43-a45);
  a23=(a24*a23);
  a45=(a25*a23);
  a43=(a43+a45);
  a22=(a24*a22);
  a45=(a34*a22);
  a43=(a43-a45);
  a31=(a24*a31);
  a45=(a12*a31);
  a43=(a43-a45);
  a43=(a43*a04);
  a03=(a03-a32);
  a32=(a34*a23);
  a03=(a03+a32);
  a32=(a25*a22);
  a03=(a03+a32);
  a24=(a24*a16);
  a16=(a12*a24);
  a03=(a03+a16);
  a03=(a03*a33);
  a43=(a43-a03);
  a07=(a07-a39);
  a07=(a07-a39);
  a07=(a07+a01);
  a01=(a12*a23);
  a07=(a07-a01);
  a01=(a25*a31);
  a07=(a07-a01);
  a01=(a34*a24);
  a07=(a07+a01);
  a07=(a07*a28);
  a43=(a43+a07);
  a20=(a20+a21);
  a12=(a12*a22);
  a20=(a20+a12);
  a34=(a34*a31);
  a20=(a20-a34);
  a25=(a25*a24);
  a20=(a20-a25);
  a20=(a20*a40);
  a43=(a43+a20);
  a20=(a00*a22);
  a40=(a06*a23);
  a20=(a20-a40);
  a40=(a05*a31);
  a20=(a20-a40);
  a40=(a02*a24);
  a20=(a20+a40);
  a20=(a20*a08);
  a43=(a43+a20);
  a20=(a05*a23);
  a08=(a02*a22);
  a20=(a20+a08);
  a08=(a06*a31);
  a20=(a20-a08);
  a08=(a00*a24);
  a20=(a20-a08);
  a20=(a20*a13);
  a43=(a43+a20);
  a02=(a02*a23);
  a05=(a05*a22);
  a02=(a02-a05);
  a00=(a00*a31);
  a02=(a02-a00);
  a06=(a06*a24);
  a02=(a02+a06);
  a02=(a02*a10);
  a43=(a43+a02);
  if (res[0]!=0) res[0][23]=a43;
  if (res[0]!=0) res[0][24]=a19;
  if (res[0]!=0) res[0][25]=a15;
  if (res[0]!=0) res[0][26]=a14;
  if (res[0]!=0) res[0][27]=a09;
  if (res[0]!=0) res[0][28]=a18;
  if (res[0]!=0) res[0][29]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_cost_y_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
