/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[61] = 
  {13, 13, 0, 0, 0, 0, 1, 2,
  3, 9, 15, 21, 27, 33, 39, 45,
  0, 1, 2, 3, 4, 5, 7, 8,
  9, 3, 4, 5, 6, 8, 9, 3,
  4, 5, 6, 7, 9, 3, 4, 5,
  6, 7, 8, 6, 7, 8, 9, 11,
  12, 6, 7, 8, 9, 10, 12, 6,
  7, 8, 9, 10, 11};
static const casadi_int casadi_s5[29] = 
  {13, 13, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 10, 11, 12};
static const casadi_int casadi_s6[21] = 
  {13, 6, 0, 3, 6, 9, 10, 11,
  12, 3, 4, 5, 3, 4, 5, 3,
  4, 5, 10, 11, 12};

/* quadrotor_ode_impl_dae_fun_jac_x_xdot_u:(i0[13],i1[13],i2[6],i3[0],i4[],i5[0])->(o0[13],o1[13x13,45nz],o2[13x13,13nz],o3[13x6,12nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45;
  a00=arg[1]? arg[1][0] : 0;
  a01=arg[0]? arg[0][3] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[1]? arg[1][1] : 0;
  a01=arg[0]? arg[0][4] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[1]? arg[1][2] : 0;
  a01=arg[0]? arg[0][5] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][3] : 0;
  a01=1.;
  a02=2.;
  a03=arg[0]? arg[0][8] : 0;
  a04=casadi_sq(a03);
  a05=arg[0]? arg[0][9] : 0;
  a06=casadi_sq(a05);
  a07=(a04+a06);
  a07=(a02*a07);
  a07=(a01-a07);
  a08=arg[2]? arg[2][0] : 0;
  a09=(a07*a08);
  a10=arg[0]? arg[0][7] : 0;
  a11=(a10*a03);
  a12=arg[0]? arg[0][6] : 0;
  a13=(a05*a12);
  a14=(a11-a13);
  a14=(a02*a14);
  a15=arg[2]? arg[2][1] : 0;
  a16=(a14*a15);
  a09=(a09+a16);
  a16=(a10*a05);
  a17=(a03*a12);
  a18=(a16+a17);
  a18=(a02*a18);
  a19=arg[2]? arg[2][2] : 0;
  a20=(a18*a19);
  a09=(a09+a20);
  a00=(a00-a09);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][4] : 0;
  a11=(a11+a13);
  a11=(a02*a11);
  a13=(a11*a08);
  a09=casadi_sq(a10);
  a06=(a09+a06);
  a06=(a02*a06);
  a06=(a01-a06);
  a20=(a06*a15);
  a13=(a13+a20);
  a20=(a03*a05);
  a21=(a10*a12);
  a22=(a20-a21);
  a22=(a02*a22);
  a23=(a22*a19);
  a13=(a13+a23);
  a00=(a00-a13);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][5] : 0;
  a16=(a16-a17);
  a16=(a02*a16);
  a17=(a16*a08);
  a20=(a20+a21);
  a20=(a02*a20);
  a21=(a20*a15);
  a17=(a17+a21);
  a09=(a09+a04);
  a09=(a02*a09);
  a09=(a01-a09);
  a04=(a09*a19);
  a17=(a17+a04);
  a04=9.8066499999999994e+00;
  a17=(a17-a04);
  a00=(a00-a17);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[1]? arg[1][6] : 0;
  a17=5.0000000000000000e-01;
  a04=arg[0]? arg[0][10] : 0;
  a21=(a04*a10);
  a13=arg[0]? arg[0][11] : 0;
  a23=(a13*a03);
  a21=(a21+a23);
  a23=arg[0]? arg[0][12] : 0;
  a24=(a23*a05);
  a21=(a21+a24);
  a21=(a17*a21);
  a00=(a00+a21);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[1]? arg[1][7] : 0;
  a21=(a04*a12);
  a24=(a23*a03);
  a21=(a21+a24);
  a24=(a13*a05);
  a21=(a21-a24);
  a21=(a17*a21);
  a00=(a00-a21);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[1]? arg[1][8] : 0;
  a21=(a13*a12);
  a24=(a23*a10);
  a21=(a21-a24);
  a24=(a04*a05);
  a21=(a21+a24);
  a21=(a17*a21);
  a00=(a00-a21);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[1]? arg[1][9] : 0;
  a21=(a23*a12);
  a24=(a13*a10);
  a21=(a21+a24);
  a24=(a04*a03);
  a21=(a21-a24);
  a21=(a17*a21);
  a00=(a00-a21);
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[1]? arg[1][10] : 0;
  a21=6.6666666666666671e+01;
  a24=arg[2]? arg[2][3] : 0;
  a25=7.0000000000000001e-03;
  a26=(a25*a23);
  a27=(a13*a26);
  a28=1.4999999999999999e-02;
  a29=(a28*a13);
  a30=(a23*a29);
  a27=(a27-a30);
  a24=(a24+a27);
  a24=(a21*a24);
  a00=(a00-a24);
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[1]? arg[1][11] : 0;
  a24=arg[2]? arg[2][4] : 0;
  a27=(a28*a04);
  a30=(a23*a27);
  a31=(a04*a26);
  a30=(a30-a31);
  a24=(a24+a30);
  a24=(a21*a24);
  a00=(a00-a24);
  if (res[0]!=0) res[0][11]=a00;
  a00=arg[1]? arg[1][12] : 0;
  a24=1.4285714285714286e+02;
  a30=arg[2]? arg[2][5] : 0;
  a31=(a04*a29);
  a32=(a13*a27);
  a31=(a31-a32);
  a30=(a30+a31);
  a24=(a24*a30);
  a00=(a00-a24);
  if (res[0]!=0) res[0][12]=a00;
  a00=-1.;
  if (res[1]!=0) res[1][0]=a00;
  if (res[1]!=0) res[1][1]=a00;
  if (res[1]!=0) res[1][2]=a00;
  a00=(a02*a03);
  a24=(a19*a00);
  a30=(a02*a05);
  a31=(a15*a30);
  a32=(a24-a31);
  a32=(-a32);
  if (res[1]!=0) res[1][3]=a32;
  a32=(a08*a30);
  a33=(a02*a10);
  a34=(a19*a33);
  a35=(a32-a34);
  a35=(-a35);
  if (res[1]!=0) res[1][4]=a35;
  a35=(a15*a33);
  a36=(a08*a00);
  a37=(a35-a36);
  a37=(-a37);
  if (res[1]!=0) res[1][5]=a37;
  a37=(a17*a04);
  a38=(-a37);
  if (res[1]!=0) res[1][6]=a38;
  a39=(a17*a13);
  a40=(-a39);
  if (res[1]!=0) res[1][7]=a40;
  a41=(a17*a23);
  a42=(-a41);
  if (res[1]!=0) res[1][8]=a42;
  a00=(a15*a00);
  a30=(a19*a30);
  a43=(a00+a30);
  a43=(-a43);
  if (res[1]!=0) res[1][9]=a43;
  a43=(a10+a10);
  a43=(a02*a43);
  a44=(a15*a43);
  a36=(a36-a44);
  a44=(a02*a12);
  a45=(a19*a44);
  a36=(a36-a45);
  a36=(-a36);
  if (res[1]!=0) res[1][10]=a36;
  a36=(a15*a44);
  a32=(a32+a36);
  a43=(a19*a43);
  a32=(a32-a43);
  a32=(-a32);
  if (res[1]!=0) res[1][11]=a32;
  if (res[1]!=0) res[1][12]=a37;
  if (res[1]!=0) res[1][13]=a41;
  if (res[1]!=0) res[1][14]=a40;
  a40=(a03+a03);
  a40=(a02*a40);
  a32=(a08*a40);
  a35=(a35-a32);
  a35=(a35+a45);
  a35=(-a35);
  if (res[1]!=0) res[1][15]=a35;
  a33=(a08*a33);
  a30=(a33+a30);
  a30=(-a30);
  if (res[1]!=0) res[1][16]=a30;
  a44=(a08*a44);
  a31=(a31-a44);
  a19=(a19*a40);
  a31=(a31-a19);
  a31=(-a31);
  if (res[1]!=0) res[1][17]=a31;
  if (res[1]!=0) res[1][18]=a39;
  if (res[1]!=0) res[1][19]=a42;
  if (res[1]!=0) res[1][20]=a37;
  a37=(a05+a05);
  a02=(a02*a37);
  a08=(a08*a02);
  a08=(a08+a36);
  a34=(a34-a08);
  a34=(-a34);
  if (res[1]!=0) res[1][21]=a34;
  a15=(a15*a02);
  a44=(a44-a15);
  a44=(a44+a24);
  a44=(-a44);
  if (res[1]!=0) res[1][22]=a44;
  a33=(a33+a00);
  a33=(-a33);
  if (res[1]!=0) res[1][23]=a33;
  if (res[1]!=0) res[1][24]=a41;
  if (res[1]!=0) res[1][25]=a39;
  if (res[1]!=0) res[1][26]=a38;
  a10=(a17*a10);
  if (res[1]!=0) res[1][27]=a10;
  a12=(a17*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][28]=a12;
  a05=(a17*a05);
  a38=(-a05);
  if (res[1]!=0) res[1][29]=a38;
  a17=(a17*a03);
  if (res[1]!=0) res[1][30]=a17;
  a28=(a28*a23);
  a23=(a28-a26);
  a23=(a21*a23);
  a23=(-a23);
  if (res[1]!=0) res[1][31]=a23;
  a23=0.;
  if (res[1]!=0) res[1][32]=a23;
  if (res[1]!=0) res[1][33]=a17;
  if (res[1]!=0) res[1][34]=a05;
  if (res[1]!=0) res[1][35]=a12;
  a03=(-a10);
  if (res[1]!=0) res[1][36]=a03;
  a26=(a26-a28);
  a26=(a21*a26);
  a26=(-a26);
  if (res[1]!=0) res[1][37]=a26;
  if (res[1]!=0) res[1][38]=a23;
  if (res[1]!=0) res[1][39]=a05;
  a17=(-a17);
  if (res[1]!=0) res[1][40]=a17;
  if (res[1]!=0) res[1][41]=a10;
  if (res[1]!=0) res[1][42]=a12;
  a13=(a25*a13);
  a13=(a13-a29);
  a13=(a21*a13);
  a13=(-a13);
  if (res[1]!=0) res[1][43]=a13;
  a25=(a25*a04);
  a27=(a27-a25);
  a21=(a21*a27);
  a21=(-a21);
  if (res[1]!=0) res[1][44]=a21;
  if (res[2]!=0) res[2][0]=a01;
  if (res[2]!=0) res[2][1]=a01;
  if (res[2]!=0) res[2][2]=a01;
  if (res[2]!=0) res[2][3]=a01;
  if (res[2]!=0) res[2][4]=a01;
  if (res[2]!=0) res[2][5]=a01;
  if (res[2]!=0) res[2][6]=a01;
  if (res[2]!=0) res[2][7]=a01;
  if (res[2]!=0) res[2][8]=a01;
  if (res[2]!=0) res[2][9]=a01;
  if (res[2]!=0) res[2][10]=a01;
  if (res[2]!=0) res[2][11]=a01;
  if (res[2]!=0) res[2][12]=a01;
  a07=(-a07);
  if (res[3]!=0) res[3][0]=a07;
  a11=(-a11);
  if (res[3]!=0) res[3][1]=a11;
  a16=(-a16);
  if (res[3]!=0) res[3][2]=a16;
  a14=(-a14);
  if (res[3]!=0) res[3][3]=a14;
  a06=(-a06);
  if (res[3]!=0) res[3][4]=a06;
  a20=(-a20);
  if (res[3]!=0) res[3][5]=a20;
  a18=(-a18);
  if (res[3]!=0) res[3][6]=a18;
  a22=(-a22);
  if (res[3]!=0) res[3][7]=a22;
  a09=(-a09);
  if (res[3]!=0) res[3][8]=a09;
  a09=-6.6666666666666671e+01;
  if (res[3]!=0) res[3][9]=a09;
  if (res[3]!=0) res[3][10]=a09;
  a09=-1.4285714285714286e+02;
  if (res[3]!=0) res[3][11]=a09;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_fun_jac_x_xdot_u_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
