/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[61] = 
  {13, 13, 0, 0, 0, 0, 1, 2,
  3, 9, 15, 21, 27, 33, 39, 45,
  0, 1, 2, 3, 4, 5, 7, 8,
  9, 3, 4, 5, 6, 8, 9, 3,
  4, 5, 6, 7, 9, 3, 4, 5,
  6, 7, 8, 6, 7, 8, 9, 11,
  12, 6, 7, 8, 9, 10, 12, 6,
  7, 8, 9, 10, 11};
static const casadi_int casadi_s5[29] = 
  {13, 13, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 10, 11, 12};
static const casadi_int casadi_s6[21] = 
  {13, 6, 0, 3, 6, 9, 10, 11,
  12, 3, 4, 5, 3, 4, 5, 3,
  4, 5, 10, 11, 12};
static const casadi_int casadi_s7[3] = {13, 0, 1};

/* quadrotor_ode_impl_dae_jac_x_xdot_u_z:(i0[13],i1[13],i2[6],i3[0],i4[],i5[0])->(o0[13x13,45nz],o1[13x13,13nz],o2[13x6,12nz],o3[13x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29;
  a00=-1.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[2]? arg[2][2] : 0;
  a01=2.;
  a02=arg[0]? arg[0][8] : 0;
  a03=(a01*a02);
  a04=(a00*a03);
  a05=arg[2]? arg[2][1] : 0;
  a06=arg[0]? arg[0][9] : 0;
  a07=(a01*a06);
  a08=(a05*a07);
  a09=(a04-a08);
  a09=(-a09);
  if (res[0]!=0) res[0][3]=a09;
  a09=arg[2]? arg[2][0] : 0;
  a10=(a09*a07);
  a11=arg[0]? arg[0][7] : 0;
  a12=(a01*a11);
  a13=(a00*a12);
  a14=(a10-a13);
  a14=(-a14);
  if (res[0]!=0) res[0][4]=a14;
  a14=(a05*a12);
  a15=(a09*a03);
  a16=(a14-a15);
  a16=(-a16);
  if (res[0]!=0) res[0][5]=a16;
  a16=5.0000000000000000e-01;
  a17=arg[0]? arg[0][10] : 0;
  a18=(a16*a17);
  a19=(-a18);
  if (res[0]!=0) res[0][6]=a19;
  a20=arg[0]? arg[0][11] : 0;
  a21=(a16*a20);
  a22=(-a21);
  if (res[0]!=0) res[0][7]=a22;
  a23=arg[0]? arg[0][12] : 0;
  a24=(a16*a23);
  a25=(-a24);
  if (res[0]!=0) res[0][8]=a25;
  a03=(a05*a03);
  a07=(a00*a07);
  a26=(a03+a07);
  a26=(-a26);
  if (res[0]!=0) res[0][9]=a26;
  a26=(a11+a11);
  a26=(a01*a26);
  a27=(a05*a26);
  a15=(a15-a27);
  a27=arg[0]? arg[0][6] : 0;
  a28=(a01*a27);
  a29=(a00*a28);
  a15=(a15-a29);
  a15=(-a15);
  if (res[0]!=0) res[0][10]=a15;
  a15=(a05*a28);
  a10=(a10+a15);
  a26=(a00*a26);
  a10=(a10-a26);
  a10=(-a10);
  if (res[0]!=0) res[0][11]=a10;
  if (res[0]!=0) res[0][12]=a18;
  if (res[0]!=0) res[0][13]=a24;
  if (res[0]!=0) res[0][14]=a22;
  a22=(a02+a02);
  a22=(a01*a22);
  a10=(a09*a22);
  a14=(a14-a10);
  a14=(a14+a29);
  a14=(-a14);
  if (res[0]!=0) res[0][15]=a14;
  a12=(a09*a12);
  a07=(a12+a07);
  a07=(-a07);
  if (res[0]!=0) res[0][16]=a07;
  a28=(a09*a28);
  a08=(a08-a28);
  a00=(a00*a22);
  a08=(a08-a00);
  a08=(-a08);
  if (res[0]!=0) res[0][17]=a08;
  if (res[0]!=0) res[0][18]=a21;
  if (res[0]!=0) res[0][19]=a25;
  if (res[0]!=0) res[0][20]=a18;
  a18=(a06+a06);
  a18=(a01*a18);
  a09=(a09*a18);
  a09=(a09+a15);
  a13=(a13-a09);
  a13=(-a13);
  if (res[0]!=0) res[0][21]=a13;
  a05=(a05*a18);
  a28=(a28-a05);
  a28=(a28+a04);
  a28=(-a28);
  if (res[0]!=0) res[0][22]=a28;
  a12=(a12+a03);
  a12=(-a12);
  if (res[0]!=0) res[0][23]=a12;
  if (res[0]!=0) res[0][24]=a24;
  if (res[0]!=0) res[0][25]=a21;
  if (res[0]!=0) res[0][26]=a19;
  a19=(a16*a11);
  if (res[0]!=0) res[0][27]=a19;
  a21=(a16*a27);
  a21=(-a21);
  if (res[0]!=0) res[0][28]=a21;
  a24=(a16*a06);
  a12=(-a24);
  if (res[0]!=0) res[0][29]=a12;
  a16=(a16*a02);
  if (res[0]!=0) res[0][30]=a16;
  a12=6.6666666666666671e+01;
  a03=1.4999999999999999e-02;
  a28=(a03*a23);
  a04=7.0000000000000001e-03;
  a23=(a04*a23);
  a05=(a28-a23);
  a05=(a12*a05);
  a05=(-a05);
  if (res[0]!=0) res[0][31]=a05;
  a05=0.;
  if (res[0]!=0) res[0][32]=a05;
  if (res[0]!=0) res[0][33]=a16;
  if (res[0]!=0) res[0][34]=a24;
  if (res[0]!=0) res[0][35]=a21;
  a18=(-a19);
  if (res[0]!=0) res[0][36]=a18;
  a23=(a23-a28);
  a23=(a12*a23);
  a23=(-a23);
  if (res[0]!=0) res[0][37]=a23;
  if (res[0]!=0) res[0][38]=a05;
  if (res[0]!=0) res[0][39]=a24;
  a16=(-a16);
  if (res[0]!=0) res[0][40]=a16;
  if (res[0]!=0) res[0][41]=a19;
  if (res[0]!=0) res[0][42]=a21;
  a21=(a04*a20);
  a20=(a03*a20);
  a21=(a21-a20);
  a21=(a12*a21);
  a21=(-a21);
  if (res[0]!=0) res[0][43]=a21;
  a03=(a03*a17);
  a04=(a04*a17);
  a03=(a03-a04);
  a12=(a12*a03);
  a12=(-a12);
  if (res[0]!=0) res[0][44]=a12;
  a12=1.;
  if (res[1]!=0) res[1][0]=a12;
  if (res[1]!=0) res[1][1]=a12;
  if (res[1]!=0) res[1][2]=a12;
  if (res[1]!=0) res[1][3]=a12;
  if (res[1]!=0) res[1][4]=a12;
  if (res[1]!=0) res[1][5]=a12;
  if (res[1]!=0) res[1][6]=a12;
  if (res[1]!=0) res[1][7]=a12;
  if (res[1]!=0) res[1][8]=a12;
  if (res[1]!=0) res[1][9]=a12;
  if (res[1]!=0) res[1][10]=a12;
  if (res[1]!=0) res[1][11]=a12;
  if (res[1]!=0) res[1][12]=a12;
  a03=casadi_sq(a02);
  a04=casadi_sq(a06);
  a17=(a03+a04);
  a17=(a01*a17);
  a17=(a12-a17);
  a17=(-a17);
  if (res[2]!=0) res[2][0]=a17;
  a17=(a11*a02);
  a21=(a06*a27);
  a20=(a17+a21);
  a20=(a01*a20);
  a20=(-a20);
  if (res[2]!=0) res[2][1]=a20;
  a20=(a11*a06);
  a19=(a02*a27);
  a16=(a20-a19);
  a16=(a01*a16);
  a16=(-a16);
  if (res[2]!=0) res[2][2]=a16;
  a17=(a17-a21);
  a17=(a01*a17);
  a17=(-a17);
  if (res[2]!=0) res[2][3]=a17;
  a17=casadi_sq(a11);
  a04=(a17+a04);
  a04=(a01*a04);
  a04=(a12-a04);
  a04=(-a04);
  if (res[2]!=0) res[2][4]=a04;
  a02=(a02*a06);
  a11=(a11*a27);
  a27=(a02+a11);
  a27=(a01*a27);
  a27=(-a27);
  if (res[2]!=0) res[2][5]=a27;
  a20=(a20+a19);
  a20=(a01*a20);
  a20=(-a20);
  if (res[2]!=0) res[2][6]=a20;
  a02=(a02-a11);
  a02=(a01*a02);
  a02=(-a02);
  if (res[2]!=0) res[2][7]=a02;
  a17=(a17+a03);
  a01=(a01*a17);
  a12=(a12-a01);
  a12=(-a12);
  if (res[2]!=0) res[2][8]=a12;
  a12=-6.6666666666666671e+01;
  if (res[2]!=0) res[2][9]=a12;
  if (res[2]!=0) res[2][10]=a12;
  a12=-1.4285714285714286e+02;
  if (res[2]!=0) res[2][11]=a12;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_impl_dae_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
