/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {19, 1, 1};

/* quadrotor_ode_expl_vde_adj:(i0[13],i1[13],i2[6],i3[6])->(o0[19]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[0]? arg[0][12] : 0;
  a01=5.0000000000000000e-01;
  a02=arg[1]? arg[1][9] : 0;
  a02=(a01*a02);
  a03=(a00*a02);
  a04=arg[0]? arg[0][11] : 0;
  a05=arg[1]? arg[1][8] : 0;
  a05=(a01*a05);
  a06=(a04*a05);
  a03=(a03+a06);
  a06=arg[0]? arg[0][10] : 0;
  a07=arg[1]? arg[1][7] : 0;
  a07=(a01*a07);
  a08=(a06*a07);
  a03=(a03+a08);
  a08=arg[0]? arg[0][7] : 0;
  a09=2.;
  a10=arg[2]? arg[2][1] : 0;
  a11=arg[1]? arg[1][5] : 0;
  a12=(a10*a11);
  a12=(a09*a12);
  a13=(a08*a12);
  a03=(a03+a13);
  a13=arg[0]? arg[0][8] : 0;
  a14=arg[2]? arg[2][0] : 0;
  a15=(a14*a11);
  a15=(a09*a15);
  a16=(a13*a15);
  a03=(a03-a16);
  a16=arg[2]? arg[2][2] : 0;
  a17=arg[1]? arg[1][4] : 0;
  a18=(a16*a17);
  a18=(a09*a18);
  a19=(a08*a18);
  a03=(a03-a19);
  a19=arg[0]? arg[0][9] : 0;
  a20=(a14*a17);
  a20=(a09*a20);
  a21=(a19*a20);
  a03=(a03+a21);
  a21=arg[1]? arg[1][3] : 0;
  a22=(a16*a21);
  a22=(a09*a22);
  a23=(a13*a22);
  a03=(a03+a23);
  a23=(a10*a21);
  a23=(a09*a23);
  a24=(a19*a23);
  a03=(a03-a24);
  if (res[0]!=0) res[0][6]=a03;
  a03=(a04*a02);
  a24=(a00*a05);
  a03=(a03-a24);
  a24=arg[1]? arg[1][6] : 0;
  a01=(a01*a24);
  a24=(a06*a01);
  a03=(a03-a24);
  a24=(a08+a08);
  a16=(a16*a11);
  a16=(a09*a16);
  a25=(a24*a16);
  a03=(a03-a25);
  a25=arg[0]? arg[0][6] : 0;
  a26=(a25*a12);
  a03=(a03+a26);
  a26=(a19*a15);
  a03=(a03+a26);
  a26=(a25*a18);
  a03=(a03-a26);
  a10=(a10*a17);
  a10=(a09*a10);
  a24=(a24*a10);
  a03=(a03-a24);
  a24=(a13*a20);
  a03=(a03+a24);
  a24=(a19*a22);
  a03=(a03+a24);
  a24=(a13*a23);
  a03=(a03+a24);
  if (res[0]!=0) res[0][7]=a03;
  a03=(a00*a07);
  a24=(a06*a02);
  a03=(a03-a24);
  a24=(a04*a01);
  a03=(a03-a24);
  a24=(a13+a13);
  a16=(a24*a16);
  a03=(a03-a16);
  a16=(a19*a12);
  a03=(a03+a16);
  a16=(a25*a15);
  a03=(a03-a16);
  a16=(a19*a18);
  a03=(a03+a16);
  a16=(a08*a20);
  a03=(a03+a16);
  a16=(a25*a22);
  a03=(a03+a16);
  a16=(a08*a23);
  a03=(a03+a16);
  a14=(a14*a21);
  a14=(a09*a14);
  a24=(a24*a14);
  a03=(a03-a24);
  if (res[0]!=0) res[0][8]=a03;
  a03=(a06*a05);
  a24=(a04*a07);
  a03=(a03-a24);
  a24=(a00*a01);
  a03=(a03-a24);
  a12=(a13*a12);
  a03=(a03+a12);
  a15=(a08*a15);
  a03=(a03+a15);
  a18=(a13*a18);
  a03=(a03+a18);
  a18=(a19+a19);
  a10=(a18*a10);
  a03=(a03-a10);
  a20=(a25*a20);
  a03=(a03+a20);
  a22=(a08*a22);
  a03=(a03+a22);
  a23=(a25*a23);
  a03=(a03-a23);
  a18=(a18*a14);
  a03=(a03-a18);
  if (res[0]!=0) res[0][9]=a03;
  a03=7.0000000000000001e-03;
  a18=(a03*a00);
  a14=6.6666666666666671e+01;
  a23=arg[1]? arg[1][11] : 0;
  a23=(a14*a23);
  a22=(a18*a23);
  a20=1.4999999999999999e-02;
  a10=(a20*a04);
  a15=1.4285714285714286e+02;
  a12=arg[1]? arg[1][12] : 0;
  a15=(a15*a12);
  a12=(a10*a15);
  a22=(a22-a12);
  a12=(a04*a15);
  a24=(a00*a23);
  a12=(a12-a24);
  a12=(a20*a12);
  a22=(a22+a12);
  a12=(a13*a02);
  a22=(a22-a12);
  a12=(a19*a05);
  a22=(a22+a12);
  a12=(a25*a07);
  a22=(a22+a12);
  a12=(a08*a01);
  a22=(a22-a12);
  if (res[0]!=0) res[0][10]=a22;
  a22=(a20*a06);
  a12=(a22*a15);
  a24=arg[1]? arg[1][10] : 0;
  a14=(a14*a24);
  a00=(a00*a14);
  a24=(a06*a15);
  a00=(a00-a24);
  a20=(a20*a00);
  a12=(a12+a20);
  a18=(a18*a14);
  a12=(a12-a18);
  a18=(a08*a02);
  a12=(a12+a18);
  a18=(a25*a05);
  a12=(a12+a18);
  a18=(a19*a07);
  a12=(a12-a18);
  a18=(a13*a01);
  a12=(a12-a18);
  if (res[0]!=0) res[0][11]=a12;
  a10=(a10*a14);
  a22=(a22*a23);
  a10=(a10-a22);
  a06=(a06*a23);
  a04=(a04*a14);
  a06=(a06-a04);
  a03=(a03*a06);
  a10=(a10+a03);
  a02=(a25*a02);
  a10=(a10+a02);
  a05=(a08*a05);
  a10=(a10-a05);
  a07=(a13*a07);
  a10=(a10+a07);
  a01=(a19*a01);
  a10=(a10-a01);
  if (res[0]!=0) res[0][12]=a10;
  a10=(a08*a19);
  a01=(a13*a25);
  a07=(a10-a01);
  a07=(a09*a07);
  a07=(a07*a11);
  a05=(a08*a13);
  a02=(a19*a25);
  a03=(a05+a02);
  a03=(a09*a03);
  a03=(a03*a17);
  a07=(a07+a03);
  a03=1.;
  a06=casadi_sq(a13);
  a04=casadi_sq(a19);
  a22=(a06+a04);
  a22=(a09*a22);
  a22=(a03-a22);
  a22=(a22*a21);
  a07=(a07+a22);
  if (res[0]!=0) res[0][13]=a07;
  a13=(a13*a19);
  a25=(a08*a25);
  a19=(a13+a25);
  a19=(a09*a19);
  a19=(a19*a11);
  a08=casadi_sq(a08);
  a04=(a08+a04);
  a04=(a09*a04);
  a04=(a03-a04);
  a04=(a04*a17);
  a19=(a19+a04);
  a05=(a05-a02);
  a05=(a09*a05);
  a05=(a05*a21);
  a19=(a19+a05);
  if (res[0]!=0) res[0][14]=a19;
  a08=(a08+a06);
  a08=(a09*a08);
  a03=(a03-a08);
  a03=(a03*a11);
  a13=(a13-a25);
  a13=(a09*a13);
  a13=(a13*a17);
  a03=(a03+a13);
  a10=(a10+a01);
  a09=(a09*a10);
  a09=(a09*a21);
  a03=(a03+a09);
  if (res[0]!=0) res[0][15]=a03;
  if (res[0]!=0) res[0][16]=a14;
  if (res[0]!=0) res[0][17]=a23;
  if (res[0]!=0) res[0][18]=a15;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
