/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {9, 1, 1};
static const casadi_int casadi_s5[3] = {29, 1, 1};

/* quadrotor_ode_cost_y_fun:(i0[13],i1[4],i2[0],i3[],i4[9])->(o0[29]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51;
  a00=arg[0]? arg[0][0] : 0;
  a01=arg[4]? arg[4][0] : 0;
  a00=(a00-a01);
  a01=casadi_sq(a00);
  a02=arg[0]? arg[0][1] : 0;
  a03=arg[4]? arg[4][1] : 0;
  a02=(a02-a03);
  a03=casadi_sq(a02);
  a01=(a01+a03);
  a03=arg[0]? arg[0][2] : 0;
  a04=arg[4]? arg[4][2] : 0;
  a03=(a03-a04);
  a04=casadi_sq(a03);
  a01=(a01+a04);
  a01=sqrt(a01);
  if (res[0]!=0) res[0][0]=a01;
  a02=atan2(a02,a00);
  if (res[0]!=0) res[0][1]=a02;
  a03=(a03/a01);
  a03=asin(a03);
  if (res[0]!=0) res[0][2]=a03;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a03=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a03;
  a03=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a03;
  a03=0.;
  a01=arg[4]? arg[4][8] : 0;
  a02=cos(a01);
  a00=arg[4]? arg[4][7] : 0;
  a04=cos(a00);
  a05=(a02*a04);
  a06=2.;
  a07=arg[0]? arg[0][6] : 0;
  a08=arg[0]? arg[0][9] : 0;
  a09=(a07*a08);
  a10=arg[0]? arg[0][7] : 0;
  a11=arg[0]? arg[0][8] : 0;
  a12=(a10*a11);
  a09=(a09+a12);
  a09=(a06*a09);
  a12=1.;
  a13=casadi_sq(a11);
  a14=casadi_sq(a08);
  a14=(a13+a14);
  a14=(a06*a14);
  a14=(a12-a14);
  a09=atan2(a09,a14);
  a14=cos(a09);
  a15=(a07*a11);
  a16=(a08*a10);
  a15=(a15-a16);
  a15=(a06*a15);
  a15=asin(a15);
  a16=cos(a15);
  a17=(a14*a16);
  a18=arg[4]? arg[4][5] : 0;
  a19=cos(a18);
  a20=arg[4]? arg[4][4] : 0;
  a21=cos(a20);
  a22=(a19*a21);
  a23=(a17*a22);
  a09=sin(a09);
  a24=(a09*a16);
  a18=sin(a18);
  a25=(a18*a21);
  a26=(a24*a25);
  a23=(a23+a26);
  a26=sin(a15);
  a20=sin(a20);
  a27=(a26*a20);
  a23=(a23+a27);
  a27=(a05*a23);
  a01=sin(a01);
  a28=(a01*a04);
  a29=(a14*a26);
  a30=(a07*a10);
  a31=(a11*a08);
  a30=(a30+a31);
  a30=(a06*a30);
  a32=casadi_sq(a10);
  a32=(a32+a13);
  a32=(a06*a32);
  a32=(a12-a32);
  a30=atan2(a30,a32);
  a13=sin(a30);
  a33=(a29*a13);
  a30=cos(a30);
  a34=(a09*a30);
  a33=(a33-a34);
  a34=(a33*a22);
  a35=(a09*a26);
  a36=(a35*a13);
  a37=(a14*a30);
  a36=(a36+a37);
  a37=(a36*a25);
  a34=(a34+a37);
  a37=(a16*a13);
  a38=(a37*a20);
  a34=(a34-a38);
  a38=(a28*a34);
  a27=(a27+a38);
  a00=sin(a00);
  a29=(a29*a30);
  a09=(a09*a13);
  a29=(a29+a09);
  a22=(a29*a22);
  a35=(a35*a30);
  a14=(a14*a13);
  a35=(a35-a14);
  a25=(a35*a25);
  a22=(a22+a25);
  a16=(a16*a30);
  a25=(a16*a20);
  a22=(a22-a25);
  a25=(a00*a22);
  a27=(a27-a25);
  a25=(a02*a00);
  a14=arg[4]? arg[4][6] : 0;
  a09=sin(a14);
  a38=(a25*a09);
  a14=cos(a14);
  a39=(a01*a14);
  a38=(a38-a39);
  a39=(a19*a20);
  a40=arg[4]? arg[4][3] : 0;
  a41=sin(a40);
  a42=(a39*a41);
  a40=cos(a40);
  a43=(a18*a40);
  a42=(a42-a43);
  a43=(a17*a42);
  a20=(a18*a20);
  a44=(a20*a41);
  a45=(a19*a40);
  a44=(a44+a45);
  a45=(a24*a44);
  a43=(a43+a45);
  a45=(a21*a41);
  a46=(a26*a45);
  a43=(a43-a46);
  a46=(a38*a43);
  a47=(a01*a00);
  a48=(a47*a09);
  a49=(a02*a14);
  a48=(a48+a49);
  a49=(a33*a42);
  a50=(a36*a44);
  a49=(a49+a50);
  a50=(a37*a45);
  a49=(a49+a50);
  a50=(a48*a49);
  a46=(a46+a50);
  a50=(a04*a09);
  a42=(a29*a42);
  a44=(a35*a44);
  a42=(a42+a44);
  a45=(a16*a45);
  a42=(a42+a45);
  a45=(a50*a42);
  a46=(a46+a45);
  a45=(a27+a46);
  a25=(a25*a14);
  a01=(a01*a09);
  a25=(a25+a01);
  a39=(a39*a40);
  a18=(a18*a41);
  a39=(a39+a18);
  a17=(a17*a39);
  a20=(a20*a40);
  a19=(a19*a41);
  a20=(a20-a19);
  a24=(a24*a20);
  a17=(a17+a24);
  a21=(a21*a40);
  a26=(a26*a21);
  a17=(a17-a26);
  a26=(a25*a17);
  a47=(a47*a14);
  a02=(a02*a09);
  a47=(a47-a02);
  a33=(a33*a39);
  a36=(a36*a20);
  a33=(a33+a36);
  a37=(a37*a21);
  a33=(a33+a37);
  a37=(a47*a33);
  a26=(a26+a37);
  a04=(a04*a14);
  a29=(a29*a39);
  a35=(a35*a20);
  a29=(a29+a35);
  a16=(a16*a21);
  a29=(a29+a16);
  a16=(a04*a29);
  a26=(a26+a16);
  a45=(a45+a26);
  a03=(a03<a45);
  a16=2.5000000000000000e-01;
  a45=(a45+a12);
  a45=sqrt(a45);
  a45=(a06*a45);
  a21=(a16*a45);
  a21=(a03?a21:0);
  a35=(!a03);
  a20=(a46<a27);
  a39=(a26<a27);
  a20=(a20&&a39);
  a39=(a25*a43);
  a14=(a47*a49);
  a39=(a39+a14);
  a14=(a04*a42);
  a39=(a39+a14);
  a14=(a38*a17);
  a37=(a48*a33);
  a14=(a14+a37);
  a37=(a50*a29);
  a14=(a14+a37);
  a37=(a39-a14);
  a36=(a12+a27);
  a36=(a36-a46);
  a36=(a36-a26);
  a36=sqrt(a36);
  a36=(a06*a36);
  a02=(a37/a36);
  a02=(a20?a02:0);
  a09=(!a20);
  a40=(a26<a46);
  a17=(a05*a17);
  a33=(a28*a33);
  a17=(a17+a33);
  a29=(a00*a29);
  a17=(a17-a29);
  a25=(a25*a23);
  a47=(a47*a34);
  a25=(a25+a47);
  a04=(a04*a22);
  a25=(a25+a04);
  a04=(a17-a25);
  a47=(a12+a46);
  a47=(a47-a27);
  a47=(a47-a26);
  a47=sqrt(a47);
  a47=(a06*a47);
  a29=(a04/a47);
  a29=(a40?a29:0);
  a33=(!a40);
  a38=(a38*a23);
  a48=(a48*a34);
  a38=(a38+a48);
  a50=(a50*a22);
  a38=(a38+a50);
  a05=(a05*a43);
  a28=(a28*a49);
  a05=(a05+a28);
  a00=(a00*a42);
  a05=(a05-a00);
  a00=(a38-a05);
  a12=(a12+a26);
  a12=(a12-a27);
  a12=(a12-a46);
  a12=sqrt(a12);
  a12=(a06*a12);
  a46=(a00/a12);
  a46=(a33?a46:0);
  a29=(a29+a46);
  a29=(a09?a29:0);
  a02=(a02+a29);
  a02=(a35?a02:0);
  a21=(a21+a02);
  a02=casadi_sq(a21);
  a37=(a37/a45);
  a37=(a03?a37:0);
  a29=(a16*a36);
  a29=(a20?a29:0);
  a05=(a05+a38);
  a38=(a05/a47);
  a38=(a40?a38:0);
  a17=(a17+a25);
  a25=(a17/a12);
  a25=(a33?a25:0);
  a38=(a38+a25);
  a38=(a09?a38:0);
  a29=(a29+a38);
  a29=(a35?a29:0);
  a37=(a37+a29);
  a29=casadi_sq(a37);
  a02=(a02+a29);
  a04=(a04/a45);
  a04=(a03?a04:0);
  a05=(a05/a36);
  a05=(a20?a05:0);
  a29=(a16*a47);
  a29=(a40?a29:0);
  a14=(a14+a39);
  a39=(a14/a12);
  a39=(a33?a39:0);
  a29=(a29+a39);
  a29=(a09?a29:0);
  a05=(a05+a29);
  a05=(a35?a05:0);
  a04=(a04+a05);
  a05=casadi_sq(a04);
  a02=(a02+a05);
  a00=(a00/a45);
  a03=(a03?a00:0);
  a17=(a17/a36);
  a20=(a20?a17:0);
  a14=(a14/a47);
  a40=(a40?a14:0);
  a16=(a16*a12);
  a33=(a33?a16:0);
  a40=(a40+a33);
  a09=(a09?a40:0);
  a20=(a20+a09);
  a35=(a35?a20:0);
  a03=(a03+a35);
  a35=casadi_sq(a03);
  a02=(a02+a35);
  a02=sqrt(a02);
  a21=(a21/a02);
  if (res[0]!=0) res[0][6]=a21;
  a37=(a37/a02);
  if (res[0]!=0) res[0][7]=a37;
  a04=(a04/a02);
  if (res[0]!=0) res[0][8]=a04;
  a03=(a03/a02);
  if (res[0]!=0) res[0][9]=a03;
  a03=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][10]=a03;
  a02=arg[0]? arg[0][11] : 0;
  a04=(a30*a02);
  a15=tan(a15);
  a37=(a13*a15);
  a21=arg[0]? arg[0][12] : 0;
  a37=(a37*a21);
  a04=(a04+a37);
  if (res[0]!=0) res[0][11]=a04;
  a30=(a30*a15);
  a30=(a30*a21);
  a13=(a13*a02);
  a30=(a30-a13);
  if (res[0]!=0) res[0][12]=a30;
  a30=7.8125000000000000e-01;
  a13=(a10*a08);
  a15=(a11*a07);
  a13=(a13+a15);
  a13=(a06*a13);
  a15=arg[1]? arg[1][0] : 0;
  a13=(a13*a15);
  a13=(a30*a13);
  if (res[0]!=0) res[0][13]=a13;
  a13=(a10*a07);
  a31=(a31-a13);
  a31=(a06*a31);
  a31=(a31*a15);
  a31=(a30*a31);
  if (res[0]!=0) res[0][14]=a31;
  a32=(a32*a15);
  a32=(a30*a32);
  a31=9.8066499999999994e+00;
  a32=(a32-a31);
  if (res[0]!=0) res[0][15]=a32;
  a32=4.3478260869565219e+01;
  a31=arg[1]? arg[1][1] : 0;
  a13=2.1999999999999999e-02;
  a13=(a13*a21);
  a04=(a02*a13);
  a37=2.3000000000000000e-02;
  a35=(a37*a02);
  a20=(a21*a35);
  a04=(a04-a20);
  a04=(a31-a04);
  a04=(a32*a04);
  if (res[0]!=0) res[0][16]=a04;
  a20=arg[1]? arg[1][2] : 0;
  a37=(a37*a03);
  a09=(a21*a37);
  a13=(a03*a13);
  a09=(a09-a13);
  a09=(a20-a09);
  a32=(a32*a09);
  if (res[0]!=0) res[0][17]=a32;
  a09=4.5454545454545460e+01;
  a13=arg[1]? arg[1][3] : 0;
  a35=(a03*a35);
  a37=(a02*a37);
  a35=(a35-a37);
  a35=(a13-a35);
  a09=(a09*a35);
  if (res[0]!=0) res[0][18]=a09;
  a35=(a06*a08);
  a35=(a15*a35);
  a35=(a30*a35);
  a37=5.0000000000000000e-01;
  a40=(a03*a07);
  a33=(a21*a11);
  a40=(a40+a33);
  a33=(a02*a08);
  a40=(a40-a33);
  a40=(a37*a40);
  a33=(a35*a40);
  a16=(a06*a11);
  a16=(a15*a16);
  a16=(a30*a16);
  a12=(a03*a10);
  a14=(a02*a11);
  a12=(a12+a14);
  a14=(a21*a08);
  a12=(a12+a14);
  a12=(a37*a12);
  a14=(a16*a12);
  a33=(a33-a14);
  a14=(a06*a07);
  a14=(a15*a14);
  a14=(a30*a14);
  a47=(a02*a07);
  a17=(a21*a10);
  a47=(a47-a17);
  a17=(a03*a08);
  a47=(a47+a17);
  a47=(a37*a47);
  a17=(a14*a47);
  a33=(a33+a17);
  a17=(a06*a10);
  a17=(a15*a17);
  a17=(a30*a17);
  a36=(a21*a07);
  a00=(a02*a10);
  a36=(a36+a00);
  a00=(a03*a11);
  a36=(a36-a00);
  a36=(a37*a36);
  a00=(a17*a36);
  a33=(a33+a00);
  if (res[0]!=0) res[0][19]=a33;
  a33=(a17*a12);
  a00=(a14*a40);
  a33=(a33-a00);
  a00=(a35*a47);
  a33=(a33+a00);
  a00=(a16*a36);
  a33=(a33+a00);
  if (res[0]!=0) res[0][20]=a33;
  a33=(a10+a10);
  a33=(a06*a33);
  a33=(a15*a33);
  a33=(a30*a33);
  a00=(a33*a40);
  a45=(a11+a11);
  a45=(a06*a45);
  a45=(a15*a45);
  a45=(a30*a45);
  a05=(a45*a47);
  a00=(a00+a05);
  a00=(-a00);
  if (res[0]!=0) res[0][21]=a00;
  a17=(a37*a17);
  a00=(a02*a17);
  a05=(a30*a36);
  a05=(a15*a05);
  a05=(a06*a05);
  a29=(a00+a05);
  a14=(a37*a14);
  a39=(a21*a14);
  a29=(a29-a39);
  a16=(a37*a16);
  a38=(a03*a16);
  a29=(a29-a38);
  a29=(a29*a40);
  a25=(a21*a17);
  a46=(a02*a14);
  a27=(a25+a46);
  a26=(a30*a47);
  a26=(a15*a26);
  a26=(a06*a26);
  a27=(a27+a26);
  a35=(a37*a35);
  a42=(a03*a35);
  a27=(a27+a42);
  a27=(a27*a12);
  a29=(a29-a27);
  a27=(a21*a35);
  a28=(a03*a17);
  a49=(a02*a16);
  a43=(a28+a49);
  a50=(a30*a12);
  a50=(a15*a50);
  a50=(a06*a50);
  a43=(a43+a50);
  a43=(a27-a43);
  a43=(a43*a47);
  a29=(a29+a43);
  a43=(a03*a14);
  a22=(a21*a16);
  a48=(a43-a22);
  a34=(a02*a35);
  a48=(a48-a34);
  a30=(a30*a40);
  a30=(a15*a30);
  a06=(a06*a30);
  a48=(a48+a06);
  a48=(a48*a36);
  a29=(a29+a48);
  a48=(a08*a14);
  a30=(a11*a17);
  a23=(a48-a30);
  a24=(a10*a16);
  a23=(a23-a24);
  a19=(a07*a35);
  a23=(a23+a19);
  a23=(a23*a04);
  a29=(a29+a23);
  a23=(a10*a17);
  a41=(a07*a14);
  a18=(a23+a41);
  a01=(a11*a16);
  a18=(a18-a01);
  a44=(a08*a35);
  a18=(a18-a44);
  a18=(a18*a32);
  a29=(a29+a18);
  a18=(a07*a17);
  a51=(a10*a14);
  a18=(a18-a51);
  a51=(a08*a16);
  a18=(a18-a51);
  a51=(a11*a35);
  a18=(a18+a51);
  a18=(a18*a09);
  a29=(a29+a18);
  if (res[0]!=0) res[0][22]=a29;
  a50=(a50+a49);
  a50=(a50-a27);
  a50=(a50+a28);
  a50=(a50*a40);
  a22=(a22-a06);
  a22=(a22+a34);
  a22=(a22-a43);
  a22=(a22*a12);
  a50=(a50-a22);
  a05=(a05-a38);
  a05=(a05+a00);
  a05=(a05-a39);
  a05=(a05*a47);
  a50=(a50+a05);
  a42=(a26+a42);
  a42=(a42+a25);
  a42=(a42+a46);
  a42=(a42*a36);
  a50=(a50+a42);
  a44=(a44-a01);
  a44=(a44+a23);
  a44=(a44-a41);
  a44=(a44*a04);
  a50=(a50+a44);
  a24=(a24+a19);
  a24=(a24+a30);
  a24=(a24+a48);
  a24=(a24*a32);
  a50=(a50+a24);
  a16=(a07*a16);
  a35=(a10*a35);
  a16=(a16-a35);
  a17=(a08*a17);
  a16=(a16+a17);
  a14=(a11*a14);
  a16=(a16-a14);
  a16=(a16*a09);
  a50=(a50+a16);
  if (res[0]!=0) res[0][23]=a50;
  a45=(a37*a45);
  a50=(a02*a45);
  a37=(a37*a33);
  a33=(a03*a37);
  a50=(a50+a33);
  a50=(a50*a12);
  a12=(a21*a45);
  a06=(a06+a06);
  a12=(a12-a06);
  a12=(a12*a40);
  a50=(a50+a12);
  a26=(a26+a26);
  a21=(a21*a37);
  a26=(a26+a21);
  a26=(a26*a47);
  a50=(a50-a26);
  a02=(a02*a37);
  a03=(a03*a45);
  a02=(a02-a03);
  a02=(a02*a36);
  a50=(a50+a02);
  a02=(a08*a45);
  a36=(a07*a37);
  a02=(a02+a36);
  a02=(a02*a04);
  a50=(a50-a02);
  a08=(a08*a37);
  a07=(a07*a45);
  a08=(a08-a07);
  a08=(a08*a32);
  a50=(a50+a08);
  a10=(a10*a45);
  a11=(a11*a37);
  a10=(a10-a11);
  a10=(a10*a09);
  a50=(a50+a10);
  if (res[0]!=0) res[0][24]=a50;
  if (res[0]!=0) res[0][25]=a15;
  if (res[0]!=0) res[0][26]=a31;
  if (res[0]!=0) res[0][27]=a20;
  if (res[0]!=0) res[0][28]=a13;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_cost_y_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
