- ros_topic_name: "/peg_pose"
  gz_topic_name: "/model/my_peg/pose"
  ros_type_name: "geometry_msgs/msg/PoseStamped"
  gz_type_name: "gz.msgs.Pose"
  direction: ROS_TO_GZ

- ros_topic_name: "/odometry"
  gz_topic_name: "/model/qr4/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/wrench_cmd"
  gz_topic_name: "/model/qr4/wrench_cmd"
  ros_type_name: "geometry_msgs/msg/Wrench"
  gz_type_name: "gz.msgs.Wrench"
  direction: ROS_TO_GZ


- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS

  # Camera -> ROS 2
- ros_topic_name: "/camera/image"
  gz_topic_name: "/world/mrsim/model/qr4/link/base/sensor/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA

- ros_topic_name: "/camera/camera_info"
  gz_topic_name: "/world/mrsim/model/qr4/link/base/sensor/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA
