- ros_topic_name: "/peg_pose"
  gz_topic_name: "/model/my_peg/pose"
  ros_type_name: "geometry_msgs/msg/PoseStamped"
  gz_type_name: "gz.msgs.Pose"
  direction: ROS_TO_GZ

- ros_topic_name: "/odometry"
  gz_topic_name: "/model/qr4/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/wrench_cmd"
  gz_topic_name: "/model/qr4/wrench_cmd"
  ros_type_name: "geometry_msgs/msg/Wrench"
  gz_type_name: "gz.msgs.Wrench"
  direction: ROS_TO_GZ